(function(g){var window=this;'use strict';var Nx=function(H,E){var G=g.gw(E),P=G?E:arguments;for(G=G?0:1;G<P.length;G++){if(H==null)return;H=H[P[G]]}return H},onu=function(H,E,G){H.N=!0;
H.T=g.a2(E,G)},yG=function(H,E,G){return{r8:(H.impressionLoggingUrlsV2s||[]).map(function(P){return P.baseUrl||""}),
click:(G.loggingUrls||[]).map(function(P){return P.baseUrl||""}),
close:(E.dismissLoggingUrlsV2s||[]).map(function(P){return P.baseUrl||""}),
A$:(E.impressionLoggingUrlsV2s||[]).map(function(P){return P.baseUrl||""}),
LF:(E.clickLoggingUrlsV2s||[]).map(function(P){return P.baseUrl||""})}},w93=function(H,E){var G=E.cardId?E.cardId:"cr:"+H.B,P=H.S.K().experiments.xp("enable_error_corrections_infocard_web_client");
if(!E.content&&E.teaser.simpleCardTeaserRenderer&&P){var Q=E.teaser.simpleCardTeaserRenderer,e=E.icon?E.icon.infoCardIconRenderer:null;if(Q.channelAvatar&&Q.channelAvatar.thumbnails&&Q.channelAvatar.thumbnails.length>0)var w=ba(Q.channelAvatar.thumbnails,22,22).url;E={id:G,timestamp:H.B,type:"simple",teaserText:g.b_(Q.message),teaserDurationMs:Number(E.cueRanges[0].teaserDurationMs),startMs:Number(E.cueRanges[0].startCardActiveMs),autoOpen:!!E.autoOpen,sessionData:{},sponsored:!1,iV:{},HR:null,MM:Q.trackingParams?
g.Bn(Q.trackingParams):null,YW:e&&e.trackingParams?g.Bn(e.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,Ss:null,title:"",customMessage:"",url:null,onClickCommand:Q.onTapCommand||null,Bv:w};ia(H,E)}else{var t;if((t=E.content)==null?0:t.simpleCardContentRenderer){if(!E.cueRanges.length)return;w=(Q=E.content)==null?void 0:Q.simpleCardContentRenderer;Q=E.teaser.simpleCardTeaserRenderer;e=E.icon?E.icon.infoCardIconRenderer:null;E={id:G,timestamp:H.B,type:"simple",teaserText:g.b_(Q.message),
teaserDurationMs:Number(E.cueRanges[0].teaserDurationMs),startMs:Number(E.cueRanges[0].startCardActiveMs),autoOpen:!!E.autoOpen,sessionData:qx(H,G,E,w),sponsored:!1,iV:yG(w,Q,w.command),HR:w.trackingParams?g.Bn(w.trackingParams):null,MM:Q.trackingParams?g.Bn(Q.trackingParams):null,YW:e&&e.trackingParams?g.Bn(e.trackingParams):null,imageUrl:ba(w.image.thumbnails,290,290).url,displayDomain:w.displayDomain?g.b_(w.displayDomain):null,showLinkIcon:!!w.showLinkIcon,Ss:null,title:w.title?g.b_(w.title):"",
customMessage:w.callToAction?g.b_(w.callToAction):"",url:g.X(w.command,g.nR).url?RZ({pause_on_navigation:!H.context.videoData.isLivePlayback,target:"new",value:g.X(w.command,g.nR).url}):null,onClickCommand:null};ia(H,E)}else{var k;if((k=E.content)==null?0:k.collaboratorInfoCardContentRenderer){if(!E.cueRanges.length)return;w=(e=E.content)==null?void 0:e.collaboratorInfoCardContentRenderer;Q=E.teaser.simpleCardTeaserRenderer;e=E.icon?E.icon.infoCardIconRenderer:null;E={id:G,timestamp:H.B,type:"collaborator",
teaserText:g.b_(Q.message),teaserDurationMs:Number(E.cueRanges[0].teaserDurationMs),startMs:Number(E.cueRanges[0].startCardActiveMs),autoOpen:!!E.autoOpen,sessionData:qx(H,G,E,w),sponsored:!1,iV:yG(w,Q,w.endpoint),HR:w.trackingParams?g.Bn(w.trackingParams):null,MM:Q.trackingParams?g.Bn(Q.trackingParams):null,YW:e&&e.trackingParams?g.Bn(e.trackingParams):null,channelId:g.X(w.endpoint,g.kd).browseId,customMessage:w.customText?g.b_(w.customText):null,profileImageUrl:ba(w.channelAvatar.thumbnails,290,
290).url,title:w.channelName?g.b_(w.channelName):"",metaInfo:[w.subscriberCountText?g.b_(w.subscriberCountText):""],url:RZ({pause_on_navigation:!H.context.videoData.isLivePlayback,target:"new",value:g.X(w.endpoint,g.kd).canonicalBaseUrl?g.X(w.endpoint,g.kd).canonicalBaseUrl:"/channel/"+g.X(w.endpoint,g.kd).browseId}),onClickCommand:null};ia(H,E)}else{var W;if((W=E.content)==null?0:W.playlistInfoCardContentRenderer){if(!E.cueRanges.length)return;var I;w=(I=E.content)==null?void 0:I.playlistInfoCardContentRenderer;
Q=E.teaser.simpleCardTeaserRenderer;e=E.icon?E.icon.infoCardIconRenderer:null;E={id:G,timestamp:H.B,type:"playlist",teaserText:g.b_(Q.message),teaserDurationMs:Number(E.cueRanges[0].teaserDurationMs),startMs:Number(E.cueRanges[0].startCardActiveMs),autoOpen:!!E.autoOpen,sessionData:qx(H,G,E,w),sponsored:!1,iV:yG(w,Q,w.action),HR:w.trackingParams?g.Bn(w.trackingParams):null,MM:Q.trackingParams?g.Bn(Q.trackingParams):null,YW:e&&e.trackingParams?g.Bn(e.trackingParams):null,fV:ba(w.playlistThumbnail.thumbnails,
258,290).url,customMessage:w.customMessage?g.b_(w.customMessage):null,playlistVideoCount:g.b_(w.playlistVideoCount),title:w.playlistTitle?g.b_(w.playlistTitle):"",metaInfo:[w.channelName?g.b_(w.channelName):"",w.videoCountText?g.b_(w.videoCountText):""],url:RZ({pause_on_navigation:!H.context.videoData.isLivePlayback,target:"new",value:ec3(w.action)}),onClickCommand:null};ia(H,E)}else{var A;if((A=E.content)==null?0:A.videoInfoCardContentRenderer){if(!E.cueRanges.length)return;var m;w=(m=E.content)==
null?void 0:m.videoInfoCardContentRenderer;Q=E.teaser.simpleCardTeaserRenderer;e=E.icon?E.icon.infoCardIconRenderer:null;E={id:G,timestamp:H.B,type:"video",teaserText:g.b_(Q.message),teaserDurationMs:Number(E.cueRanges[0].teaserDurationMs),startMs:Number(E.cueRanges[0].startCardActiveMs),autoOpen:!!E.autoOpen,sessionData:qx(H,G,E,w),sponsored:!1,iV:yG(w,Q,w.action),HR:w.trackingParams?g.Bn(w.trackingParams):null,MM:Q.trackingParams?g.Bn(Q.trackingParams):null,YW:e&&e.trackingParams?g.Bn(e.trackingParams):
null,fV:ba(w.videoThumbnail.thumbnails,258,290).url,videoDuration:w.lengthString?g.b_(w.lengthString):null,customMessage:w.customMessage?g.b_(w.customMessage):null,title:w.videoTitle?g.b_(w.videoTitle):"",metaInfo:[w.channelName?g.b_(w.channelName):"",w.viewCountText?g.b_(w.viewCountText):""],isLiveNow:!!w.badge,url:RZ({pause_on_navigation:!H.context.videoData.isLivePlayback,target:"new",value:ec3(w.action)}),onClickCommand:null};ia(H,E)}}}}}H.B++},hcZ=function(H,E,G){var P=P===void 0?{}:P;
var Q;return Q=g.Pm(H,E,function(){g.sz(Q);G.apply(H,arguments)},P)},ba=function(H,E,G){for(var P=-1,Q=-1,e=0;e<H.length;e++){if(H[e].height===E||H[e].width===G)return H[e];
((H[e].height||0)<E||(H[e].width||0)<G)&&(P<0||(H[P].height||0)<(H[e].height||0)||(H[P].width||0)<(H[e].width||0))?P=e:((H[e].height||0)>=E||(H[e].width||0)>=G)&&(Q<0||(H[Q].height||0)>(H[e].height||0)||(H[Q].width||0)>(H[e].width||0))&&(Q=e)}return H[Q>=0?Q:P]},$m$=function(H,E,G,P,Q){if(E.length!=2||G.length!=2)throw Error("Start and end points must be 2D");
Jj.call(this,H,E,G,P,Q)},kvW=function(){rh||(rh=new g.Wt(function(){tPH()},20));
var H=rh;H.isActive()||H.start()},W3o=function(H){return Math.pow(H,3)},mmH=function(H,E,G){if(E.targetUrl&&(!G||G.type!=="keypress"||G.keyCode===13)){for(var P=G.target;P&&!g.T2(P,"ytp-ce-element");){g.T2(P,"subscribe-label")&&IiZ(H,E);
if(g.T2(P,"ytp-ce-channel-subscribe"))return;P=P.parentElement||null}if(!P||g.T2(P,"ytp-ce-element-hover")){G.preventDefault();G.stopPropagation();if(P=H.W[E.id])AsH(H,P,E),P.element.blur();if(G.ctrlKey||G.metaKey||E.Exm==="new")IiZ(H,E),H.player.sendVideoStatsEngageEvent(17,void 0),H.player.pauseVideo(),G=g.x5(Bc(H,E.targetUrl)),G=g.Uw(G),g.YK(G,void 0,E.sessionData);else{var Q=g.sn(H.player.K())||H.player.getVideoData().Xg,e=function(){var w=Bc(H,E.targetUrl),t=E.sessionData,k=E.watchEndpoint,W=
g.oz(w);Q&&W&&(W.v||W.list)?H.player.OF(W.v,t,W.list,!1,void 0,k||void 0):g.tU(w,t)};
IiZ(H,E,function(){H.player.sendVideoStatsEngageEvent(17,e)})}}}},Yk=function(H,E,G){E?typeof E==="string"?E={"class":E}:Array.isArray(E)&&(E={"class":E.join(" ")}):E={};
E.dir=g.Y5(G);return{J:H,j:E,iJ:G}},AsH=function(H,E,G){g.Tn(E.element,"ytp-ce-element-hover");
g.Tn(E.element,"ytp-ce-force-expand");Xo(H,G.id,!1)},RZ=function(H){if(!H)return null;
var E=g.x5(umW(H.value));E=g.Uw(E);if(!E)return null;var G=Zp(H.target,vnW,"current");if(G==null)H=null;else{var P=H.show_link_icon;H=new MPC(E,G,P==="true"||P==="false"?P==="true":!0,H.pause_on_navigation!=null?H.pause_on_navigation:!0)}return H},DmD=function(H,E){E<H.startTime&&(H.endTime=E+H.endTime-H.startTime,H.startTime=E);
H.progress=(E-H.startTime)/(H.endTime-H.startTime);H.progress>1&&(H.progress=1);H.C=1E3/(E-H.D);H.D=E;dmR(H,H.progress);H.progress==1?(H.L=0,LG(H),H.onFinish(),H.K1()):H.isPlaying()&&H.h4()},umW=function(H){return typeof H==="string"?H:""},dmR=function(H,E){typeof H.T==="function"&&(E=H.T(E));
H.coords=Array(H.W.length);for(var G=0;G<H.W.length;G++)H.coords[G]=(H.B[G]-H.W[G])*E+H.W[G]},nn$=function(H,E){for(var G={},P=g.R(E.attributes),Q=P.next();!Q.done;Q=P.next())Q=Q.value,G[Q.name]=Q.nodeValue;
for(P=0;P<E.childNodes.length;P++)if(Q=E.childNodes[P],g.rW(Q)&&Q.nodeType==1){if(G[Q.tagName])var e=G[Q.tagName];else if(Q.tagName==="data"){Q.childNodes.length>0&&(e=Q.childNodes[0].nodeValue,G[Q.tagName]=typeof e==="string"?e.trim():e);continue}else e=[],G[Q.tagName]=e;Q&&Q.tagName==="TEXT"?Q.childNodes.length===1&&Q.childNodes[0].nodeType===3?e.push(Q.childNodes[0].nodeValue):e.push(""):Q&&e.push(nn$(H,Q))}return G},K3H=function(H,E){H.D||(H.D=g.N0(function(){aiW(this);
O3W(this)},E,H))},Ndd=function(H){var E=H.player.getVideoData(),G=E.videoId;
H.D&&H.D.abort();G={method:"POST",onFinish:function(Q){var e=H.D=null;Q.status===200&&(Q=Q.responseText,Q.substring(0,3)===")]}"&&(Q=Q.substring(3),e=JSON.parse(Q),e=jN3(e,csu(H))));la(H,e)},
urlParams:{v:G},withCredentials:!0};H.L_&&(G.urlParams.ptype="embedded");var P=E.q6;P&&(G.postParams={ad_tracking:P});if(E=g.BN7(E))if(E=g.x5(E),E=g.Uw(E))H.D=g.a2(E,G)},b3W=function(H,E){var G=null;
switch(E.type){case "VIDEO":H={J:"div",QN:["ytp-ce-element","ytp-ce-video"],j:{tabindex:"0","aria-label":E.iF||"","aria-hidden":"true"},V:[{J:"div",Y:"ytp-ce-element-shadow"},{J:"div",Y:"ytp-ce-covering-image",j:U6(E)},{J:"div",Y:"ytp-ce-covering-shadow-top"},{J:"a",Y:"ytp-ce-covering-overlay",j:{href:Bc(H,E.targetUrl),tabindex:"-1"},V:[{J:"div",QN:["ytp-ce-video-title","ytp-webkit-ellipsis"],j:{dir:g.Y5(E.title||"")},iJ:E.title},{J:"div",Y:E.iZ?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
iJ:E.videoDuration||void 0}]}]};G=new g.D(H);break;case "PLAYLIST":H={J:"div",QN:["ytp-ce-element","ytp-ce-playlist"],j:{tabindex:"0","aria-label":E.iF||"","aria-hidden":"true"},V:[{J:"div",Y:"ytp-ce-element-shadow"},{J:"div",Y:"ytp-ce-covering-image",j:U6(E)},{J:"div",Y:"ytp-ce-covering-shadow-top"},{J:"a",Y:"ytp-ce-covering-overlay",j:{href:Bc(H,E.targetUrl),tabindex:"-1"},V:[{J:"div",QN:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],j:{dir:g.Y5(E.title||"")},iJ:E.title},{J:"div",Y:"ytp-ce-playlist-count",
V:[{J:"div",Y:"ytp-ce-playlist-icon"},{J:"div",Y:"ytp-ce-playlist-count-text",iJ:E.playlistLength||void 0}]}]}]};G=new g.D(H);break;case "CHANNEL":G={J:"div",QN:["ytp-ce-element","ytp-ce-channel",E.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],j:{tabindex:"0","aria-label":E.iF||"","aria-hidden":"true"},V:[{J:"div",Y:"ytp-ce-element-shadow"},{J:"div",Y:"ytp-ce-expanding-overlay",V:[{J:"div",Y:"ytp-ce-expanding-overlay-hider"},{J:"div",Y:"ytp-ce-expanding-overlay-background"},{J:"div",Y:"ytp-ce-expanding-overlay-content",
V:[{J:"div",Y:"ytp-ce-expanding-overlay-body",V:[{J:"div",Y:"ytp-ce-expanding-overlay-body-padding",V:[{J:"a",QN:["ytp-ce-channel-title","ytp-ce-link"],j:{href:Bc(H,E.targetUrl),target:"_blank",tabindex:"-1",dir:g.Y5(E.title||"")},iJ:E.title},E.subscribeButton?{J:"div",Y:"ytp-ce-subscribe-container",V:[{J:"div",Y:"ytp-ce-channel-subscribe"}]}:"",E.subscribersText?{J:"div",Y:"ytp-ce-channel-subscribers-text",iJ:E.subscribersText}:"",E.metadata?{J:"div",QN:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],iJ:E.metadata}:""]}]}]}]},{J:"div",Y:"ytp-ce-expanding-image",j:U6(E)}]};G=new g.D(G);var P=g.V_(document,"div","ytp-ce-channel-subscribe",G.element)[0];if(E.subscribeButton&&E.channelId){g.aG(P,"ytp-ce-subscribe-button");if(H.player.K().W){var Q=null;var e=E.sessionData.itct}else Q="endscreen",e=null;Q=new g.FE(E.subscribeButton.subscribeText,E.subscribeButton.subscribeCount,E.subscribeButton.unsubscribeText,E.subscribeButton.unsubscribeCount,!!E.subscribeButton.enabled,!!E.subscribeButton.classic,
E.channelId,!!E.subscribeButton.subscribed,Q,e,H.player,!1);P.appendChild(Q.element);H.N.push(Q)}break;case "WEBSITE":H={J:"div",QN:["ytp-ce-element","ytp-ce-website"],j:{tabindex:"0","aria-label":E.iF||"","aria-hidden":"true"},V:[{J:"div",Y:"ytp-ce-element-shadow"},{J:"div",Y:"ytp-ce-expanding-overlay",V:[{J:"div",Y:"ytp-ce-expanding-overlay-hider"},{J:"div",Y:"ytp-ce-expanding-overlay-background"},{J:"div",Y:"ytp-ce-expanding-overlay-content",V:[{J:"div",Y:"ytp-ce-expanding-overlay-body",V:[{J:"div",
Y:"ytp-ce-expanding-overlay-body-padding",V:[{J:"div",Y:"ytp-ce-website-title",j:{dir:g.Y5(E.title||"")},iJ:E.title},{J:"div",Y:"ytp-ce-website-metadata",iJ:E.metadata},{J:"a",QN:["ytp-ce-website-goto","ytp-ce-link"],j:{href:Bc(H,E.targetUrl),target:"_blank",tabindex:"-1"},iJ:E.callToAction}]}]}]}]},{J:"div",Y:"ytp-ce-expanding-image",j:U6(E)},{J:"div",Y:"ytp-ce-expanding-icon",j:ysK(E.iconUrl)}]};G=new g.D(H);break;case "CREATOR_MERCHANDISE":G="",E.productPrice&&(G={J:"div",Y:"ytp-ce-merchandise-price-container",
V:[{J:"div",Y:"ytp-ce-merchandise-price",iJ:E.productPrice}]},E.additionalFeesText&&G.V.push({J:"div",Y:"ytp-ce-merchandise-additional-fees",iJ:E.additionalFeesText})),H={J:"div",QN:["ytp-ce-element","ytp-ce-merchandise"],j:{tabindex:"0","aria-label":E.iF||"","aria-hidden":"true"},V:[{J:"div",Y:"ytp-ce-element-shadow"},{J:"div",Y:"ytp-ce-expanding-overlay",V:[{J:"div",Y:"ytp-ce-expanding-overlay-hider"},{J:"div",Y:"ytp-ce-expanding-overlay-background"},{J:"div",Y:"ytp-ce-expanding-overlay-content",
V:[{J:"div",Y:"ytp-ce-expanding-overlay-body",V:[{J:"div",Y:"ytp-ce-expanding-overlay-body-padding",V:[{J:"div",Y:"ytp-ce-merchandise-title",j:{dir:g.Y5(E.title||"")},iJ:E.title},G,{J:"div",Y:"ytp-ce-merchandise-metadata",iJ:E.metadata},{J:"a",QN:["ytp-ce-merchandise-goto","ytp-ce-link"],j:{href:Bc(H,E.targetUrl),target:"_blank",tabindex:"-1"},iJ:E.callToAction}]}]}]}]},{J:"div",Y:"ytp-ce-expanding-image",j:U6(E)},{J:"div",Y:"ytp-ce-merchandise-invideo-cta-container",V:[{J:"div",Y:"ytp-ce-merchandise-invideo-cta",
iJ:E.callToAction||void 0}]}]},G=new g.D(H)}E.isPlaceholder&&g.aG(G.element,"ytp-ce-placeholder");return G},i3o=function(H,E){this.merchant=H;
this.price=E},qNo=function(H){var E=g.X3(),G=g.ri();
G&&E&&H.endscreen.visualElement&&g.NL(g.IC)(void 0,G,E,H.endscreen.visualElement)},RcJ=function(H,E){E=!E.isCued()&&!g.F(E,1024);
H.W.BT(E);H.G.BT(E)},LG=function(H){H=g.bY(H);
delete xk[H];g.ZR(xk)&&rh&&rh.stop()},Js3=function(H){var E=g.ws(H);
H=g.or(H);return new g.Yn(E.x,E.y,H.width,H.height)},rsC=function(H,E){return function(){var G=g.c4.apply(0,arguments);
H.Iu()||H.WF.push(g.eD.c6(function(){E.apply(null,g.EC(G))}))}},YNo=function(H,E){H.L_.pP?(E=new z3([0,
H.W.scrollTop],[0,E.bv.offsetTop],600,BdW),H.context.G.listen(E,"animate",function(G){H.W.scrollTop=G.y}),H.context.G.listen(E,"finish",function(G){H.W.scrollTop=G.y}),E.play()):(H.L_.BT(!0),H.W.scrollTop=E.bv.offsetTop,H.L_.BT(!1))},z3=function(H,E,G,P){g.uf.call(this);
if(!Array.isArray(H)||!Array.isArray(E))throw Error("Start and end parameters must be arrays");if(H.length!=E.length)throw Error("Start and end points must be the same length");this.W=H;this.B=E;this.duration=G;this.T=P;this.coords=[];this.progress=this.C=0;this.D=null},ia=function(H,E){if(!X9H(H,E)||Z3J(H,E)){var G=CMK(H,E);
if(G){var P={S7:E,bv:G.element,zm:!1};if(E.onClickCommand)H.S.U("web_infocards_teaser_show_logging_fix")&&(H.G6||lio(H),L3K(H,E.id),G=H.findLastIndex(P),g.nH(H.cards,G,0,P));else{H.isInitialized||gno(H);L3K(H,E.id);var Q=H.findLastIndex(P);g.nH(H.cards,Q,0,P);G.mx(H.W,Q);H.tM()}E.autoOpen?H.addCueRange(E.startMs,0x8000000000000,E.id,function(){H.G||(H.L=P,T3(H),YNo(H,P),VG(H,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(G=H.context.S.getCurrentTime()*1E3,G<5E3&&G>E.startMs&&UmK(H,P),H.addCueRange(E.startMs,
E.startMs+1,E.id,function(){UmK(H,P)}),T3(H))}}},zcW=function(H){var E=new g.D({J:"div"});
g.Jx(E.element,!1);var G=new xmM(H.player,E.element,S8(H));g.d(G,E);E.mx(H.W.element);G.b_();return G},Bc=function(H,E){H=H.player.K();
if(E){if(E.startsWith("//"))return H.protocol+":"+E;if(E.startsWith("/"))return g.sW(H)+E}else return"";return E},Td3=function(H,E){this.context=H;
this.L=E},VPH=function(H,E){var G=G===void 0?0:G;
var P=Js3(E).width;g.lN(E,P);G=new $m$(E,[P,E.offsetTop],[P-P-G,E.offsetTop],200,W3o);g.d(H,G);H.context.G.listen(G,"begin",function(){g.Jx(E,!0)});
G.play()},fiK=function(H){var E=H.player.getVideoData();
if(E.BA){var G=H.player.K().T$.get(E.videoId);if(G){var P={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(Q,e,w){Q=H.loadNumber;e=E.videoId;H.loaded&&H.loadNumber===Q&&H.player.getVideoData().videoId===e&&(w=g.dw(w)&&w.responseXML?w.responseXML:null)&&SNK(H,w)}};
g.Sh()&&(P.onFinish=rsC(H,P.onFinish));P.postParams={ic_only:"1"};F3Z(P,G);H.N=!0;g.a2(E.BA,P)}}},Fo=function(H){H.publish("cardstatechange",H.pR()&&H.DG()?1:0)},p9K=function(H){if(!H.metaInfo||H.metaInfo.length===0)return"";
var E=[];H=g.R(H.metaInfo);for(var G=H.next();!G.done;G=H.next())E.push(Yk("li","",G.value));return{J:"ul",Y:"iv-card-meta-info",V:E}},HyH=function(H,E){g.DK.call(this,H);
this.coords=E.coords;this.x=E.coords[0];this.y=E.coords[1];this.z=E.coords[2];this.duration=E.duration;this.progress=E.progress;this.fps=E.C;this.state=E.L},E0R=function(H,E,G){function P(eu){if(eu){var QM=[],$Q=eu.videoId;
$Q&&QM.push("v="+$Q);($Q=eu.playlistId)&&QM.push("list="+$Q);(eu=eu.startTimeSeconds)&&QM.push("t="+eu);return"/watch?"+QM.join("&")}}
function Q(eu){var QM=eu.hovercardButton;if(!QM)return null;QM=QM.subscribeButtonRenderer;if(!QM)return null;var $Q=e(QM.unsubscribedButtonText),En=e(QM.subscribedButtonText);if(QM.subscribed){var Dj=e(QM.subscriberCountWithUnsubscribeText);var gl=e(QM.subscriberCountText)}else Dj=e(QM.subscriberCountText),gl=e(QM.subscriberCountWithSubscribeText);var oD=null;if(eu.signinEndpoint){oD=Nx(eu,"signinEndpoint","webNavigationEndpointData","url");if(!oD){var GZ,qT;oD=(qT=g.X((GZ=QM.signInEndpoint)==null?
void 0:GZ.commandMetadata,g.Mk))==null?void 0:qT.url}if(!oD)return null}return $Q&&(En||oD)?{subscribed:QM.subscribed,subscribeText:$Q,subscribeCount:Dj,unsubscribeText:En,unsubscribeCount:gl,enabled:QM.enabled,signinUrl:oD,classic:eu.useClassicSubscribeButton}:null}
function e(eu){if(!eu)return null;var QM=eu.simpleText;return QM?QM:eu.runs?g.wH(eu.runs,function($Q){return $Q.text}).join(""):null}
E=E.endscreenElementRenderer;if(!E)return null;var w=E.style,t=E.endpoint||{},k=null,W=null,I=!1,A=null,m=null,u=null,v=null,n=!1,O=null,q=null,N=null,r=null,B=null,l=null;if(w==="VIDEO")g.X(t,g.nR)?k=g.X(t,g.nR).url:(l=g.X(t,g.Xt),k=P(l)),W=!1,A=H,E.thumbnailOverlays?(I=E.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,m=e(I.text),I=I.style==="LIVE"):m=e(E.videoDuration);else if(w==="PLAYLIST")g.X(t,g.nR)?k=g.X(t,g.nR).url:(l=g.X(t,g.Xt),k=P(l)),W=!1,A=H,u=e(E.playlistLength);else if(w===
"CHANNEL"){if(n=Nx(t,"browseEndpoint","browseId"))v=n,k="/channel/"+v;W=!1;A="new";(n=!!E.isSubscribe)?O=Q(E):q=e(E.subscribersText)}else w==="WEBSITE"?((N=Nx(t,"urlEndpoint","url"))&&(k=N),W=!0,A="new",N=E.icon.thumbnails[0].url):w==="CREATOR_MERCHANDISE"&&(E.productPrice&&(r=e(E.productPrice)),E.additionalFeesText&&(B=e(E.additionalFeesText)),(W=Nx(t,"urlEndpoint","url"))&&(k=W),W=!0,A="new");H=Nx(E,"title","accessibility","accessibilityData","label");var S=E.endpoint?E.endpoint.clickTrackingParams:
null,z="";if(E.metadata){var Pt=e(E.metadata);Pt&&(z=Pt)}return{id:"element-"+G,type:w,title:e(E.title),metadata:z,callToAction:e(E.callToAction),qT:E.image,iconUrl:N,left:Number(E.left),width:Number(E.width),top:Number(E.top),aspectRatio:Number(E.aspectRatio),startMs:Math.floor(Number(E.startMs)),endMs:Math.floor(Number(E.endMs)),videoDuration:m,iZ:I,playlistLength:u,channelId:v,subscribeButton:O,subscribersText:q,isSubscribe:n,targetUrl:k||null,HP$:W,sessionData:S?{itct:S}:null,Exm:A,iF:H?H:null,
isPlaceholder:E.isPlaceholder,impressionUrls:fG(E.impressionUrls||[],pG),XF_:fG(E.hovercardShowUrls||[],pG),clickUrls:fG(t.loggingUrls||[],pG),visualElement:g.Bn(E.trackingParams),productPrice:r,additionalFeesText:B,watchEndpoint:l||null}},T3=function(H){g.Bt(H.S.getRootNode(),"ytp-cards-shopping-active",GqW(H))},PkD=function(H){g.UM.call(this,H);
this.D=this.endscreen=null;this.W={};this.C={};this.T=this.G=null;this.N=[];this.L=null;this.p_=!0;this.B=0;H=H.K();this.L_=g.nb(H)||g.PZ(H);this.events=new g.Z0(this);g.d(this,this.events);this.events.Z(this.player,g.Ya("creatorendscreen"),this.onCueRangeEnter);this.events.Z(this.player,g.XT("creatorendscreen"),this.onCueRangeExit);this.events.Z(this.player,"resize",this.h7);this.events.Z(window,"focus",this.T6a);this.load();var E=g.pu("STYLE");(g.lw("HEAD")[0]||document.body).appendChild(E);this.addOnDisposeCallback(function(){g.LQ(E)});
E.sheet&&(E.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),E.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},qx=function(H,E,G,P){return{feature:G.feature?G.feature:"cards",
src_vid:H.context.videoData.videoId,annotation_id:E,ei:H.context.videoData.eventId||"",itct:P.trackingParams||""}},csu=function(H){return H.player.getVideoData().Xg?"current":H.L_?"new":"current"},QTR=function(H){return H.customMessage?Yk("div","iv-card-message",H.customMessage):""},sTZ=function(H,E,G,P,Q,e,w){this.L=H;
this.G=E;this.X=G;this.videoData=P;this.logger=Q;this.S=e;this.W=w},haC=function(H){if(!H)return null;
var E=Zp(H.type,o0J),G=Zp(H.trigger,eaH);H=H.url;H=Array.isArray(H)&&H.length?H[0]:H;H=RZ(H?H:null);return E?new wVo(E,G,H):null},Hr=function(H,E,G,P,Q,e,w){H.context.L.listen(E,"click",function(t){H.x8(G,P,Q,e||[],w||0,t)});
H.context.L.listen(E,"touchstart",function(){H.au=!1});
H.context.L.listen(E,"touchmove",function(){H.au=!0})},tBu=function(H,E){var G,P;
if(E=(G=E.getWatchNextResponse())==null?void 0:(P=G.cards)==null?void 0:P.cardCollectionRenderer)H.p_=!0,$FM(H,E),E.headerText&&H.r6&&(G=g.b_(E.headerText),H.player.U("player_tooltip_data_title_killswitch")?H.r6.setAttribute("title",G):H.r6.setAttribute("data-tooltip-title",G))},WXR=function(H,E){var G=H.player.getVideoData().clientPlaybackNonce;
H=H.player.getCurrentTime().toFixed(2);G={CPN:G,AD_CPN:G,MT:H};H=[];for(var P=0;P<E.length;P++)H.push(kqW(E[P],G));return H},I83=function(H,E){E=E.data;
E.autoOpenMs&&H.addCueRange(E.autoOpenMs,0x8000000000000,"",function(){VG(H,"YOUTUBE_DRAWER_AUTO_OPEN")});
E.autoCloseMs&&H.addCueRange(E.autoCloseMs,0x8000000000000,"",function(){EK(H)});
var G=E.headerText;g.rA(H.FI,G);H.T&&(H.S.U("player_tooltip_data_title_killswitch")?H.T.setAttribute("title",G):H.T.setAttribute("data-tooltip-title",G));E.eventId&&(H.eventId=E.eventId);H.PF=g.Bn(E.trackingParams);H.N=g.Bn(E.closeTrackingParams);H.YW=g.Bn(E.iconTrackingParams)},xmM=function(H,E,G){Ga.call(this,E,G);
var P=this;this.S=H;this.eventId=null;this.G6=this.T$=this.dP=this.G=this.isInitialized=!1;this.cards=[];this.s7=this.T=this.O7=this.C=this.eR=this.L=null;this.p_=[];this.WF=this.N=this.YW=this.PF=null;this.B=0;this.E7=new g.Wt(function(){},G.X.CL?4E3:3E3);
g.d(this,this.E7);this.hm=new g.Wt(function(){});
g.d(this,this.hm);this.Jm=new Td3(G,function(Q,e,w,t,k,W){Hr(P,Q,e,w,t,k,W)});
this.L_=new g.D({J:"div",Y:"iv-drawer",j:{id:"iv-drawer"},V:[{J:"div",Y:"iv-drawer-header",j:{"aria-role":"heading"},V:[{J:"span",Y:"iv-drawer-header-text"},{J:"button",QN:["iv-drawer-close-button","ytp-button"],j:{"aria-label":"Hide cards",tabindex:"0"}}]},{J:"div",Y:"iv-drawer-content"}]});g.d(this,this.L_);this.D=this.L_.element;this.MZ=new g.NB(this.L_,330);g.d(this,this.MZ);this.FI=g.mO("iv-drawer-header-text",this.D);this.W=g.mO("iv-drawer-content",this.D);this.addCueRange(0,G.videoData.lengthSeconds*
1E3,"",function(){P.dP&&VG(P,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(P.dP=P.G)&&EK(P)});
this.z$=new g.Z0(this);g.d(this,this.z$);this.S.addEventListener("videodatachange",this.QW.bind(this))},AOW=function(H){if(!H.customMessage)return"";
var E=["iv-card-action","iv-card-primary-link"],G={};H.Ss&&(E.push("iv-card-action-icon"),G.style="background-image: url("+H.Ss+");");G.dir=g.Y5(H.customMessage);var P=[{J:"span",iJ:H.customMessage}];H.showLinkIcon&&(P.push("\u00a0"),P.push({J:"span",Y:"iv-card-link-icon"}));return{J:"div",QN:E,j:G,V:P}},Zp=function(H,E,G){for(var P in E)if(E[P]===H)return H;
return G},Pr=function(H,E,G,P){if(P){E=g.R(E);
for(var Q=E.next();!Q.done;Q=E.next())H.L(Q.value,P,G.id,G.sessionData,G.iV.click,5)}},L3K=function(H,E){if(E=mFu(H,E))E===H.L&&(H.L=null),H.S.removeCueRange(E.S7.id),g.LQ(E.bv),g.Ih(H.cards,E),H.tM(),T3(H)},kqW=function(H,E){return H.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(G){var P=unescape(G);
P=P.substring(1,P.length-1);return E[P]?escape(E[P]):G})},sK=function(H,E,G){function P(){e||(Q++,Q===E.length&&(w.stop(),G&&G()))}
if(!E||E.length===0||QI(H))G&&G();else{E=WXR(H,E);var Q=0,e=!1,w=new g.Wt(function(){e=!0;G&&G()},1E3,H);
w.start();for(H=0;H<E.length;H++)g.iN(E[H],P)}},la=function(H,E,G){G=G===void 0?!0:G;
H.player.dV("creatorendscreen");H.G&&(H.G.dispose(),H.G=null,H.T.dispose(),H.T=null);for(var P=g.R(Object.values(H.W)),Q=P.next();!Q.done;Q=P.next())Q.value.dispose();H.W={};H.C={};H.N.length>0&&(H.N.forEach(function(t){t.dispose()}),H.N.length=0);
H.L&&(g.Tn(H.L,"ytp-ce-element-show"),H.L.setAttribute("aria-hidden","true"));H.B=0;if((H.endscreen=E)&&E.elements){G&&qNo(H);G=[];P=new g.cP(E.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});G.push(P);H.player.K().W||(H.G=new g.D({J:"div",Y:"ytp-ce-shadow"}),g.as(H.player,H.G.element,4),H.T=new g.NB(H.G,200));for(P=0;P<E.elements.length;++P){Q=E.elements[P];var e=b3W(H,Q);if(e){H.W[Q.id]=e;H.C[Q.id]=Q;g.as(H.player,e.element,4);var w=new g.cP(Q.startMs,Q.endMs,{id:"ytp-ce-element-"+
Q.id,namespace:"creatorendscreen"});G.push(w);uLM(H,e,Q)}else g.p5(new g.LN("buildEndscreenElement null",Q))}H.player.MV(G);H.h7()}},BdW=function(H){return 3*H*H-2*H*H*H},pG=function(H){return H.baseUrl||null},mFu=function(H,E){return g.VS(H.cards,function(G){return G.S7.id===E})},Z3J=function(H,E){H.WF=E;
var G=H.S.getVideoData();if(!G)return!1;G=g.Yd(G);if(G==null?0:G.markersMap)for(var P,Q=0;((P=G)==null?void 0:P.markersMap.length)>Q;Q++){var e=void 0,w=(e=G)==null?void 0:e.markersMap[Q];if(w.key==="ERROR_CORRECTION_MARKERS"&&(e=void 0,(w=(e=w.value)==null?void 0:e.markers)&&w.length>0))return P=void 0,E.startMs=((P=g.X(w[0],g.xDt))==null?void 0:P.timeRangeStartMillis)||0,H.WF=null,!0}return!1},tPH=function(){var H=g.Gl();
g.kn(xk,function(E){DmD(E,H)});
g.ZR(xk)||kvW()},gno=function(H){g.rl(H.E2(),[g.JN.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.as(H.S,H.D,5);H.Fi();H.T=g.mO("ytp-cards-button",H.S.getRootNode());H.s7=g.mO("iv-drawer-close-button",H.D);H.isInitialized=!0},MBC=function(H,E){return E?E:v0$(H)?"current":"new"},ysK=function(H){return H?{style:"background-image: url("+H+")"}:{}},oU=function(H){return H.L&&H.L.S7?H.L.S7:H.cards[0]&&H.cards[0].S7?H.cards[0].S7:null},SNK=function(H,E){var G=!1,P=E.getElementsByTagName("annotations");
if(P&&!(P.length<1)&&(P=P[0].getAttribute("itct"))){var Q=g.ri();if(Q){var e=g.X3();e&&g.NL(g.vx)(void 0,Q,e,[g.Bn(P)])}}E=E.getElementsByTagName("annotation");for(P=0;P<E.length;P++){e=nn$(H,E[P]);Q=null;try{if(e){var w=e.id,t=/.+/;var k=typeof w==="string"&&t!=null&&w!=null&&w.match(t)?w:"";var W=Zp(e.type,dF3),I=Zp(e.style,DFK),A=umW(e.data),m=A.length!==0?JSON.parse(A):{};var u=e.action;e=haC;if(u==null)var v=null;else if(g.gw(u)){t=[];for(var n=g.R(u),O=n.next();!O.done;O=n.next()){var q=e(O.value);
q&&t.push(q)}v=t}else{var N=e(u);v=N?[N]:[]}Q=k&&W?new n0K(k,W,I,v,m):null}else Q=null}catch(Pt){}if(Q)if(Q.type==="branding"||Q.type==="promotion"){e=H;t=Q;var r=a8M(e),B=null;switch(t.type){case "branding":if(e.player.K().ox)break;e.player.U("web_player_overlay_positioned_layout")?(r.setAttribute("data-overlay-order","11"),e.player.lx(r,4,!0)):e.W.element.appendChild(r);B=new ew(r,S8(e),t);break;case "promotion":g.as(e.player,r,4),B=new Oyo(r,S8(e),t)}B&&B.b_();if(e=B)g.d(H,e),H.C[Q.id]=e}else if(Q.type===
"card"||Q.type==="drawer"){H.L||(H.L=zcW(H),g.d(H,H.L));if(Q.type==="card"){r=H.L;var l=(G=Q)&&G.data&&G.data.card_type;Q=G.data;if(l)switch(e=Q.tracking||{},e={r8:e.impression,click:e.click,close:e.close,A$:e.teaser_impression,LF:e.teaser_click},t=Q.tracking_params||{},B=null,l){case "collaborator":G={id:G.id,timestamp:Q.timestamp||0,type:Q.card_type,teaserText:Q.teaser_text,teaserDurationMs:Q.teaser_duration_ms,startMs:Q.start_ms,autoOpen:Q.auto_open||!1,sessionData:Q.session_data||{},sponsored:Q.sponsored||
!1,iV:e,HR:t.card?g.Bn(t.card):null,MM:t.teaser?g.Bn(t.teaser):null,YW:t.icon?g.Bn(t.icon):null,channelId:Q.channel_id,customMessage:Q.custom_message?Q.custom_message:null,profileImageUrl:Q.image_url,title:Q.title,metaInfo:Q.meta_info,url:RZ({pause_on_navigation:Q.pause_on_navigation,target:Q.target||"new",value:Q.url}),onClickCommand:null};ia(r,G);break;case "playlist":G={id:G.id,timestamp:Q.timestamp||0,type:Q.card_type,teaserText:Q.teaser_text,teaserDurationMs:Q.teaser_duration_ms,startMs:Q.start_ms,
autoOpen:Q.auto_open||!1,sessionData:Q.session_data||{},sponsored:Q.sponsored||!1,iV:e,HR:t.card?g.Bn(t.card):null,MM:t.teaser?g.Bn(t.teaser):null,YW:t.icon?g.Bn(t.icon):null,fV:Q.image_url,playlistVideoCount:Q.playlist_video_count,customMessage:Q.custom_message?Q.custom_message:null,title:Q.title,metaInfo:Q.meta_info,url:RZ({pause_on_navigation:Q.pause_on_navigation,target:Q.target||"new",value:Q.url}),onClickCommand:null};ia(r,G);break;case "productListing":Q.signin_url&&(B=RZ({target:"current",
value:Q.signin_url}));l=[];for(var S=Q.offers||[],z=0;z<S.length;z++)l.push(new i3o(g.zE(S[z].merchant),g.zE(S[z].price)));G={id:G.id,timestamp:Q.timestamp||0,type:Q.card_type,teaserText:Q.teaser_text,teaserDurationMs:Q.teaser_duration_ms,startMs:Q.start_ms,autoOpen:Q.auto_open||!1,sessionData:Q.session_data||{},sponsored:Q.sponsored||!1,iV:e,HR:t.card?g.Bn(t.card):null,MM:t.teaser?g.Bn(t.teaser):null,YW:t.icon?g.Bn(t.icon):null,imageUrl:Q.image_url,displayDomain:Q.display_domain?Q.display_domain:
null,showLinkIcon:!!Q.show_link_icon,Ss:Q.button_icon_url?Q.button_icon_url:null,title:Q.title,customMessage:Q.custom_message?Q.custom_message:null,url:RZ({pause_on_navigation:Q.pause_on_navigation,target:Q.target||"new",value:Q.url}),e47:B,cN$:Q.signin_title?Q.signin_title:void 0,Com:Q.signin_message?Q.signin_message:void 0,offers:l,onClickCommand:null};ia(r,G);break;case "simple":G={id:G.id,timestamp:Q.timestamp||0,type:Q.card_type,teaserText:Q.teaser_text,teaserDurationMs:Q.teaser_duration_ms,
startMs:Q.start_ms,autoOpen:Q.auto_open||!1,sessionData:Q.session_data||{},sponsored:Q.sponsored||!1,iV:e,HR:t.card?g.Bn(t.card):null,MM:t.teaser?g.Bn(t.teaser):null,YW:t.icon?g.Bn(t.icon):null,imageUrl:Q.image_url,displayDomain:Q.display_domain?Q.display_domain:null,showLinkIcon:!!Q.show_link_icon,Ss:Q.button_icon_url?Q.button_icon_url:null,title:Q.title,customMessage:Q.custom_message?Q.custom_message:null,url:RZ({pause_on_navigation:Q.pause_on_navigation,target:Q.target||"new",value:Q.url}),onClickCommand:null};
ia(r,G);break;case "video":G={id:G.id,timestamp:Q.timestamp||0,type:Q.card_type,teaserText:Q.teaser_text,teaserDurationMs:Q.teaser_duration_ms,startMs:Q.start_ms,autoOpen:Q.auto_open||!1,sessionData:Q.session_data||{},sponsored:Q.sponsored||!1,iV:e,HR:t.card?g.Bn(t.card):null,MM:t.teaser?g.Bn(t.teaser):null,YW:t.icon?g.Bn(t.icon):null,fV:Q.image_url,videoDuration:Q.video_duration||null,customMessage:Q.custom_message?Q.custom_message:null,title:Q.title,metaInfo:Q.meta_info,isLiveNow:!!Q.is_live_now,
url:RZ({pause_on_navigation:Q.pause_on_navigation,target:Q.target||"new",value:Q.url}),onClickCommand:null},ia(r,G)}}else I83(H.L,Q);G=!0}}G&&(Fo(H.player),H.Ir())},IiZ=function(H,E,G){sK(H,E.clickUrls,G);
(H=g.ri())&&E.HP$&&g.aF(H,E.visualElement)},n0K=function(H,E,G,P,Q){this.id=H;
this.type=E;this.style=G;this.data=Q;this.action=P||[]},Oyo=function(H,E,G){wX.call(this,H,E,G);
var P=this;this.N=this.isCollapsed=this.L_=!1;this.C=5E3;this.W=this.G=this.L=this.D=null;this.B=this.createElement({J:"div",QN:["iv-promo-contents"]});this.T=new g.Wt(function(){P.L.setAttribute("aria-hidden","true");g.Jx(P.G,!1);g.Jx(P.W,!0)},700,this);
g.d(this,this.T)},Ga=function(H,E){g.J.call(this);
var G=this;this.element=H;this.context=E;this.au=!1;this.Yp=new Map;this.BF=new Map;this.context.S.addEventListener(g.Ya("annotations_module"),function(P){(P=G.Yp.get(P))&&P.apply(G)});
this.context.S.addEventListener(g.XT("annotations_module"),function(P){(P=G.BF.get(P))&&P.apply(G)})},KXo=function(H){this.S=H},UmK=function(H,E){if(!g.T2(H.S.getRootNode(),"ytp-cards-teaser-shown")){if(H.L!==E){var G=g.ri(),P=H.L?H.L.S7.YW:H.YW;
G&&P&&g.nm(G,[P]);H.L=E;T3(H)}(G=H.isInitialized&&H.E2().style.display=="none")||(G=H.context.S.getPlayerState(),P=G===0&&H.context.S.getCurrentTime()===0,G=!(G===1||G===3||P));if(!G&&E.S7.teaserDurationMs){var Q;G={teaserText:E.S7.teaserText,durationMs:E.S7.teaserDurationMs,onClickCommand:E.S7.onClickCommand,Bv:(Q=E.S7.Bv)!=null?Q:null};H.S.t3(!0,G)}H.hm.isActive()||((!H.G||!H.E7.isActive()&&H.T$)&&YNo(H,E),H.hm.start(910+E.S7.teaserDurationMs))}},jTd=function(H){return H==="annotation-editor"||
H==="live-dashboard"},wVo=function(H,E,G){this.type=H;
this.trigger=E;this.url=G},jN3=function(H,E){var G={startMs:Math.floor(Number(H.startMs)),
impressionUrls:fG(H.impressionUrls||[],pG),elements:fG(H.elements||[],function(P,Q){return E0R(E,P,Q)})};
H.trackingParams&&(G.visualElement=g.Bn(H.trackingParams));return G},cOC=function(H,E,G){g.T2(E.element,"ytp-ce-element-hover")||(G.type==="VIDEO"||G.type==="PLAYLIST"?g.aG(E.element,"ytp-ce-element-hover"):H.player.K().W?(new g.Wt(function(){g.aG(E.element,"ytp-ce-element-hover")},200)).start():g.aG(E.element,"ytp-ce-element-hover"),sK(H,G.XF_),Xo(H,G.id,!0))},hV=function(H,E,G,P){var Q=1,e=void 0,w=-1;
if(G){var t=!1;e=function(){Q--;Q||t||(clearTimeout(w),t=!0,G())};
w=setTimeout(function(){t=!0;G()},1E3)}E=g.R(E||[]);
for(var k=E.next();!k.done;k=E.next())k=k.value,Q++,g.iN(k,e);P&&(Q++,P!==0&&H.S.sendVideoStatsEngageEvent(P,e))},$FM=function(H,E){var G=!1;
H.L||(H.L=zcW(H),g.d(H,H.L));for(var P=g.R(E.cards||[]),Q=P.next();!Q.done;Q=P.next())Q=Q.value,Q.cardRenderer&&(w93(H.L,Q.cardRenderer),G=!0);if(G){var e;(e=H.player.getVideoData())!=null&&g.dS(e)||(G=H.L,P=E.headerText?g.b_(E.headerText):"",g.rA(G.FI,P),G.T&&(G.S.U("player_tooltip_data_title_killswitch")?G.T.setAttribute("title",P):G.T.setAttribute("data-tooltip-title",P)),G.context.videoData.eventId&&(G.eventId=G.context.videoData.eventId),G.PF=E.trackingParams?g.Bn(E.trackingParams):null,G.N=
E.closeButton.infoCardIconRenderer.trackingParams?g.Bn(E.closeButton.infoCardIconRenderer.trackingParams):null,G.YW=E.icon.infoCardIconRenderer.trackingParams?g.Bn(E.icon.infoCardIconRenderer.trackingParams):null,H.Ir());Fo(H.player)}},ew=function(H,E,G){wX.call(this,H,E,G);
this.L=null;this.G=!1;this.W=null},byo=function(H){g.UM.call(this,H);
var E=this;this.p_=this.N=!1;this.loadNumber=0;this.C={};this.logger=new KXo(this.player);this.D=new g.Z0(this);this.T=this.B=null;this.events=new g.Z0(this);this.r6=this.L_=this.L=null;this.WF=[];g.d(this,this.D);this.D.Z(this.player,"onVideoAreaChange",function(){E.publish("onVideoAreaChange")});
this.D.Z(this.player,"onHideControls",function(){E.publish("onHideControls")});
this.D.Z(this.player,"onShowControls",function(){E.publish("onShowControls")});
this.D.Z(this.player,"resize",function(e){E.publish("resize",e)});
this.D.Z(this.player,"presentingplayerstatechange",function(e){E.publish("presentingplayerstatechange",e)});
this.subscribe("presentingplayerstatechange",this.VX,this);this.subscribe("resize",this.Ir,this);this.player.K().T$.subscribe("vast_info_card_add",this.N2,this);g.d(this,this.events);this.Jm=this.createElement({J:"div",Y:"video-custom-annotations"});this.W=new g.D({J:"div",QN:["ytp-player-content","ytp-iv-player-content"]});g.d(this,this.W);g.as(this.player,this.W.element,4);this.W.hide();this.G=new g.D({J:"div",QN:["ytp-iv-video-content"]});g.d(this,this.G);H=this.createElement({J:"div",Y:"video-annotations"});
H.appendChild(this.Jm);this.G.element.appendChild(H);this.lB()&&this.load();var G=this.createElement({J:"style"});(g.lw("HEAD")[0]||document.body).appendChild(G);this.addOnDisposeCallback(function(){g.LQ(G)});
if(H=G.sheet){for(var P=g.R(NWR),Q=P.next();!Q.done;Q=P.next())H.insertRule(Q.value,0);P=g.R(yOo);for(Q=P.next();!Q.done;Q=P.next())H.insertRule(Q.value,0)}},X9H=function(H,E){var G;
return E.onClickCommand&&((G=g.X(E.onClickCommand,g.ZwZ))==null?void 0:G.targetId)==="engagement-panel-error-corrections"?(H.WF=E,!0):!1},aiW=function(H){H.D&&(g.lU.clearTimeout(H.D),H.D=null)},Jj=function(H,E,G,P,Q){z3.call(this,E,G,P,Q);
this.element=H},MPC=function(H,E,G,P){this.value=H;
this.target=E;this.showLinkIcon=G;this.L=P},lio=function(H){H.p_.push(g.tf("iv-teaser-shown",H.al,H));
H.p_.push(g.tf("iv-teaser-hidden",H.jqF,H));H.p_.push(g.tf("iv-teaser-clicked",H.K2,H));H.G6=!0},iyo=function(H,E,G){E&&(G?hV(H,E.map(function(P){return g.iO(P,G)})):hV(H,E))},uLM=function(H,E,G){function P(k){H.B+=k;
H.B>0?(g.aG(E.element,"ytp-ce-force-expand"),Xo(H,G.id,!0)):(g.Tn(E.element,"ytp-ce-force-expand"),g.Tn(E.element,"ytp-ce-element-hover"),Xo(H,G.id,!1))}
function Q(k){k&&(E.listen("blur",function(){k.style.display!="none"&&H.p_&&k.focus()}),E.Z(k,"focus",w),E.Z(k,"blur",e))}
function e(){P(-1)}
function w(){P(1)}
E.listen("mouseenter",function(){cOC(H,E,G)});
E.listen("mouseleave",function(){AsH(H,E,G)});
H.player.K().W||E.listen("click",function(){g.aG(E.element,"ytp-ce-element-hover")});
E.listen("click",function(k){mmH(H,G,k)});
E.listen("keypress",function(k){mmH(H,G,k)});
E.listen("focus",function(){cOC(H,E,G)});
E.listen("blur",function(){AsH(H,E,G)});
E.listen("touchstart",function(){cOC(H,E,G)});
var t=g.mO("ytp-ce-expanding-overlay-hider",E.element);t&&E.Z(t,"touchstart",function(k){k.stopPropagation();g.Tn(E.element,"ytp-ce-element-hover");g.Tn(E.element,"ytp-ce-force-expand")});
E.listen("keydown",function(k){H.p_=k.keyCode===9&&!k.shiftKey});
Q(g.mO("ytp-sb-subscribe",E.element));Q(g.mO("ytp-sb-unsubscribe",E.element));E.listen("focus",w);E.listen("blur",e)},qWH=function(H){var E=H.annotation.data;
"start_ms"in E&&"end_ms"in E&&H.addCueRange(Number(E.start_ms),Number(E.end_ms),H.annotation.id,function(){H.show()},function(){H.hide()})},Rad=function(H){H.T.stop();
H.isCollapsed&&(g.YQ(H.E2(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),H.isCollapsed=!1,H.L&&H.L.removeAttribute("aria-hidden"),g.Jx(H.W,!1),g.Jx(H.G,!0))},S8=function(H){if(!H.L_){var E=new JOC(H);
g.d(H,E);var G=new g.S1(H);g.d(H,G);H.L_=new sTZ(E,G,H.player.K(),H.player.getVideoData(),H.logger,H.player,H.yG)}return H.L_},rOR=function(H,E){return g.VS(H.action,E)},wX=function(H,E,G){Ga.call(this,H,E);
this.annotation=G;this.isActive=!1},BW3=function(H,E,G){G.stopPropagation();
Rad(H);K3H(H,E);H.L.focus()},QI=function(H){return H.player.K().playerStyle==="creator-endscreen-editor"},ec3=function(H){var E;
return((E=g.X(H,g.nR))==null?0:E.url)?g.X(H,g.nR).url:(H=g.X(H,g.Xt))&&H.videoId?(E="/watch?v="+H.videoId,H.playlistId&&(E+="&list="+H.playlistId),H.index&&(E+="&index="+H.index),H.startTimeSeconds&&(E+="&t="+H.startTimeSeconds),E):null},CMK=function(H,E){switch(E.type){case "simple":H=H.Jm;
var G=E.displayDomain?{J:"div",Y:"iv-card-image-text",iJ:E.displayDomain}:void 0;var P=AOW(E);G={J:"div",QN:["iv-card"],V:[{J:"a",Y:"iv-click-target",j:{href:E.url?$P(E.url)||"":""},V:[tV(E.imageUrl,G),{J:"div",Y:"iv-card-content",V:[Yk("h2",void 0,E.title),P]}]}]};G=new g.D(G);Pr(H,g.RQ("iv-click-target",G.element),E,E.url);E=G;break;case "collaborator":H=H.Jm;G={J:"div",QN:["iv-card","iv-card-channel"],V:[{J:"a",QN:["iv-click-target"],j:{href:$P(E.url)||"","data-ytid":E.channelId},V:[tV(E.profileImageUrl),
{J:"div",Y:"iv-card-content",V:[QTR(E),{J:"h2",Y:"iv-card-primary-link",iJ:E.title},p9K(E)]}]}]};G=new g.D(G);Pr(H,g.RQ("iv-click-target",G.element),E,E.url);E=G;break;case "playlist":H=H.Jm;G={J:"div",QN:["iv-card","iv-card-playlist"],V:[{J:"a",Y:"iv-click-target",j:{href:$P(E.url)||""},V:[tV(E.fV,{J:"div",Y:"iv-card-image-overlay",V:[{J:"span",Y:"iv-card-playlist-video-count",iJ:E.playlistVideoCount}]}),{J:"div",Y:"iv-card-content",V:[QTR(E),Yk("h2","iv-card-primary-link",E.title),p9K(E)]}]}]};
G=new g.D(G);Pr(H,g.RQ("iv-click-target",G.element),E,E.url);E=G;break;case "productListing":H=H.Jm;var Q=E.offers.length!=0;G=["iv-card"];P="";var e=AOW(E);Q&&(G.push("iv-card-product-listing"),P="iv-card-primary-link",e=E.offers[0],Q=[],e.price&&Q.push({J:"div",Y:"iv-card-offer-price",iJ:e.price}),e.merchant&&Q.push({J:"div",Y:"iv-card-offer-merchant",iJ:e.merchant}),e={J:"div",V:Q});Q=E.url?$P(E.url)||"":"";G={J:"div",QN:G,j:{tabindex:"0"},V:[{J:"a",QN:["iv-card-image","iv-click-target"],j:{style:"background-image: url("+
E.imageUrl+");",href:Q,"aria-hidden":"true",tabindex:"-1"}},{J:"div",Y:"iv-card-content",V:[E.sponsored?{J:"div",Y:"iv-card-sponsored",V:["Sponsored",{J:"div",Y:"iv-ad-info-container",V:[{J:"div",Y:"iv-ad-info",iJ:"{{adInfo}}"},{J:"div",Y:"iv-ad-info-icon-container",V:[{J:"div",Y:"iv-ad-info-icon"},{J:"div",Y:"iv-ad-info-callout"}]}]}]}:"",{J:"a",Y:"iv-click-target",j:{href:Q},V:[Yk("h2",P,E.title),e]}]}]};G=new g.D(G);P=g.pu("span");g.rA(P,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
G.setContent(P,"adInfo");Pr(H,g.RQ("iv-click-target",G.element),E,E.url);E=G;break;case "video":H=H.Jm;P=E.videoDuration?{J:"span",Y:"iv-card-video-duration",iJ:E.videoDuration}:void 0;e=E.isLiveNow?{J:"span",QN:["yt-badge","yt-badge-live"],iJ:"LIVE NOW"}:null;Q={J:"div",QN:["iv-card","iv-card-video"],V:[{J:"a",Y:"iv-click-target",j:{href:((G=E.url)==null?void 0:$P(G))||""},V:[tV(E.fV,P),{J:"div",Y:"iv-card-content",V:[QTR(E),Yk("h2","iv-card-primary-link",E.title),p9K(E),e]}]}]};G=new g.D(Q);Pr(H,
g.RQ("iv-click-target",G.element),E,E.url);E=G;break;default:return null}return E},F3Z=function(H,E){H.method="POST";
H.postParams=H.postParams||{};E.e0&&(H.postParams.ic_coll=E.e0);E.Pz&&(H.postParams.ic_xml=E.Pz);E.a8&&(H.postParams.ic_track=E.a8)},v0$=function(H){var E;
(E=H)&&!(E=H.length>1?H.charAt(0)==="/"&&H.charAt(1)!=="/":H==="/")&&(E=H.replace(/^(https?:)?\/\//,"").split("/",1),E=!E||E.length<1||!E[0]?[]:E[0].toLowerCase().split(".").reverse(),E=E[0]==="com"&&E[1]==="youtube"||E[0]==="be"&&E[1]==="youtu");return E?H.indexOf("/redirect?")===-1:!1},VG=function(H,E,G){if(!H.G){H.MZ.show();
H.eR=new g.Wt(function(){g.aG(H.context.S.getRootNode(),g.JN.IV_DRAWER_OPEN)},0);
H.eR.start();H.z$.Z(H.W,"mousewheel",function(w){H.E7.start();w.preventDefault();w=w||window.event;var t=0;w.type=="MozMousePixelScroll"?t=0==(w.axis==w.HORIZONTAL_AXIS)?w.detail:0:window.opera?t=w.detail:t=w.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?w.wheelDeltaY/-30:w.wheelDeltaY/-1.2:w.wheelDelta/-1.6:w.wheelDeltaY/-3;if(w=t)H.W.scrollTop+=w});
H.G=!0;var P=g.ri();P&&H.PF&&H.N&&g.LJ(P,[H.PF,H.N]);E={TRIGGER_TYPE:E};for(var Q=g.R(H.cards),e=Q.next();!e.done;e=Q.next())e=e.value,e.zm||(e.zm=!0,iyo(H.context.logger,e.S7.iV.r8,E)),P&&g.LJ(P,[e.S7.HR]);Fo(H.S);G&&(H.C=new g.Wt(function(){H.O7=H.T;H.s7.focus()},330),H.C.start())}},a8M=function(H){H=H.createElement({J:"div",
QN:["annotation","annotation-type-custom"]});g.Jx(H,!1);return H},U6=function(H){if(H.qT)var E=H.qT.thumbnails;
return ysK(E?E[E.length-1].url:null)},O3W=function(H){H.isCollapsed||H.N||H.D||(g.aG(H.E2(),"iv-promo-collapsed"),H.isCollapsed=!0,H.T.start())},Xo=function(H,E,G){H.G&&(G?H.T.show():H.T.hide());
for(var P=g.R(Object.keys(H.W)),Q=P.next();!Q.done;Q=P.next())Q=Q.value,Q!==E&&g.Bt(H.W[Q].element,"ytp-ce-element-shadow-show",G)},GqW=function(H){if(H.L)return H.L.S7.type==="productListing";
if(H.S.U("enable_wn_infocards")){var E;return!((E=H.cards)==null||!E.length)&&g.fF(H.cards,function(G){return G.S7.type==="productListing"})}return g.fF(H.cards,function(G){return G.S7.type==="productListing"})},$P=function(H){return H.value?H.value:null},EK=function(H){H.G&&(H.MZ.hide(),g.hH(H.z$),g.Tn(H.context.S.getRootNode(),g.JN.IV_DRAWER_OPEN),H.G=!1,Fo(H.S),H.C&&H.C.stop(),H.C=new g.Wt(function(){H.O7&&(H.O7.focus(),H.O7=null)},330),H.C.start())},JOC=function(H){g.J.call(this);
this.W=H||window;this.L=[]},YWD=function(H){var E=H.annotation.data;
if(H.annotation.style==="cta")var G=6;else if(H.annotation.style==="video"||H.annotation.style==="playlist")G=7;H.C=E.collapsedelay_ms||H.C;var P=["iv-promo","iv-promo-inactive"];H.E2().setAttribute("aria-hidden","true");H.E2().setAttribute("aria-label","Promotion");H.E2().tabIndex=0;var Q=H.annotation.TU(),e=E.image_url;if(e){var w=H.createElement({J:"div",QN:["iv-promo-img","iv-click-target"]});e=H.createElement({J:"img",j:{src:e,"aria-hidden":"true"}});w.appendChild(e);E.video_duration&&!E.is_live?
(e=H.createElement({J:"span",Y:"iv-promo-video-duration",iJ:E.video_duration}),w.appendChild(e)):E.playlist_length&&(e=H.createElement({J:"span",Y:"iv-promo-playlist-length",iJ:E.playlist_length.toString()}),w.appendChild(e));Q&&Hr(H,w,Q,H.annotation.id,E.session_data,void 0,G)}Q?(e=H.createElement({J:"a",Y:"iv-promo-txt"}),g.HQ(e,$P(Q)),H.L=e):H.L=H.createElement({J:"div",Y:"iv-promo-txt"});switch(H.annotation.style){case "cta":case "website":var t=H.createElement({J:"p",V:[{J:"strong",iJ:E.text_line_1}]});
var k=H.createElement({J:"p",V:[{J:"span",Y:"iv-promo-link",iJ:E.text_line_2}]});if(e=E.text_line_3){P.push("iv-promo-website-card-cta-redesign");var W=H.createElement({J:"button",QN:["iv-promo-round-expand-icon","ytp-button"]});e=H.createElement({J:"button",QN:["iv-button","iv-promo-button"],V:[{J:"span",Y:"iv-button-content",iJ:e}]});var I=H.createElement({J:"div",Y:"iv-promo-button-container"});I.appendChild(e);Q&&Hr(H,H.E2(),Q,H.annotation.id,E.session_data,void 0,G)}g.aG(H.L,"iv-click-target");
Q&&Hr(H,H.L,Q,H.annotation.id,E.session_data,void 0,G);break;case "playlist":case "video":t=H.createElement({J:"p",V:[{J:"span",iJ:E.text_line_1}]}),k=H.createElement({J:"p",V:[{J:"strong",iJ:E.text_line_2}]}),E.is_live&&(t=k,k=H.createElement({J:"span",QN:["yt-badge","iv-promo-badge-live"],iJ:"LIVE NOW"})),g.aG(H.L,"iv-click-target"),Q&&Hr(H,H.L,Q,H.annotation.id,E.session_data,void 0,G),P.push("iv-promo-video")}t&&H.L.appendChild(t);k&&H.L.appendChild(k);H.B.appendChild(H.L);I&&H.B.appendChild(I);
G=H.createElement({J:"div",Y:"iv-promo-actions"});H.W=H.createElement({J:"button",QN:["iv-promo-expand","ytp-button"]});H.W.title="Expand";H.context.L.listen(H.W,"click",function(A){BW3(H,5E3,A)});
G.appendChild(H.W);g.Jx(H.W,!1);H.context.L.listen(H.E2(),"mouseover",H.opR,H);H.context.L.listen(H.E2(),"mouseout",H.zww,H);H.context.L.listen(H.E2(),"touchend",function(A){BW3(H,5E3,A)});
H.G=H.createElement({J:"button",QN:["iv-promo-close","ytp-button"]});H.G.title="Close";H.context.L.listen(H.G,"click",H.annotation.style==="cta"&&E.text_line_3?H.tR$:H.T5N,H);G.appendChild(H.G);g.rl(H.E2(),P);w&&(g.jx(H.E2(),w),W&&w.appendChild(W));g.jx(H.E2(),H.B);g.jx(H.E2(),G)},XV$=function(H,E){function G(w){var t=H.loadNumber;
H.T=null;H.loaded&&H.loadNumber===t&&H.player.getVideoData().videoId===P&&(w=g.dw(w)&&w.responseXML?w.responseXML:null)&&(SNK(H,w),g.aG(H.player.getRootNode(),"iv-module-loaded"))}
var P=E.videoId;g.Sh()&&(G=rsC(H,G));var Q={format:"XML",onFinish:G,onError:function(){H.T=null},
urlParams:{}};E.isPharma&&(Q.urlParams.pharma="1");Q.method="POST";Q.withCredentials=!0;var e=H.player.K().T$.get(P);e&&(Math.random()<g.hE(H.player.K().experiments,"annotation_module_vast_cards_load_logging_fraction")&&g.p5(new g.LN("Unexpected call to loadVastInfoCards; VastInfoCard exists.")),F3Z(Q,e));e=e&&(e.Pz||e.e0);if(!E.iL||e)E.BA?(Math.random()<g.hE(H.player.K().experiments,"annotation_module_vast_cards_load_logging_fraction")&&g.p5(new g.LN("Unexpected call to loadVastInfoCards; Attempting to load annotations via invideo URL.")),
onu(H,E.BA,Q)):(H.B=function(){if(!H.N)H.onVideoDataChange(Q);var w=H.player.getVideoData();(w==null?0:g.dS(w))&&!H.p_&&tBu(H,w)},H.player.addEventListener("videodatachange",H.B))},tV=function(H,E){H="background-image: url("+H+");";
var G=[];E&&G.push(E);return{J:"div",Y:"iv-card-image",j:{style:H},V:G}},fG=function(H,E){return g.W2(g.wH(H,E),function(G){return!!G})};
g.NK.prototype.t3=g.Mt(39,function(H,E){var G=g.b0(this.lm());G&&G.t3(H,E)});
var xk={},rh=null;g.xE(z3,g.uf);g.M=z3.prototype;g.M.getDuration=function(){return this.duration};
g.M.play=function(H){if(H||this.L==0)this.progress=0,this.coords=this.W;else if(this.isPlaying())return!1;LG(this);this.startTime=H=g.Gl();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.HQ();this.Xf("play");this.isPaused()&&this.Xf("resume");this.L=1;var E=g.bY(this);E in xk||(xk[E]=this);kvW();DmD(this,H);return!0};
g.M.stop=function(H){LG(this);this.L=0;H&&(this.progress=1);dmR(this,this.progress);this.onStop();this.K1()};
g.M.pause=function(){this.isPlaying()&&(LG(this),this.L=-1,this.Xf("pause"))};
g.M.G$=function(){this.L==0||this.stop(!1);this.Xf("destroy");z3.j7.G$.call(this)};
g.M.destroy=function(){this.dispose()};
g.M.h4=function(){this.Xf("animate")};
g.M.Xf=function(H){this.dispatchEvent(new HyH(H,this))};
g.xE(HyH,g.DK);g.xE(Jj,z3);Jj.prototype.G=function(){};
Jj.prototype.h4=function(){this.G();Jj.j7.h4.call(this)};
Jj.prototype.K1=function(){this.G();Jj.j7.K1.call(this)};
Jj.prototype.HQ=function(){this.G();Jj.j7.HQ.call(this)};
g.xE($m$,Jj);$m$.prototype.G=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.C(JOC,g.J);g.M=JOC.prototype;g.M.listen=function(H,E,G,P){G=(0,g.co)(G,P||this.W);H=g.Pm(H,E,G);this.L.push(H);return H};
g.M.So=function(H,E,G,P){G=(0,g.co)(G,P||this.W);H=hcZ(H,E,G);this.L.push(H);return H};
g.M.Sq=function(H){g.sz(H);g.Ih(this.L,H)};
g.M.removeAll=function(){g.sz(this.L);this.L.length=0};
g.M.G$=function(){this.removeAll();g.J.prototype.G$.call(this)};g.C(PkD,g.UM);g.M=PkD.prototype;g.M.load=function(){g.UM.prototype.load.call(this);if(!QI(this)){var H=g.YEM(this.player.getVideoData());H?(H=jN3(H,csu(this)),la(this,H,!1)):Ndd(this)}};
g.M.unload=function(){la(this,null);this.D&&(this.D.abort(),this.D=null);g.UM.prototype.unload.call(this)};
g.M.Mf=function(H,E){return QI(this)?H==="loadCustomEndscreenRenderer"?(H=jN3(E,"new"),la(this,H),!0):null:null};
g.M.getOptions=function(){return QI(this)?["loadCustomEndscreenRenderer"]:[]};
g.M.h7=function(){if(this.endscreen&&this.endscreen.elements){var H=this.player.getVideoContentRect();if(H&&H.width!==0&&H.height!==0){var E=this.player.getPlayerSize();if(E&&E.width!==0&&E.height!==0){var G=H.width/H.height;var P=0;for(var Q=-1,e=0;e<Zyd.length;e++){var w=Math.abs(E.width-Zyd[e]);if(Q===-1||P>=w)Q=e,P=w}P=CkK[Q];this.G&&g.AE(this.G.element,"outline-width",Math.max(E.width,E.height)+"px");for(E=0;E<this.endscreen.elements.length;++E)if(e=this.endscreen.elements[E].id,Q=this.W[e],
w=this.C[e],Q&&w){var t=w.width*G/w.aspectRatio,k=Math.round(w.width*H.width);e=Math.round(t*H.height);var W=H.left+Math.round(w.left*H.width),I=H.top+Math.round(w.top*H.height);g.sR(Q.element,k,e);g.lN(Q.element,W,I);g.YQ(Q.element,g0R);k>256||e>256?g.aG(Q.element,"ytp-ce-large-round"):k>96||e>96?g.aG(Q.element,"ytp-ce-medium-round"):g.aG(Q.element,"ytp-ce-small-round");g.YQ(Q.element,LXu);k=w.left+w.width/2;w=w.top+t/2;g.aG(Q.element,k<=.5&&w<=.5?"ytp-ce-top-left-quad":k>.5&&w<=.5?"ytp-ce-top-right-quad":
k<=.5&&w>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.YQ(Q.element,CkK);g.aG(Q.element,P);(Q=g.V_(document,"div","ytp-ce-expanding-overlay-body",Q.element)[0])&&g.AE(Q,"height",e+"px")}}}}};
g.M.onCueRangeEnter=function(H){if(this.endscreen)if(H.getId()==="ytp-ce-in-endscreen")sK(this,this.endscreen.impressionUrls),(H=g.ri())&&this.endscreen.visualElement&&g.u8(H,this.endscreen.visualElement),this.L&&(g.aG(this.L,"ytp-ce-element-show"),this.L.removeAttribute("aria-hidden"),this.player.pR()?g.aG(this.L,"ytp-ce-hide-button-lower"):g.Tn(this.L,"ytp-ce-hide-button-lower"));else{H=H.getId().substring(15);var E=this.W[H],G=this.C[H];g.aG(E.element,"ytp-ce-element-show");E.element.removeAttribute("aria-hidden");
E=this.player.getRootNode();g.aG(E,"ytp-ce-shown");sK(this,G.impressionUrls);(E=g.ri())&&g.u8(E,G.visualElement);this.player.K().N&&this.player.n_("endscreenelementshown",H)}};
g.M.onCueRangeExit=function(H){if(H.getId()==="ytp-ce-in-endscreen")this.L&&(g.Tn(this.L,"ytp-ce-element-show"),this.L.setAttribute("aria-hidden","true"));else{H=H.getId().substring(15);var E=this.W[H];g.Tn(E.element,"ytp-ce-element-show");E.element.setAttribute("aria-hidden","true");E=this.player.getRootNode();g.Tn(E,"ytp-ce-shown");this.player.K().N&&this.player.n_("endscreenelementhidden",H)}};
g.M.T6a=function(H){var E=this;H.target===window&&(new g.Wt(function(){for(var G=g.R(Object.values(E.W)),P=G.next();!P.done;P=G.next())g.YQ(P.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.M.BT=function(H){for(var E=g.R(Object.values(this.W)),G=E.next();!G.done;G=E.next())G=G.value,H?G.element.setAttribute("hidden",""):G.element.removeAttribute("hidden")};
g.M.yjN=function(H){this.L&&this.player.getRootNode().removeChild(this.L);H&&(g.aG(H,"ytp-ce-hide-button-container"),this.L=H,g.as(this.player,this.L,4))};
var Zyd=[346,426,470,506,570,640,853,1280,1920],CkK="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),LXu=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],g0R=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var vnW={iXx:"current",y2$:"new"};var o0J={CLOSE:"close",abx:"openUrl",SUBSCRIBE:"subscribe"},eaH={nM7:"click",CLOSE:"close",DBZ:"hidden",q0$:"rollOut",wRw:"rollOver",lLo:"shown"};n0K.prototype.TU=function(){var H=rOR(this,function(E){return E.type==="openUrl"&&E.url!=null});
return H?H.url:null};
var DFK={a1R:"anchored",sI:"branding",CHANNEL:"channel",WQa:"cta",ufw:"highlightText",qFZ:"label",PLAYLIST:"playlist",POPUP:"popup",tbF:"speech",SUBSCRIBE:"subscribe",YVx:"title",VIDEO:"video",mE7:"website"},dF3={sI:"branding",cvo:"card",Qmw:"drawer",HL7:"highlight",EQw:"marker",mO_:"promotion",TEXT:"text",k9m:"widget"};var NWR=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
yOo=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];g.C(Ga,g.J);g.M=Ga.prototype;g.M.addCueRange=function(H,E,G,P,Q){H=new g.cP(H,E,{id:G,namespace:"annotations_module"});P&&this.Yp.set(H,P);Q&&this.BF.set(H,Q);this.context.S.MV([H],1)};
g.M.b_=function(){this.context.W.subscribe("resize",this.tM,this)};
g.M.E2=function(){return this.element};
g.M.x8=function(H,E,G,P,Q,e){if(this.au)return!1;e&&(e.stopPropagation(),e.preventDefault());this.navigate(H,G,P,Q);return!1};
g.M.show=function(){};
g.M.hide=function(){};
g.M.destroy=function(){g.LQ(this.E2())};
g.M.tM=function(){};
g.M.navigate=function(H,E,G,P){var Q=this,e=$P(H);if(e){var w=MBC(e,H.target),t=function(){H.L&&Q.context.S.pauseVideo();var k=Q.context.videoData.Xg||!1,W=g.oz(e||"");k&&W&&(W.v||W.list)?Q.context.S.OF(W.v,E,W.list,!1):g.YK(e||"",w==="current"?"_top":void 0,E)};
w==="new"&&(t(),t=null);hV(this.context.logger,G,t,P);v0$(e)||(G=g.ri(),P=E.itct,G&&P&&g.aF(G,g.Bn(P)))}};
g.M.G$=function(){this.Yp.clear();this.BF.clear();g.J.prototype.G$.call(this)};
g.M.createElement=function(H){H=new g.D(H);g.d(this,H);return H.element};g.C(xmM,Ga);g.M=xmM.prototype;g.M.QW=function(){this.WF&&ia(this,this.WF)};
g.M.isAvailable=function(){var H;if(H=!!this.cards.length)(H=this.S.getRootNode())?(H=g.or(H),H=173<H.width&&173<H.height):H=!1;return H};
g.M.tM=function(){var H=this.isAvailable();g.Jx(this.E2(),H);g.Bt(this.context.S.getRootNode(),g.JN.IV_DRAWER_ENABLED,H);Fo(this.S)};
g.M.destroy=function(){this.S.t3(!1);try{this.S.getRootNode().removeChild(this.D)}catch(H){}g.$O(this.p_);g.hH(this.z$);this.eR&&this.eR.dispose();this.C&&this.C.dispose();Ga.prototype.destroy.call(this)};
g.M.Fi=function(){var H=this;this.context.L.listen(g.mO("iv-drawer-close-button",this.D),"click",this.QR,this);this.context.L.listen(this.W,"touchend",function(){H.E7.start()});
this.context.L.listen(this.W,"scroll",this.kN,this);this.context.W.subscribe("onHideControls",function(){H.T$=!0});
this.context.W.subscribe("onShowControls",function(){H.T$=!1});
this.context.W.subscribe("onVideoAreaChange",function(){H.T$=g.T2(H.S.getRootNode(),"ytp-autohide")});
this.p_.push(g.tf("iv-button-shown",this.vVp,this));this.p_.push(g.tf("iv-button-hidden",this.fup,this));lio(this)};
g.M.findLastIndex=function(H){if(this.cards.length===0)return 0;var E=g.D7(this.cards,function(G){return H.S7.startMs>G.S7.startMs||H.S7.startMs===G.S7.startMs&&H.S7.timestamp>=G.S7.timestamp?!0:!1});
return E===-1?0:E+1};
g.M.QR=function(){if(this.G){hV(this.context.logger,oU(this).iV.close);var H=g.ri();H&&this.N&&g.aF(H,this.N);EK(this)}};
g.M.kN=function(){g.Bt(this.D,"iv-drawer-scrolled",this.W.scrollTop>0)};
g.M.vVp=function(){var H=g.ri(),E=oU(this);E=E?E.YW:this.YW;H&&E&&g.LJ(H,[E])};
g.M.fup=function(){var H=g.ri(),E=oU(this);E=E?E.YW:this.YW;H&&E&&g.nm(H,[E])};
g.M.al=function(){var H=oU(this);hV(this.context.logger,H.iV.A$);var E=g.ri();if(E&&H)if(this.S.U("web_infocards_teaser_show_logging_fix")){var G=[];H.MM&&G.push(H.MM);H.YW&&G.push(H.YW);G.length>0&&g.LJ(E,G)}else g.LJ(E,[H.MM,H.YW])};
g.M.jqF=function(){var H=g.ri(),E=oU(this);H&&E&&g.nm(H,[E.MM])};
g.M.K2=function(H){var E=oU(this),G=g.ri();this.L?H?(H=this.context.logger,hV(H,E.iV.LF),H.S.sendVideoStatsEngageEvent(4,void 0),G&&E.MM&&g.aF(G,E.MM)):(H=this.context.logger,hV(H,E.iV.LF),H.S.sendVideoStatsEngageEvent(4,void 0),G&&E.YW&&g.aF(G,E.YW)):(H=this.context.logger,hV(H,E.iV.LF),H.S.sendVideoStatsEngageEvent(4,void 0),G&&this.YW&&g.aF(G,this.YW))};g.C(wX,Ga);wX.prototype.b_=function(){Ga.prototype.b_.call(this);qWH(this)};
wX.prototype.show=function(){Ga.prototype.show.call(this);var H=g.ri(),E=this.annotation.data;H&&E&&(E=E.session_data)&&g.LJ(H,[g.Bn(E.itct)])};
wX.prototype.hide=function(){Ga.prototype.hide.call(this);var H=g.ri(),E=this.annotation.data;H&&E&&(E=E.session_data)&&g.nm(H,[g.Bn(E.itct)])};g.C(ew,wX);
ew.prototype.show=function(){if(!this.isActive){wX.prototype.show.call(this);if(!this.G){g.aG(this.E2(),"iv-branding");var H=this.annotation.data;this.L=this.createElement({J:"img",QN:["branding-img","iv-click-target"],j:{"aria-label":"Channel watermark",src:H.image_url,width:H.image_width,height:H.image_height}});g.Jx(this.L,!1);var E=this.createElement({J:"button",QN:["branding-img-container","ytp-button"]});E.appendChild(this.L);this.E2().appendChild(E);var G=this.annotation.TU();G&&Hr(this,E,
G,this.annotation.id,H.session_data);this.G=!0}g.Jx(this.E2(),!0);this.isActive=!0;if(this.L){try{VPH(this,this.L)}catch(P){}g.aG(this.context.S.getRootNode(),"ytp-branding-shown");this.context.S.getRootNode().style.setProperty("--branding-image-width",this.L.getAttribute("width")+"px")}}};
ew.prototype.hide=function(){this.isActive&&(wX.prototype.hide.call(this),g.Jx(this.E2(),!1),this.isActive=!1,g.Tn(this.context.S.getRootNode(),"ytp-branding-shown"))};
ew.prototype.destroy=function(){this.W&&(this.W.dispose(),this.W=null);g.Tn(this.context.S.getRootNode(),"ytp-branding-shown");wX.prototype.destroy.call(this)};g.C(Oyo,wX);g.M=Oyo.prototype;g.M.show=function(){this.isActive||(wX.prototype.show.call(this),this.L_||(YWD(this),this.L_=!0),g.Jx(this.E2(),!0),g.N0(function(){g.Tn(this.E2(),"iv-promo-inactive")},100,this),this.E2().removeAttribute("aria-hidden"),this.isActive=!0,aiW(this),Rad(this),K3H(this,this.C))};
g.M.hide=function(){this.isActive&&(g.aG(this.E2(),"iv-promo-inactive"),this.isActive=!1,this.E2().setAttribute("aria-hidden","true"))};
g.M.x8=function(H,E,G,P,Q,e){return this.isCollapsed?!1:wX.prototype.x8.call(this,H,E,G,P,Q,e)};
g.M.opR=function(H){this.N=!0;BW3(this,500,H)};
g.M.zww=function(){this.N=!1;O3W(this)};
g.M.T5N=function(H){H.stopPropagation();this.hide()};
g.M.tR$=function(H){H.stopPropagation();aiW(this);this.isCollapsed=!0;g.aG(this.E2(),"iv-promo-collapsed-no-delay");this.T.start()};
g.M.destroy=function(){this.T.dispose();wX.prototype.destroy.call(this)};g.C(byo,g.UM);g.M=byo.prototype;g.M.Mf=function(H,E){if(!jTd(this.player.K().playerStyle))return null;switch(H){case "loadCustomAnnotationsXml":return(H=g.T_(E))&&SNK(this,H),!0;case "removeCustomAnnotationById":return E&&this.L&&(L3K(this.L,E),Fo(this.player)),!0}return null};
g.M.getOptions=function(){return jTd(this.player.K().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.M.lB=function(){var H=this.player.K(),E=this.player.getVideoData(),G=H.annotationsLoadPolicy||E.annotationsLoadPolicy;return E.Xg||this.player.isMutedByEmbedsMutedAutoplay()?!1:G===1&&!E.NN||H.T$.get(E.videoId)||g.Yt(E)||g.Ho(E)?!0:!1};
g.M.Ir=function(){if(this.G){var H=this.player.NZ().getVideoContentRect(!0);g.sR(this.G.element,H.width,H.height);g.lN(this.G.element,H.left,H.top)}if(this.L){var E=this.player.qS();H=this.L;E=E.width;g.Bt(H.D,"iv-drawer-small",E<=426);g.Bt(H.D,"iv-drawer-big",E>=1280)}};
g.M.VX=function(H){RcJ(this,H.state);g.F(H.state,2)&&(this.pR()&&this.DG()&&this.player.getPresentingPlayerType()!==2&&this.Sv(!1),this.t3(!1))};
g.M.load=function(){g.UM.prototype.load.call(this);RcJ(this,this.player.getPlayerStateObject());this.loadNumber++;var H=this.player.getVideoData();XV$(this,H);g.as(this.player,this.G.element,4);this.Ir();var E=g.Yt(H);E&&$FM(this,E);if((E=g.Ho(H))&&E.featuredChannel){var G=E.featuredChannel;E=E.annotationId||"branding";var P=H.videoId||null,Q=H.eventId||null;if(!this.player.K().ox){var e=[];G.navigationEndpoint&&g.X(G.navigationEndpoint,g.kd)&&g.X(G.navigationEndpoint,g.kd).browseId&&e.push(new wVo("openUrl",
"click",new MPC("/channel/"+g.X(G.navigationEndpoint,g.kd).browseId,"new",!0,!0)));var w=G.watermark.thumbnails[0];P={channel_name:G.channelName,end_ms:G.endTimeMs,image_height:w.height,image_type:1,image_url:w.url,image_width:w.width,is_mobile:!1,session_data:{annotation_id:E,ei:Q,feature:"iv",itct:G.trackingParams,src_vid:P},start_ms:G.startTimeMs};if(G.subscribeButton&&g.X(G.subscribeButton,g.sa)){P.channel_id=g.X(G.subscribeButton,g.sa).channelId;var t;G=g.X(G.subscribeButton,g.sa);w=Q=null;G.subscribed?
(G.subscriberCountWithUnsubscribeText&&(Q=g.b_(G.subscriberCountWithUnsubscribeText)),G.subscriberCountText&&(w=g.b_(G.subscriberCountText))):(G.subscriberCountText&&(Q=g.b_(G.subscriberCountText)),G.subscriberCountWithSubscribeText&&(w=g.b_(G.subscriberCountWithSubscribeText)));var k,W=((k=g.X((t=G.signInEndpoint)==null?void 0:t.commandMetadata,g.Mk))==null?void 0:k.url)||"";t={subscribeText:g.b_(G.unsubscribedButtonText),subscribeCount:Q||"",unsubscribeText:g.b_(G.subscribedButtonText),unsubscribeCount:w||
"",enabled:G.enabled||!1,classic:!1,subscribed:G.subscribed||!1,feature:"iv",signInUrl:W};P.standalone_subscribe_button_data=t}t=new n0K(E,"branding","branding",e,P);k=a8M(this);this.player.U("web_player_overlay_positioned_layout")?(k.setAttribute("data-overlay-order","11"),this.player.lx(k,4,!0)):this.W.element.appendChild(k);t=new ew(k,S8(this),t);t.b_();g.d(t,t);this.C[E]=t}}this.r6=g.mO("ytp-cards-button",this.player.getRootNode());g.dS(H)&&tBu(this,H)};
g.M.onVideoDataChange=function(H){var E=this.player.getVideoData();E.BA&&onu(this,E.BA,H)};
g.M.unload=function(){this.player.dV("annotations_module");for(var H=g.R(Object.keys(this.C)),E=H.next();!E.done;E=H.next())this.C[E.value].destroy();this.L_=null;this.L&&(this.L.destroy(),this.L=null,Fo(this.player));this.N=!1;this.T&&(this.T.abort(),this.T=null);this.p_=!1;this.C={};this.W.hide();g.UM.prototype.unload.call(this);this.G.detach();this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null)};
g.M.N2=function(H){H===this.player.getVideoData().videoId&&(this.loaded?fiK(this):this.load())};
g.M.pR=function(){var H;return((H=this.L)==null?void 0:H.isAvailable())||this.p_};
g.M.DG=function(){return!!this.L&&this.L.G};
g.M.Sv=function(H,E,G){E=E===void 0?!1:E;this.pR();this.L&&(H?G?VG(this.L,G,E):VG(this.L,"YOUTUBE_DRAWER_AUTO_OPEN",E):EK(this.L))};
g.M.t3=function(H,E){this.player.publish(H?"cardsteasershow":"cardsteaserhide",E)};
g.M.G$=function(){this.player.K().T$.unsubscribe("vast_info_card_add",this.N2,this);g.Tn(this.player.getRootNode(),g.JN.IV_DRAWER_OPEN);for(var H=this.WF,E=g.eD,G=0,P=H.length;G<P;G++)E.gU(H[G]);this.WF.length=0;g.UM.prototype.G$.call(this)};
g.M.createElement=function(H){H=new g.D(H);g.d(this,H);return H.element};g.IK("annotations_module",byo);g.IK("creatorendscreen",PkD);})(_yt_player);
