(function(g){var window=this;'use strict';var zaJ=function(H,E){var G=g.pu("SPAN");g.AE(G,{display:"inline-block","white-space":"pre-wrap"});g.AE(G,xFK(H,E));G.classList.add("ytp-caption-segment");H.B.appendChild(G);G.previousElementSibling&&(g.AE(G.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.AE(G,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return G},kP=function(){this.segments=[]},VB3=function(){this.G=this.time=this.mode=this.W=0;
this.D=new TWM(this);this.T=new TWM(this);this.L=[];this.clear()},FXM=function(H,E,G){SWR(H,E).then(function(P){P&&G(P.trackData,new g.qd(P.metadata))})},f8D=function(){},pVW=function(H,E,G){var P=[],Q;
for(Q in H.L.L)if(H.L.L.hasOwnProperty(Q)){var e=H.L.L[Q];if(g.nl(e,G||null)){var w=e.info.captionTrack;w&&w.languageCode===E&&P.push(e)}}return P.length?P[0]:null},IU=function(H){this.T=H;
this.G=[];this.L=this.W=this.row=0;this.style=new Wr;for(H=this.D=0;H<=15;H++){this.G[H]=[];for(var E=0;E<=32;E++)this.G[H][E]=new HqR}},PFR=function(H,E){H.L.sort(function(Q,e){var w=Q.time-e.time;
return w===0?Q.order-e.order:w});
for(var G=g.R(H.L),P=G.next();!P.done;P=G.next())P=P.value,H.time=P.time,P.type===0?EgZ(H,P.l6,P.b6,E):P.type===1&&H.W&496&&GoW(H.T,P.l6,P.b6,E);H.L.length=0},QAH=function(){return g.pr("yt-player-caption-display-settings")},ekW=function(H){if(!sA$.test(H))throw Error("'"+H+"' is not a valid hex color");
H.length==4&&(H=H.replace(ogM,"#$1$1$2$2$3$3"));H=H.toLowerCase();H=parseInt(H.slice(1),16);return[H>>16,H>>8&255,H&255]},w4u=function(H){H.Jm=Array.from(H.element.getElementsByClassName("caption-visual-line"));
for(var E=H.W.params.JH,G=0,P=0,Q=H.Jm.length-1;G<E&&Q>-1;){var e=H.Jm[Q];P+=H.G?e.offsetWidth:e.offsetHeight;G++;Q--}H.N=P;E=Math;G=E.max;isNaN(H.E7)&&((P=H.L.Ld)?(Q=g.pu("SPAN"),g.rA(Q,"\u2013".repeat(P)),g.AE(Q,xFK(H,H.L.sT)),H.D.appendChild(Q),H.E7=Q.offsetWidth,H.D.removeChild(Q)):H.E7=0);P=H.D;H.p_=G.call(E,H.E7,H.FI,(H.G?P.offsetHeight:P.offsetWidth)+1)},Wr=function(){this.type=0},hkM=function(H,E){var G=new g.qd;
G.languageCode=H.languageCode;G.languageName=H.languageName;G.name=H.name;G.displayName=H.displayName;G.kind=H.kind;G.isDefault=!1;G.L=H.L;G.isTranslateable=H.isTranslateable;G.vssId=H.vssId;G.url=H.url;G.translationLanguage=E;H.xtags&&(G.xtags=H.xtags);H.captionId&&(G.captionId=H.captionId);return G},$1D=function(H,E,G,P,Q){P===0&&(P=0x8000000000000);
var e={};E.wpWinPosId&&Object.assign(e,H.D.get(E.wpWinPosId));E.wsWinStyleId&&Object.assign(e,H.T.get(E.wsWinStyleId));H=E.rcRowCount;H!==void 0&&(e.JH=H);E=E.ccColCount;E!==void 0&&(e.Ld=E);if(e.o3===2||e.o3===3)E=e.JH,e.JH=e.Ld,e.Ld=E;return new AV(G,P,0,Q,e)},tk$=function(H,E){var G=g.eS(H.segments,E);
G>=0||G<0&&(-G-1)%2===1||(G=-G-1,G>0&&E-H.segments[G-1]===1&&G<H.segments.length&&H.segments[G]-E===1?(g.Fh(H.segments,G),g.Fh(H.segments,G-1)):G>0&&E-H.segments[G-1]===1?H.segments[G-1]=E:G<H.segments.length&&H.segments[G]-E===1?H.segments[G]=E:(g.nH(H.segments,G,0,E),g.nH(H.segments,G+1,0,E)))},mV=function(H){return H.L_&&H.L_.L},EgZ=function(H,E,G,P){E===255&&G===255||!E&&!G?(++H.G===45&&H.reset(),H.D.W.clear(),H.T.W.clear()):(H.G=0,GoW(H.D,E,G,P))},m1H=function(H,E){switch(H){case 0:return kou[(E&
127)-32];
case 1:return WnC[E&15];case 2:return IUC[E&31];case 3:return A9d[E&31]}return 0},uaH=function(H,E){var G=H.S.xt().E2().textTracks;
H=H.W.toString();for(var P=0;P<G.length;P++){var Q=G[P];Q.id===H&&(E?Q.mode!=="showing"&&(Q.mode="showing"):Q.mode==="showing"&&(Q.mode="disabled"))}},vgC=function(H,E,G){g.L(function(P){H.L=g.a2(E,G);
g.P2(P)})},MkW=function(H,E){return E?H.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},SWR=function(H,E){var G,P,Q;
return g.L(function(e){if(e.L==1)return G=H+"|"+E,g.U(e,g.De(),2);if(e.L!=3){P=e.W;if(!P)throw g.Xs("gct");return g.U(e,g.K4(P),3)}Q=e.W;return e.return(Q.get("captions",G))})},d1M=function(H){var E=1+.25*(H.fontSizeIncrement||0);
if(H.offset===0||H.offset===2)E*=.8;return E},D1W=function(H,E){var G={},P=E.getAttribute("ws");
Object.assign(G,P?H.L_[P]:H.D);H=ui(E,"mh");H!=null&&(G.Zn=H);H=ui(E,"ju");H!=null&&(G.textAlign=H);H=ui(E,"pd");H!=null&&(G.o3=H);H=ui(E,"sd");H!=null&&(G.JW=H);H=vr(E,"wfc");H!=null&&(G.windowColor=H);E=Mv(E,"wfo");E!==void 0&&(G.windowOpacity=E/255);return G},dX=function(H,E){H=H.getAttribute(E);
if(H!=null)return H==="1"},ngR=function(H){var E={};
if(H=g.xr(H))E.lang=H,g.wtZ.test(H)&&(E.o3=1);return E},OqK=function(H,E){w4u(H);
var G=H.Jm.reduce(function(e,w){return(H.G?w.offsetWidth:w.offsetHeight)+e},0);
G=H.N-G;if(G!==H.z$){var P=G>0&&H.z$===0,Q=G<H.z$;E||isNaN(G)||P||!Q||(g.aG(H.element,"ytp-rollup-mode"),H.Z(H.element,"transitionend",H.wg));g.AE(H.D,"transform",aUW(H,G));H.z$=G}w4u(H)},KnW=function(H,E,G){var P=g.DB(H,0,1836476516),Q=9E4;
P&&(Q=g.j_(P)||9E4);P=0;for(var e=g.Fu(H,1836019558),w=0;w<e.length;w++){var t=e[w];w<E.length&&(t=g.DB(H,t.dataOffset,1953653094))&&(t=g.DB(H,t.dataOffset,1952867444))&&(t=g.W9t(t)/Q*1E3,w===0&&(P=t),E[w].q1=t-P+G||G*w*1E3)}},D3=function(H,E){if(H.W&&(E===void 0||!E)||!H.videoData.captionTracks.length)return!1;
H=H.getAudioTrack();return!!H.L||H.W==="FORCED_ON"},nS=function(H){H=H.split("px");
return H.length>0?(H=Number(H[0]))?H:0:0},jAd=function(H){var E=H.au.getVideoContentRect(!0).height,G=H.au.getVideoContentRect(!0).width;
if(!E||!G)return null;E*=H.WF.height;G*=H.WF.width;return{width:G,height:E}},aUW=function(H,E){if(!E)return"";
H.G&&H.W.params.JW!==1&&(E*=-1);return"translate"+(H.G?"X":"Y")+"("+E+"px)"},NLW=function(H,E){H.L=function(G,P){if(G.info.G){var Q=G;
if(H.gs.length>0){for(Q=H.gs.shift();H.gs.length>0;)Q=g.Np(Q,H.gs.shift());Q=g.Np(Q,G)}if(Q){G=Q;try{var e=g.wD(G)*1E3}catch(W){e=G.info.startTime*1E3}try{var w=g.ql1(G)*1E3}catch(W){w=G.info.duration*1E3}if(e<0||w<0)e<0&&(e=G.info.startTime*1E3),w<0&&(w=G.info.duration*1E3);G.info.startTime=e/1E3;G.info.D=e/1E3;G.info.duration=w/1E3;G.info.B=w/1E3;e=H.oZ(Q);w=e.U7;e={formatId:e.formatId,startTimeMs:e.startTimeMs,durationMs:e.durationMs,pW:w,N4:w};w=c9W(H.i4,e.startTimeMs);var t=(G=w>=0?H.i4[w]:null)?
G.startTimeMs+G.durationMs:0,k=e.startTimeMs+e.durationMs;!G||e.startTimeMs-t>H.W?H.i4.splice(w+1,0,e):(G.durationMs=Math.max(t,k)-G.startTimeMs,G.N4=Math.max(G.N4,e.N4));P(H.i4);e=g.h_(Q);P=H.G;e=e.buffer.slice(e.byteOffset,e.byteLength+e.byteOffset);Q=Q.info.D;P.C?P.D==null?g.d3(P.logger,350058965,"Null loaded track meta data at captions data received"):E.oz(e,P.D,Q*1E3):g.d3(P.logger,350058965,"Null Representation at captions data received")}else g.d3(H.logger,350058965,"Empty slice")}else H.gs.push(G)};
H.S.addEventListener("sabrCaptionsDataLoaded",H.L)},bqH=function(H,E,G){H.PF=H.PF||!!G;
var P={};Object.assign(P,H.L.sT);Object.assign(P,G||E.L);Object.assign(P,H.gt.sT);(G=!H.B)&&y9W(H);for(var Q=H.O7&&H.T$&&g.aP(P,H.T$)?H.O7:zaJ(H,P),e=typeof E.text==="string",w=e?E.text.split("\n"):[E.text],t=0;t<w.length;t++){var k=t>0||!E.append,W=w[t];k&&!G?(y9W(H),Q=zaJ(H,P)):k&&G&&(G=!1);W&&(Q.appendChild(e?g.HL(W):W),e||W.tagName!=="RUBY"||W.childElementCount!==4||g.Zs||!g.ux(W.children[2],"text-emphasis")||(k=H.G?"padding-right":"padding-top",g.ux(W.children[2],"text-emphasis-position")&&(k=
H.G?"padding-left":"padding-bottom"),g.E7?g.AE(Q,k,"1em"):g.AE(Q,k,"0.5em")))}H.T$=P;H.O7=Q;H.C.push(E)},aU=function(H,E){if(!H.L)return null;
if(H.L_&&H.L_.D)return H.L_.D;E=iqW(H,E);E=g.CL(H.L.W,E);var G=null;if(q7Z(H.X)){var P=H.S.isInline()?void 0:g.pr("yt-player-caption-sticky-language");for(var Q=[P,H.videoData.captionsLanguagePreference,H.X.captionsLanguagePreference,g.KH(H.videoData,"yt:cc_default_lang")],e=!1,w=0;w<Q.length;w++){var t=Q[w];if(t){e=!0;for(var k=0;k<E.length;k++)if(g.xr(E[k])===t)return E[k];for(k=0;k<E.length;k++)if(g.xr(E[k]).split("-")[0]===t.split("-")[0])return E[k]}}if(e&&H.L&&(Q=H.L.T,Q.length))for(Q=g.R(Q),
e=Q.next();!e.done;e=Q.next())if(e=e.value,e.languageCode===P){G=e;break}}else for(P=[H.videoData.captionsLanguagePreference,H.X.captionsLanguagePreference,g.KH(H.videoData,"yt:cc_default_lang")],Q=0;Q<P.length;Q++)for(e=0;e<E.length;e++)if(g.xr(E[e])===P[Q])return E[e];P=null;H.L_&&H.L_.G&&(P=H.L_.G);P||(P=E.find(function(W){return W.isDefault})||null);
P||(P=E[0]||mV(H));P&&G&&g.xr(P).split("-")[0]!==G.languageCode.split("-")[0]&&(P=hkM(P,G));return P},iqW=function(H,E){g.Oz(H.videoData)&&(E=!0);
E||(E=H.D==="TTS"?!1:H.D==="INNERTUBE"?!1:!0);return E||H.X.U("web_deprecate_always_includes_asr_setting")&&g.sn(H.X)?!0:!!g.UF().A7(66)},Rko=function(H,E){H.player.hR(E);
E=g.R(E);for(var G=E.next();!G.done;G=E.next())g.Ih(H.O7,G.value);OK(H.T$)},GoW=function(H,E,G,P){H.W.update();
E=J9Z(E,G,H.W);switch(E.result){case 0:return;case 1:case 2:return}var Q=E.Xy;G=E.qP;if(32<=Q||!Q)H.L.mode&H.L.W&&(E=Q,E&128&&(E=127),G&128&&(G=127),H=H.D.L,E&96&&KS(H,0,E),G&96&&KS(H,0,G),E!==0&&G!==0&&H.style.type===3&&jw(H,P));else if(Q&16)a:if(!H.W.matches(Q,G)&&(E=H.W,E.Xy=Q,E.qP=G,E.state=2,E=Q&8?H.C:H.G,H.D=E,H.L.mode=1<<(H.T<<2)+(E.T<<1)+(E.style.type===4?1:0),(H.L.mode|1<<(H.T<<2)+(E.T<<1)+(E.style.type!==4?1:0))&H.L.W))if(G&64){P=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(Q&7)<<1|G>>5&1];
H=G&16?((G&14)>>1)*4:0;G=E.L;switch(E.style.get()){case 4:P=G.row;break;case 3:if(P!==G.row){if(P<G.L&&(P=G.L,P===G.row))break;var e=1+G.row-G.L,w=1+P-G.L;r9d(G,w,e,G.L);E=e;Q=G.L;w<e?(e=w+Q-e,e>0&&(E+=e,Q-=e)):(e=e+Q-w,e>0&&(Q-=e));cr(G,E,Q)}}G.row=P;G.W=H+1}else switch(Q&7){case 1:switch(G&112){case 32:KS(E.L,0,32);break a;case 48:G===57?(P=E.L,Nv(P).L=0,P.W<32&&P.W++):KS(E.L,1,G&15)}break;case 2:G&32&&KS(E.L,2,G&31);break;case 3:G&32&&KS(E.L,3,G&31);break;case 4:case 5:if(32<=G&&G<=47)switch(G){case 32:BLo(E);
break;case 33:P=E.L;P.W>1&&(--P.W,Nv(P).L=0);break;case 36:P=E.L;E=Nv(P);for(H=0;H<=15;H++)for(G=0;G<=32;G++)if(P.G[H][G]===E){for(;G<=32;G++)P.G[H][G].reset();break}break;case 37:Y7o(E,2,P);break;case 38:Y7o(E,3,P);break;case 39:Y7o(E,4,P);break;case 40:KS(E.L,0,32);break;case 41:E.style.set(2);E.L=E.W;E.L.L=0;E.L.style=E.style;E.G.mode=1<<E.L.D;break;case 42:P=E.text;P.L=15;P.style.set(4);X4o(P);Zqd(E);break;case 43:Zqd(E);break;case 44:H=E.W;switch(E.style.get()){case 1:case 2:case 3:jw(H,P)}cr(H,
0,15);break;case 45:b:{H=E.L;switch(E.style.get()){default:case 2:case 1:break b;case 4:if(H.row<15){++H.row;H.W=1;break b}break;case 3:}H.L<2&&(H.L=2,H.row<H.L&&(H.row=H.L));E=H.row-H.L+1;jw(H,P);r9d(H,E,E+1,H.L-1);cr(H,H.row,1)}break;case 46:cr(E.D,0,15);break;case 47:jw(E.W,P),E.D.updateTime(E.G.time+0),P=E.D,E.D=E.W,E.W=P,BLo(E)}break;case 7:switch(G){case 33:case 34:case 35:P=E.L,(P.W+=G&3)>32&&(P.W=32)}}},gg$=function(H){var E=void 0,G=g.UF().A7(65);
if(g.sn(H.X)&&G!=null){if(CFo(H)!=null)return!1;E=!G}return E},bi=function(H,E){yI.call(this);
this.W=H;this.D=E;this.track=this.D.languageName==="CC3"?4:0;this.L=new VB3;this.L.W=1<<this.track},xFK=function(H,E){var G={},P=E.background?E.background:H.L.sT.background;
if(E.backgroundOpacity!=null||E.background){var Q=E.backgroundOpacity!=null?E.backgroundOpacity:H.L.sT.backgroundOpacity;P=ekW(P);G.background="rgba("+P[0]+","+P[1]+","+P[2]+","+Q+")";H.dP&&(G["box-decoration-break"]="clone",G["border-radius"]=H.Yp/8+"px")}if(E.fontSizeIncrement!=null||E.offset!=null)G["font-size"]=H.eR*d1M(E)+"px";P=1;Q=E.color||H.L.sT.color;if(E.color||E.textOpacity!=null)Q=ekW(Q),P=E.textOpacity==null?H.L.sT.textOpacity:E.textOpacity,Q="rgba("+Q[0]+","+Q[1]+","+Q[2]+","+P+")",
G.color=Q,G.fill=Q;var e=E.charEdgeStyle;e===0&&(e=void 0);if(e){Q="rgba(34, 34, 34, "+P+")";var w="rgba(204, 204, 204, "+P+")";E.dn&&(w=Q=E.dn);var t=H.eR/16/2,k=Math.max(t,1),W=Math.max(2*t,1),I=Math.max(3*t,1),A=Math.max(5*t,1);P=[];switch(e){case 4:for(;I<=A;I+=t)P.push(W+"px "+W+"px "+I+"px "+Q);break;case 1:W=window.devicePixelRatio>=2?.5:1;for(e=k;e<=I;e+=W)P.push(e+"px "+e+"px "+Q);break;case 2:P.push(k+"px "+k+"px "+w);P.push("-"+k+"px -"+k+"px "+Q);break;case 3:for(I=0;I<5;I++)P.push("0 0 "+
W+"px "+Q)}G["text-shadow"]=P.join(", ")}Q="";switch(E.fontFamily){case 1:Q='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:Q='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:Q='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:Q='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:Q='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:Q=g.aa()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:Q='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}Q&&(G["font-family"]=Q);Q=E.offset;Q==null&&(Q=H.L.sT.offset);switch(Q){case 0:G["vertical-align"]="sub";break;case 2:G["vertical-align"]="super"}E.fontFamily===7&&(G["font-variant"]="small-caps");E.bold&&(G["font-weight"]="bold");E.italic&&(G["font-style"]="italic");E.underline&&(G["text-decoration"]=
"underline");E.aaJ&&(G.visibility="hidden");E.c7===1&&H.G&&(G["text-combine-upright"]="all",G["text-orientation"]="mixed",Q=g.Zs||g.Ez,H.W.params.o3===3?G.transform=Q?"rotate(90deg)":"rotate(180deg)":Q&&(G.transform="rotate(-90deg)"));if(E.textEmphasis===1||E.textEmphasis===2||E.textEmphasis===3||E.textEmphasis===4||E.textEmphasis===5)if(g.Zs)G["font-weight"]="bold";else switch(G["text-emphasis-style"]="filled circle",G["text-emphasis-color"]="currentcolor",G["webkit-text-emphasis"]="filled circle",
E.textEmphasis){case 4:case 3:G["text-emphasis-position"]="under left";G["webkit-text-emphasis-position"]="under left";break;case 5:case 2:G["text-emphasis-position"]="over right",G["webkit-text-emphasis-position"]="over right"}return G},vr=function(H,E){H=H.getAttribute(E);
if(H!=null)return ii.test(H),H},BLo=function(H){H.style.set(1);
H.L=H.D;H.L.L=0;H.L.style=H.style;H.G.mode=1<<H.L.D},Lno=function(H){this.G=H;
this.T=0;this.style=new Wr;this.C=new IU(this.G);this.B=new IU(this.G);this.text=new IU(this.G);this.W=this.C;this.D=this.B;this.L=this.W},lUu=function(H){var E=H.split(":");
H=0;E=g.R(E);for(var G=E.next();!G.done;G=E.next())H=H*60+Number(G.value);return H*1E3},qv=function(H,E,G,P,Q,e,w,t,k,W){var I=W.isInline()&&!0,A={};
Object.assign(A,E);Object.assign(A,H.params);Object.assign(A,G);var m={};Object.assign(m,E.sT);H.params.sT&&Object.assign(m,H.params.sT);Object.assign(m,G.sT);I&&(A.windowOpacity=.6,m.backgroundOpacity=0);A.sT=m;var u=A.o3===1,v=[{J:"span",Y:"captions-text",j:{style:"word-wrap: normal; display: block;"}}],n,O,q;(t=t.xp("caption_edit_on_hover")&&((n=W.getVideoData().getPlayerResponse())==null?void 0:(O=n.captions)==null?void 0:(q=O.playerCaptionsTracklistRenderer)==null?void 0:q.openTranscriptCommand))&&
v.unshift({J:"button",Y:"caption-edit",j:{tabindex:"0","aria-label":U1o()},V:[{J:"svg",j:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{J:"path",j:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.D.call(this,{J:"div",Y:"caption-window",j:{id:"caption-window-"+H.id,dir:u?"rtl":"ltr",tabindex:"0",lang:A.lang},V:v});var N=
this;this.C=[];this.PF=!1;this.W=H;this.T$=this.O7=null;this.WO=e;this.ML=w;this.B=null;this.maxWidth=e*.96;this.maxHeight=w*.96;this.L=A;this.gt=G;this.WF=E;this.D=this.HF("captions-text");this.dP=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.eR=x1H(P,Q,e,w);this.jT=k;t&&(this.T=this.HF("caption-edit"),this.Z(this.T,"click",function(){N.jT()}));
this.type=0;this.Yp=this.eR*d1M(m);this.s7=I;H=new g.DO(this.element,!0);g.d(this,H);H.subscribe("dragstart",this.Rl,this);H.subscribe("dragmove",this.s1,this);H.subscribe("dragend",this.XQ,this);this.MZ=this.BF=this.au=this.hm=0;H="";this.L.windowOpacity&&(H=ekW(this.L.windowColor),H="rgba("+H[0]+","+H[1]+","+H[2]+","+this.L.windowOpacity+")");E={"background-color":H,display:this.L.isVisible===!1?"none":"","text-align":zkH[this.L.textAlign]};this.dP&&(E["border-radius"]=H?this.Yp/8+"px":"");(this.G=
this.W.params.o3===2||this.W.params.o3===3)&&TLC(this,this.element);g.AE(this.element,E);if(I){var r;(r=this.element.parentElement)==null||r.style.setProperty("--caption-window-color",H)}switch(this.L.Y7){case 0:case 1:case 2:g.aG(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.aG(this.element,"ytp-caption-window-bottom")}},Mv=function(H,E){H=H.getAttribute(E);
if(H!=null)return Number(H)},VkC=function(H,E,G,P){var Q=this;
this.S=H;this.G=E;this.logger=G;this.T6=P;this.i4=[];this.gs=[];this.L=null;this.kV={vXN:function(){return Q.L},
AK:function(){return Q.i4}};
H=g.hE(this.S.K().experiments,"html5_override_micro_discontinuities_threshold_ms");this.W=H>0?H:10},q7Z=function(H){return g.sn(H)||H.U("web_enable_caption_language_preference_stickiness")},AV=function(H,E,G,P,Q){g.cP.call(this,H,H+E,{priority:G,
namespace:"captions"});this.id=P;this.params=Q;this.L=[]},S73=function(H,E,G){G=G===void 0?!1:G;
var P=RU.sT;H.G={};Object.assign(H.G,RU);H.G.sT={};Object.assign(H.G.sT,P);H.C={sT:{}};var Q=E.backgroundOverride?H.C:H.G,e=E.background||P.background;ii.test(e);Q.sT.background=e;Q=E.colorOverride?H.C:H.G;e=E.color||P.color;ii.test(e);Q.sT.color=e;Q=E.windowColorOverride?H.C:H.G;e=E.windowColor||RU.windowColor;ii.test(e);Q.windowColor=e;Q=E.backgroundOpacityOverride?H.C:H.G;e=E.backgroundOpacity;e==null&&(e=P.backgroundOpacity);Q.sT.backgroundOpacity=e;Q=E.fontSizeIncrementOverride?H.C:H.G;e=E.fontSizeIncrement;
e==null&&(e=P.fontSizeIncrement);Q.sT.fontSizeIncrement=e;e=E.fontStyleOverride?H.C:H.G;Q=E.fontStyle;Q==null&&(Q=P.bold&&P.italic?3:P.bold?1:P.italic?2:0);e=e.sT;switch(Q){case 1:e.bold=!0;delete e.italic;break;case 2:delete e.bold;e.italic=!0;break;case 3:e.bold=!0;e.italic=!0;break;default:delete e.bold,delete e.italic}Q=E.textOpacityOverride?H.C:H.G;e=E.textOpacity;e==null&&(e=P.textOpacity);Q.sT.textOpacity=e;Q=E.windowOpacityOverride?H.C:H.G;e=E.windowOpacity;e==null&&(e=RU.windowOpacity);Q.windowOpacity=
e;Q=E.charEdgeStyleOverride?H.C:H.G;e=E.charEdgeStyle;e==null&&(e=P.charEdgeStyle);Q.sT.charEdgeStyle=e;Q=E.fontFamilyOverride?H.C:H.G;e=E.fontFamily;e==null&&(e=P.fontFamily);Q.sT.fontFamily=e;H.loaded&&H.In();G&&g.Fj("yt-player-caption-display-settings",E,2592E3)},JV=function(H,E,G){g.iv.call(this,H);
this.videoData=E;this.audioTrack=G;this.T=E.Co},rX=function(H,E){g.iv.call(this,E);
this.L=H;this.S=E;this.logger=new g.Pj("caps");this.D=this.C=null;this.B=new VkC(this.S,this,this.logger,this.L.T6)},Zqd=function(H){H.style.set(4);
H.L=H.text;H.L.style=H.style;H.G.mode=1<<H.L.D},Br=function(H){H=g.Mo(Math.round(H),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-H.length)+H},Fno=function(H,E){var G=jAd(H);
if(!G)return null;var P=H.W?g.xr(H.W):null;P&&g.wtZ.test(P)&&(E.params.o3=1);var Q=H.au.getPlayerSize();P=Q.height*H.WF.height;Q=Q.width*H.WF.width;H.X.playerStyle!=="google-live"||H.G.isDefault||Object.assign(E.params,H.G);switch(E.params.Zn!=null?E.params.Zn:E.L.length>1?1:0){case 1:return new YP(E,H.G,H.C,G.width,G.height,Q,P,H.X.experiments,H.Mt.bind(H),H.S);case 2:return new XF(E,H.G,H.C,G.width,G.height,Q,P,H.X.experiments,H.Mt.bind(H),H.S);default:return new qv(E,H.G,H.C,G.width,G.height,Q,
P,H.X.experiments,H.Mt.bind(H),H.S)}},fUZ=function(H,E,G,P,Q,e,w,t,k){switch(w.tagName){case "b":t.bold=!0;
break;case "i":t.italic=!0;break;case "u":t.underline=!0}for(var W=0;W<w.childNodes.length;W++){var I=w.childNodes[W];if(I.nodeType===3)I=new Z3(E,G,P,Q.id,I.nodeValue,e||W>0,g.ZR(t)?void 0:t),k.push(I),Q.L.push(I);else{var A={};Object.assign(A,t);fUZ(H,E,G,P,Q,!0,I,A,k)}}},HCM=function(H){if(typeof H==="string")return!1;
H=new CS(H,8,0);return p4J(H)},EpW=function(H,E){var G={},P=E.getAttribute("wp");
P&&Object.assign(G,H.N[P]);H=ui(E,"ap");H!=null&&(G.Y7=H);H=Mv(E,"cc");H!=null&&(G.Ld=H);H=Mv(E,"ah");H!=null&&(G.UB=H);H=Mv(E,"rc");H!=null&&(G.JH=H);E=Mv(E,"av");E!=null&&(G.h2=E);return G},gX=function(H,E){g.iv.call(this,E);
this.L=H;this.S=E;this.D=null;this.C=!1;this.logger=new g.Pj("caps");this.B=g.D6(this.S,this.L)},Gr$=function(H,E,G,P){var Q={};
Object.assign(Q,EpW(H,E));Object.assign(Q,D1W(H,E));P?g.aP(Q,H.D)?(P=H.T,Q=H.D):P="_"+LS++:P=E.getAttribute("id")||"_"+LS++;H=Mv(E,"t")+G;E=Mv(E,"d")||0x8000000000000;if(Q.o3===2||Q.o3===3)G=Q.JH,Q.JH=Q.Ld,Q.Ld=G;return new AV(H,E,0,P,Q)},KS=function(H,E,G){E>=2&&H.W>1&&(--H.W,Nv(H).L=0);
var P=Nv(H);P.timestamp=H.T.time+0;P.L=m1H(E,G);H.W<32&&H.W++},PTK=function(H){var E,G=!((E=H.S.xt())==null||!E.eO());
return H.BF&&G&&H.D!=="LIVE"&&H.D!=="SABR_LIVE"},QPd=function(H,E){H.X.U("html5_modify_caption_vss_logging")&&(H.videoData.qF=E)},li=function(H){yI.call(this);
this.D=H;this.pens={};this.N={};this.L_={};this.T="_"+LS++;this.B={};this.W=this.L=null;this.C=!0},UK=function(H){yI.call(this);
this.C=H;this.L=new Map;this.D=new Map;this.T=new Map;this.W=new Map},TLC=function(H,E){var G="vertical-rl";
H.L.JW===1&&(G="vertical-lr");g.kh&&(G=G==="vertical-lr"?"tb-lr":"tb-rl");g.AE(E,"-o-writing-mode",G);g.AE(E,"-webkit-writing-mode",G);g.AE(E,"writing-mode",G);g.AE(E,"text-orientation","upright");g.aG(E,"ytp-vertical-caption");H.W.params.o3===3&&(g.AE(E,"text-orientation",""),g.AE(E,"transform","rotate(180deg)"))},opH=function(H){var E=sPM.length;
if(H.byteLength<E)return!1;H=new Uint8Array(H,0,E);for(var G=0;G<E;G++)if(sPM[G]!==H[G])return!1;return!0},edd=function(H){if(H.X.sZ===1||H.videoData.wH===1||g.KH(H.videoData,"yt:cc")==="alwayson")return!0;
if(H.videoData.captionTracks.length)var E=H.getAudioTrack().W;if(H.X.sZ===2){if(g.sn(H.X))var G=CFo(H);else if(H.storage)try{G=H.storage.get("module-enabled")}catch(Q){H.storage.remove("module-enabled")}else G=null;if(G!=null)return!!G}G=MkW(H.player.getAudioTrack(),g.sn(H.X));var P=g.KH(H.videoData,"yt:cc");if(gg$(H)===void 0){if(G==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return P?P==="on":!0;if(G==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return P==="on"}else return P==="on";return E==="ON"||g.KH(H.videoData,
"yt:cc")==="on"},YP=function(H,E,G,P,Q,e,w,t,k,W){qv.call(this,H,E,G,P,Q,e,w,t,k,W);
this.type=1},wP$=function(H,E){return E!=null&&E in H.L.L?H.L.L[E]:null},hd$=function(H,E){if(!g.D9n(H)||H.L!=null&&g.D6(E,H.L)&&H.L.L.rawcc!=null)return!1;
E=!!H.L&&H.L.isManifestless&&Object.values(H.L.L).some(function(G){return g.nl(G,"386")});
H=!!H.L&&!H.L.isManifestless&&g.X4t(H.L);return E||H},Y7o=function(H,E,G){var P=H.W,Q=!1;
switch(H.style.get()){case 4:case 1:case 2:H.style.get()===4&&P.L>0||(jw(P,G),X4o(H.W),X4o(H.D),P.row=15,P.L=E,Q=!0)}H.style.set(3);H.L=P;H.L.style=H.style;H.G.mode=1<<P.D;Q?P.W=1:P.L!==E&&(P.L>E?(jw(P,G),cr(P,P.row-P.L,E)):P.row<E&&(E=P.L),P.L=E)},$LD=function(H,E,G){var P=[],Q;
for(Q in H.L.L)if(H.L.L.hasOwnProperty(Q)){var e=H.L.L[Q];if(g.nl(e,G||null)){var w=e.info.captionTrack;w&&w.languageCode===E&&P.push(e)}}return P.length?P[0]:null},kro=function(H,E,G,P,Q,e,w){var t=e[0],k=w[t.getAttribute("p")];
if(k.Fe===1){var W=e[1],I=e[2];e=e[3];t.getAttribute("t");W.getAttribute("t");I.getAttribute("t");e.getAttribute("t");t.getAttribute("p");W.getAttribute("p");e.getAttribute("p");w=w[I.getAttribute("p")];t=tVW(t.textContent,W.textContent,I.textContent,e.textContent,w);return new Z3(H,E,Q,G,t,P,k)}switch(k.Fe){case 9:case 10:k.textEmphasis=1;break;case 11:k.textEmphasis=2;break;case 12:k.textEmphasis=3;break;case 13:k.textEmphasis=4;break;case 14:k.textEmphasis=5}return new Z3(H,E,Q,G,t.textContent||
"",P,k)},WKC=function(H,E,G){if(typeof E==="string"||HCM(E))return[{trackData:E,
q1:G}];if(typeof E==="string"&&E.substring(0,6)==="WEBVTT"||typeof E!=="string"&&opH(E))return[{trackData:E,q1:G}];var P=new DataView(E);if(P.byteLength<=8||P.getUint32(4)!==1718909296)return[];var Q=g.oln(P);if(H.W&&Q){var e=g.WA7(Q),w=g.INv(Q);Q=Q.bA;e&&Q&&H.W.dh(Q,e,w)}H=g.Fu(P,1835295092);if(!H||!H.length||!H[0].size)return[];e=[];for(w=0;w<H.length;w++)Q=H[w],Q=new Uint8Array(E,Q.dataOffset,Q.size-(Q.dataOffset-Q.offset)),Q=g.x$(Q),e.push({trackData:Q,q1:G+w*1E3});KnW(P,e,G);return e=e.filter(function(t){return!!t.trackData})},
CFo=function(H){if(!H.S.isInline())return g.pr("yt-player-sticky-caption")},cr=function(H,E,G){for(var P=0;P<G;P++)for(var Q=0;Q<=32;Q++)H.G[E+P][Q].reset()},xP=function(H,E){g.J.call(this);
this.S=H;this.X=E;this.L=null;this.W=this.S.Wn();this.logger=new g.Pj("caps")},za=function(H,E){H.S.isInline()||g.Fj("yt-player-sticky-caption",E,2592E3)},Ta=function(H){var E=H.byteOffset;
H.byteOffset+=1;return H.L.getUint8(E)},IcJ=function(H,E,G,P,Q,e){g.J.call(this);
this.policy=H;this.player=E;this.uJ=G;this.N=P;this.T=Q;this.L_=e;this.D=new kP;this.C=-1;this.W=this.G=this.L=null;this.p_=0;this.B=new g.Wt(this.Sp,1E3,this);this.events=new g.Z0(this);g.d(this,this.B);g.d(this,this.events);this.events.Z(E,"SEEK_COMPLETE",this.bf);this.bf();this.Sp()},x1H=function(H,E,G,P){var Q=E/360*16;
E>=H&&(H=640,P>G*1.3&&(H=480),Q=G/H*16);return Q},HqR=function(){this.timestamp=this.L=0},tVW=function(H,E,G,P,Q){var e=g.aa(),w=e?g.pu("DIV"):g.pu("RUBY"),t=g.pu("SPAN");
t.textContent=H;w.appendChild(t);H=e?g.pu("DIV"):g.pu("RP");H.textContent=E;w.appendChild(H);E=e?g.pu("DIV"):g.pu("RT");E.textContent=G;w.appendChild(E);G=Q.Fe;if(G===10||G===11||G===12||G===13||G===14)if(g.AE(E,"text-emphasis-style","filled circle"),g.AE(E,"text-emphasis-color","currentcolor"),g.AE(E,"webkit-text-emphasis","filled circle"),Q.Fe===11||Q.Fe===13)g.AE(E,"webkit-text-emphasis-position","under left"),g.AE(E,"text-emphasis-position","under left");G=!0;if(Q.Fe===4||Q.Fe===7||Q.Fe===12||
Q.Fe===14)g.AE(w,"ruby-position","over"),g.AE(w,"-webkit-ruby-position","before");else if(Q.Fe===5||Q.Fe===6||Q.Fe===11||Q.Fe===13)g.AE(w,"ruby-position","under"),g.AE(w,"-webkit-ruby-position","after"),G=!1;Q=e?g.pu("DIV"):g.pu("RP");Q.textContent=P;w.appendChild(Q);e&&(P=G,g.AE(w,{display:"inline-block",position:"relative"}),e=w.firstElementChild.nextElementSibling,g.AE(e,"display","none"),e=e.nextElementSibling,g.AE(e,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.AE(w.lastElementChild,"display","none"),P?(g.AE(w,"padding-top","0.6em"),g.AE(e,"top","0")):(g.AE(w,"padding-bottom","0.6em"),g.AE(e,"bottom","0")));return w},U1o=function(){var H=void 0;
H=H===void 0?{}:H;var E="suggest_correction"in g.KdM?g.KdM.suggest_correction:"Edit caption";E=E||"";var G={},P;for(P in H){G={lZ:G.lZ};G.lZ=P;var Q=function(e){return function(){return String(H[e.lZ])}}(G);
E=E.replace(new RegExp("\\$\\{"+G.lZ+"\\}","gi"),Q);E=E.replace(new RegExp("\\$"+G.lZ,"gi"),Q)}return E},VI=function(H){var E=H.byteOffset;
H.byteOffset+=4;return H.L.getUint32(E)},yI=function(){g.J.apply(this,arguments)},mLM=function(H,E,G){H.L||(H.L=new ALD);
H=H.L.G(E,G);Math.random()<.01&&g.p5(Error("Deprecated subtitles format in web player: WebVTT"));return H},ujK=function(H){return H.L&&H.L.T?H.L.T+H.player.YV()<H.player.getCurrentTime():!1},TWM=function(H){this.L=H;
this.T=0;this.G=new Lno(this.L);this.C=new Lno(this.L);this.W=new Sw;this.D=this.G},XF=function(H,E,G,P,Q,e,w,t,k,W){qv.call(this,H,E,G,P,Q,e,w,t,k,W);
var I=this;this.type=2;this.Jm=[];this.p_=this.N=this.z$=0;this.E7=NaN;this.FI=0;this.U2=null;this.G6=new g.Wt(this.wg,433,this);this.T&&(W.createClientVe(this.T,this,167342),this.Z(this.T,"click",function(){W.logClick(I.T)}),H=new g.DO(this.element,!0),g.d(this,H),H.subscribe("hoverstart",function(){W.logVisibility(I.T,!0)},this));
g.aG(this.element,"ytp-caption-window-rollup");g.d(this,this.G6);g.AE(this.element,"overflow","hidden")},MVR=function(H,E){var G=[],P;
for(P in H.L.L)if(H.L.L.hasOwnProperty(P)){var Q=H.L.L[P];if(g.nl(Q,E||null)){var e=Q.info.id,w=e,t="."+e,k="",W="";if(Q=Q.info.captionTrack)e=Q.languageCode,w=Q.displayName,t=Q.vssId,k=Q.kind,W=Q.id;else{Q=e;var I=g.TfD.get(Q);I==null&&(I=vp3[Q]||vp3[Q.replace(/-/g,"_")],g.TfD.set(Q,I));Q=I;w=Q||w}G.push(new g.qd({id:P,languageCode:e,languageName:w,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:t,kind:k,captionId:W}))}}return G},dLJ=function(H){g.UM.call(this,H);
var E=this;this.S=H;this.O7=[];this.Jm={};this.Yp={};this.N=!1;this.D="NONE";this.L=this.L_=this.p_=this.eR=this.hm=null;this.G6={zA:function(){E.zA()},
oz:function(e,w,t,k){E.oz(e,w,t,k)}};
this.W=null;this.X=this.S.K();this.videoData=this.S.getVideoData();this.au=this.S.NZ();this.G={sT:{}};this.C={sT:{}};g.B$(this.videoData)?this.D="OFFLINE":hd$(this.videoData,this.S)?this.D="SABR_LIVE":g.pnU(this.videoData,this.S)?this.D="LIVE":this.videoData.captionTracks.length?this.D="INNERTUBE":this.videoData.G6&&(this.D="TTS");this.BF=this.X.controlsType==="3";this.MZ=new xP(this.S,this.X);this.PF=new g.Z0(this);this.B=new g.D({J:"div",Y:"ytp-caption-window-container",j:{id:"ytp-caption-window-container"}});
this.WF={top:0,right:0,bottom:0,left:0,width:1,height:1};var G=null,P=g.Ev("yt-html5-player-modules::subtitlesModuleData");P&&(G=new g.TA(P));this.storage=G;var Q;this.s7=!((Q=H.xt())==null||!Q.rZ());this.T=PTK(this);this.E7=!this.T&&this.BF&&this.s7&&(this.D==="LIVE"||this.D==="SABR_LIVE");g.d(this,this.MZ);this.T?this.z$=this.T$=null:(this.T$=new g.tr(this.mK,void 0,this),g.d(this,this.T$),this.z$=new g.Wt(this.l5R,2E3,this),g.d(this,this.z$));g.d(this,this.PF);g.as(this.player,this.B.element,4);
g.d(this,this.B);this.T||this.PF.Z(H,"resize",this.In);(this.FI=g.HZ(this.X)&&!g.Qu()&&!this.S.isFullscreen()&&!this.T&&!this.E7)&&this.PF.Z(H,"resize",this.mVx);this.PF.Z(H,"onPlaybackAudioChange",this.C47);this.PF.Z(H,g.Ya("captions"),function(e){E.onCueRangeEnter(e)});
this.PF.Z(H,g.XT("captions"),function(e){E.onCueRangeExit(e)});
S73(this,QAH()||{});this.player.GU("onCaptionsModuleAvailable")},X4o=function(H){H.row=H.L>0?H.L:1;
H.W=1;cr(H,0,15)},FF=function(H){var E=mV(H);
return!!E&&H.W===E},DLZ=function(H,E){var G=[],P;
for(P in H.L.L)if(H.L.L.hasOwnProperty(P)){var Q=H.L.L[P];if(g.nl(Q,E||null)){var e=Q.info.id,w=e,t="."+e,k="",W="";if(Q=Q.info.captionTrack)e=Q.languageCode,w=Q.displayName,t=Q.vssId,k=Q.kind,W=Q.id;G.push(new g.qd({id:P,languageCode:e,languageName:w,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:t,kind:k,captionId:W}))}}return G},Sw=function(){this.state=this.qP=this.Xy=0},npM=function(H,E){if(E instanceof AV){var G=H.Jm[E.id];
G&&G.W!==E&&(G.dispose(),delete H.Jm[E.id],G=null);G||(G=Fno(H,E))&&(H.Jm[E.id]=G)}else G=E.windowId,H.Yp[G]||(H.Yp[G]=[]),H.Yp[G].push(E)},c9W=function(H,E){H=g.eS(H,{startTimeMs:E},function(G,P){return G.startTimeMs-P.startTimeMs});
return H>=0?H:-H-2},OK=function(H){H.isActive()||H.start()},acD=function(H,E){if(!H.L)return{};
if(E){g.ZR(E)||H.rG(E.vss_id,"m");if(H.T||!g.rW(E))return;if(g.ZR(E)){fS(H,null,!0);return}for(var G,P=g.CL(H.L.W,!0),Q=0;Q<P.length;Q++){var e=P[Q];e.languageCode!==E.languageCode||G&&(e.languageName!==E.languageName||(e.captionId||"")!==(E.captionId||"")||g.y9(e)!==E.displayName)||(G=E.translationLanguage?hkM(e,E.translationLanguage):e)}H.bS(E.position);!G||G===H.W&&H.loaded||(E=g.zi(),P=g.xr(G),E.length&&P===E[E.length-1]||(E.push(P),g.Fj("yt-player-caption-language-preferences",E)),q7Z(H.X)&&
!H.S.isInline()&&g.Fj("yt-player-caption-sticky-language",P,2592E3),fS(H,G,!0))}else return H.loaded&&H.W&&!FF(H)?g.ex(H.W):{};return""},KKW=function(H,E,G){E&&!H.p_?(E=OCW({o3:0,
lang:"en"}),H.p_=[E,new Z3(E.start,E.end-E.start,0,E.id,G!=null?G:"Captions look like this")],H.player.MV(H.p_)):!E&&H.p_&&(Rko(H,H.p_),H.p_=null)},jw=function(H,E){if(H.style.type===3){for(var G=0,P=0,Q=H.T.time+0,e="",w="",t=Q,k=1;k<=15;++k){for(var W=!1,I=P?P:1;I<=32;++I){var A=H.G[k][I];
if(A.L!==0){G===0&&(G=k,P=I);W=String.fromCharCode(A.L);var m=A.timestamp;m<Q&&(Q=m);A.timestamp=t;w&&(e+=w,w="");e+=W;W=!0}if((A.L===0||I===32)&&W){w="\n";break}else if(P&&!W)break}if(G&&!W)break}e&&E.D(G,P,Q,t,e)}else for(P=G=0,e=Q=H.T.time+0,w=1;w<=15;++w)for(t="",k=1;k<=32;++k)if(I=H.G[w][k],A=I.L,A!==0&&(G===0&&(G=w,P=k),W=String.fromCharCode(A),m=I.timestamp,m<=Q&&(Q=m),t+=W,I.reset()),k===32||A===0)t&&E.D(G,P,Q,e,t),Q=e,t="",P=G=0},y9W=function(H){H.B=g.pu("SPAN");
g.AE(H.B,{display:"block"});g.aG(H.B,"caption-visual-line");H.D.appendChild(H.B)},Z3=function(H,E,G,P,Q,e,w){e=e===void 0?!1:e;
w=w===void 0?null:w;g.cP.call(this,H,H+E,{priority:G,namespace:"captions"});this.windowId=P;this.text=Q;this.append=e;this.L=w},J9Z=function(H,E,G){if(H===255&&E===255||!H&&!E)return{Xy:H,
qP:E,result:0};H=jPD[H];E=jPD[E];if(H&128){var P;if(P=!(E&128))P=E,P=G.zU()&&G.qP===P;if(P)return{Xy:H,qP:E,result:1}}else if(E&128&&1<=H&&H<=31)return{Xy:H,qP:E,result:2};return{Xy:H,qP:E,result:3}},CS=function(H,E,G){this.trackData=H;
this.C=G;this.version=this.T=this.G=this.byteOffset=0;this.W=[];this.L=new DataView(this.trackData)},OCW=function(H){var E="_"+LS++;
return new AV(0,0x8000000000000,0,E,H)},cLo=function(H,E){if(H.policy.sV&&H.player.J2()){var G=g.h5(E,H.policy,{});
G.set("pot",H.player.J2());G=G.TU()}else G=g.h5(E,H.policy,{}).TU();var P={format:"RAW",withCredentials:!0};if(H.policy.z$){P.method="POST";var Q=E.D;Q&&Object.keys(Q).length>0?P.postBody=g.Z8(Q,g.$i):P.postBody=(0,g.Vi)([120,0])}H.T&&(P.responseType="arraybuffer");var e=++H.p_,w=(0,g.ON)();H.W=g.yb(G,P,3,100,-1,function(t){t.errorCode==="net.timeout"&&H.player.g5("capnt",{rn:e++})}).then(function(t){if(H.policy.QJ7&&e%100===1){var k=(0,g.ON)();
H.player.g5("caprsp",{rn:e,ms:k-w,kb:(t.xhr.responseText.length/1024).toFixed()})}a:{t=t.xhr;H.Iu();if(H.G){var W=!(H.T?t.response:t.responseText)||t.status>=400;if(k=g.mau(t)){t=g.h5(H.G,H.policy,{});H.G.EB(t,k);cLo(H,H.G);break a}if(W)H.player.g5("capfail",{status:t.status});else{var I;g.ng("fcb_r",(0,g.ON)(),((I=H.player.getVideoData())==null?void 0:I.L_)||"");I=H.G.kp[0];k=I.U7;H.N!=null&&H.C!==k&&(H.T?H.N(t.response,(I.startTime+H.player.YV())*1E3):H.N(t.responseText,(I.startTime+H.player.YV())*
1E3),H.C=k)}}H.G=null;H.W=null}}).KW(function(t){H.G=null;
H.W=null;var k;H.player.g5("capfail",{rn:e,status:(k=t.xhr)==null?void 0:k.status})});
H.G=E;tk$(H.D,H.G.kp[0].U7)},p4J=function(H){if(!(H.byteOffset<H.L.byteLength)||VI(H)!==1380139777)return!1;
H.version=Ta(H);if(H.version>1)return!1;Ta(H);Ta(H);Ta(H);return!0},fS=function(H,E,G){H.loaded&&H.unload();
G!=null&&(H.N=G,H.N&&(g.sn(H.X)?za(H,!!E):pS(H,!!E)));E!==null||D3(H,!0)||H.cL(E,!!E,H.N?"m":"s");H.W=E;D3(H)&&(H.W=mV(H));var P;QPd(H,(P=H.W)!=null?P:void 0);H.load()},Nv=function(H){return H.G[H.row][H.W]},pS=function(H,E){if(H.storage)try{H.storage.set("module-enabled",E)}catch(G){}},Nid=function(H,E,G,P){P=Object.assign({Zn:0},P);
return new AV(H,E,G,"_"+LS++,P)},r9d=function(H,E,G,P){for(var Q=0;Q<P;Q++)for(var e=0;e<=32;e++){var w=H.G[E+Q][e],t=H.G[G+Q][e];
w.L=t.L;w.timestamp=t.timestamp}},ALD=function(){yI.call(this)},ui=function(H,E){H=Mv(H,E);
return H!==void 0?H:null};
g.iv.prototype.eW=g.Mt(71,function(){return!1});
g.iv.prototype.Y4=g.Mt(70,function(){});
g.Ts.prototype.Y4=g.Mt(69,function(H,E,G){var P=this;this.Iu();E=this.rp(H,E);var Q=this.cF.K().U("html5_report_captions_ctmp_qoe"),e=(0,g.ON)();this.xQ();vgC(this,E,{format:"RAW",onSuccess:function(w){P.L=null;if(Q){var t=(w.responseText.length/1024).toFixed(),k=(0,g.ON)();P.videoData.g5("capresp",{ms:k-e,kb:t})}G.oz(w.responseText,H)},
onError:Q?function(w){var t;w=(t=w==null?void 0:w.status)!=null?t:0;P.videoData.g5("capfail",{status:w})}:void 0,
withCredentials:!0})});
g.Rn.prototype.Y4=g.Mt(68,function(H,E,G){var P=this;this.Iu();E=this.rp(H,E);this.xQ();this.L=g.a2(E,{format:"RAW",onSuccess:function(Q){P.L=null;G.oz(Q.responseText,H)},
withCredentials:!0})});
g.kj.prototype.Wk=g.Mt(67,function(){for(var H=g.V_(document,"track",void 0,this.L),E=0;E<H.length;E++)g.LQ(H[E])});
g.fp.prototype.Wk=g.Mt(66,function(){this.mediaElement.Wk()});
g.kj.prototype.rZ=g.Mt(65,function(){return!(!this.L.textTracks||!this.L.textTracks.addEventListener)});
g.fp.prototype.rZ=g.Mt(64,function(){return this.mediaElement.rZ()});
g.kj.prototype.eO=g.Mt(63,function(){return!!this.L.textTracks});
g.fp.prototype.eO=g.Mt(62,function(){return this.mediaElement.eO()});
g.kj.prototype.uF=g.Mt(61,function(H){for(var E=0;E<H.length;E++)this.L.appendChild(H[E])});
g.fp.prototype.uF=g.Mt(60,function(H){this.mediaElement.uF(H)});
g.rp.prototype.dh=g.Mt(59,function(H,E,G){this.ze.dh(H,E,G)});
g.CQ.prototype.dh=g.Mt(58,function(H,E,G){this.W.set(H,{bE:E,N5:G})});
g.Gs.prototype.dh=g.Mt(57,function(H,E,G){this.WF.dh(H,E,G)});
g.rp.prototype.dN=g.Mt(56,function(H){return this.ze.dN(H)});
g.Gs.prototype.dN=g.Mt(55,function(H){var E=2;this.T.has(H)?E=0:g.H$(this,H)&&(E=1);return E});
g.NK.prototype.ZG=g.Mt(43,function(H){var E=g.TF(this.app,{playerType:void 0});return E?E.ZG(H):!1});
g.gK.prototype.ZG=g.Mt(42,function(H){return this.Fo.M4.ZG(H)});
g.hS.prototype.ZG=g.Mt(41,function(H){return this.tj().some(function(E){return E.namespace===H})});
g.iX.prototype.ZG=g.Mt(40,function(){return!1});
g.NK.prototype.rG=g.Mt(38,function(H,E){this.app.jR().rG(H,E)});
g.gK.prototype.rG=g.Mt(37,function(H,E){this.Fo.rG(H,E)});
g.g8.prototype.rG=g.Mt(36,function(H,E){H=[H,E];g.BC(this,g.Gm(this.provider),"cfi",H)});
g.$9.prototype.rG=g.Mt(35,function(H,E){this.qoe&&this.qoe.rG(H,E)});
g.Xy.prototype.rG=g.Mt(34,function(H,E){this.eT.rG(H,E)});
g.iX.prototype.rG=g.Mt(33,function(){});
g.NK.prototype.cL=g.Mt(32,function(H,E,G){this.app.jR().cL(H,E,G)});
g.gK.prototype.cL=g.Mt(31,function(H,E,G){this.Fo.cL(H,E,G)});
g.g8.prototype.cL=g.Mt(30,function(H,E,G){if(this.z$!==H||this.gt!==E)E=E==="rawcc"?"":E,G=[H,E,this.z$,G],this.provider.X.Bo().L.A7(g.Ka)&&!this.s7&&G.push("sms.0"),g.BC(this,g.Gm(this.provider),"cfs",G),this.z$=H,this.gt=E,this.s7=!0});
g.$9.prototype.cL=g.Mt(29,function(H,E,G){this.qoe&&this.qoe.cL(H,E,G)});
g.Xy.prototype.cL=g.Mt(28,function(H,E,G){this.eT.cL(H,E,G)});
g.iX.prototype.cL=g.Mt(27,function(){});
g.bs.prototype.vl=g.Mt(12,function(){return this.T});
g.Pi.prototype.vl=g.Mt(11,function(){return this.jR().Wn()});
g.NK.prototype.Wn=g.Mt(10,function(){return this.app.vl()});
g.gK.prototype.Wn=g.Mt(9,function(){return this.Fo.Wn()});
g.Xy.prototype.Wn=g.Mt(8,function(){var H;return((H=this.loader)==null?void 0:H.vl())||null});
g.iX.prototype.Wn=g.Mt(7,function(){return null});
g.MC.prototype.K9=g.Mt(1,function(H){return(H=this.R2(H))?H.L:0});
g.YF.prototype.K9=g.Mt(0,function(){return 0});
var ogM=/#(.)(.)(.)/,sA$=/^#(?:[0-9a-f]{3}){1,2}$/i,vp3={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};kP.prototype.contains=function(H){H=g.eS(this.segments,H);return H>=0||H<0&&(-H-1)%2===1};
kP.prototype.length=function(){return this.segments.length/2};
g.C(IcJ,g.J);g.M=IcJ.prototype;g.M.G$=function(){g.J.prototype.G$.call(this);this.W&&this.W.cancel()};
g.M.bf=function(){this.seekTo(this.player.getCurrentTime())};
g.M.seekTo=function(H){H-=this.player.YV();var E=this.L;this.L=g.Q3(this.uJ.e$(H).kp);E!==this.L&&this.L_&&this.L_()};
g.M.reset=function(){this.D=new kP;this.C=-1;this.W&&(this.W.cancel(),this.W=null)};
g.M.Sp=function(){this.Iu();var H;if(H=this.L!=null)H=this.L,H=H.uJ.Zv(H);if(H&&!this.W&&!(this.L&&this.L.startTime-this.player.getCurrentTime()>30)){H=this.L;H=H.uJ.YG(H);var E=H.kp[0],G;if((G=this.player.getVideoData())==null?0:G.enableServerStitchedDai)if(G=this.player.Wn()){var P=E.uJ.info.id,Q=E.U7,e=H.kp[0].D;if(this.policy.z$){if(G=G.XP(e,Q,P,3))H.D=G}else if(P=G.Y9(e,Q,P,3))if(G=G.dN(Q),G===0)P&&(H.L=new g.uo(P));else if(G===2){this.B.start();ujK(this)&&this.seekTo(this.player.getCurrentTime());
return}}E.uJ.index.Pn(E.U7)?(this.D.contains(H.kp[0].U7)||cLo(this,H),this.L=g.Q3(H.kp)):ujK(this)&&this.seekTo(this.player.getCurrentTime())}this.B.start()};
g.C(gX,g.iv);g.M=gX.prototype;g.M.Y4=function(H,E,G){var P=this;this.xQ();E=wP$(this,H.getId());E||(E=H.languageCode,E=this.L.isManifestless?$LD(this,E,"386"):$LD(this,E));if(E){var Q=(E.index.K9(E.index.gH())-E.index.getStartTime(E.index.gH()))*1E3,e=new g.m9U(this.S.K());this.D=new IcJ(e,this.S,E,function(w,t){G.oz(w,H,t,Q)},this.B||g.MQ(E.info),function(){P.D&&P.D.reset();
P.C=!0})}};
g.M.eW=function(){var H=this.C;this.C=!1;return H};
g.M.il=function(H){var E=this.S.K().U("html5_fallback_if_rawcc_missing");var G=this.L.L.rawcc!=null;if(!this.B||!G&&E)E=this.L.isManifestless?MVR(this,"386"):MVR(this);else{if(!G){g.d3(this.logger,386248249,"rawcc used but unavailable");return}E=[new g.qd({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.qd({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}E=g.R(E);
for(G=E.next();!G.done;G=E.next())g.qM(this.W,G.value);H.zA()};
g.M.xQ=function(){this.D&&(this.D.dispose(),this.D=null)};
g.M.rp=function(){return""};
var ii=/^#(?:[0-9a-f]{3}){1,2}$/i;var zkH=["left","right","center","justify"];g.C(qv,g.D);g.M=qv.prototype;g.M.Rl=function(H,E){this.BF=H;this.MZ=E;var G=g.eK(this.element,this.element.parentElement);this.hm=H-G.x;this.au=E-G.y};
g.M.s1=function(H,E){if(H!==this.BF||E!==this.MZ){g.T2(this.element,"ytp-dragging")||g.aG(this.element,"ytp-dragging");var G=g.or(this.element);H=H-this.hm-.02*this.WO;var P=E-this.au-.02*this.ML,Q=(H+G.width/2)/this.maxWidth*3;Q=Math.floor(g.Mo(Q,0,2));var e=(P+G.height/2)/this.maxHeight*3;e=Math.floor(g.Mo(e,0,2));E=Q+e*3;H=(H+Q/2*G.width)/this.maxWidth;H=g.Mo(H,0,1)*100;G=(P+e/2*G.height)/this.maxHeight;G=g.Mo(G,0,1)*100;this.W.params.Y7=E;this.W.params.h2=G;this.W.params.UB=H;this.W.params.isDefault=
!1;this.L.Y7=E;this.L.h2=G;this.L.UB=H;this.L.isDefault=!1;this.WF.Y7=E;this.WF.h2=G;this.WF.UB=H;this.WF.isDefault=!1;this.Zo()}};
g.M.XQ=function(){g.Tn(this.element,"ytp-dragging")};
g.M.Zo=function(){this.cS(this.C)};
g.M.cS=function(H){var E=this.s7?0:Math.min(this.ZA(),this.maxWidth),G=this.BJ(),P=this.s7;if(P){var Q=getComputedStyle(this.D.parentNode);Q=nS(Q.borderLeftWidth)+nS(Q.borderRightWidth)+nS(Q.paddingLeft)+nS(Q.paddingRight)}else Q=0;var e=Q;Q="";this.W.params.o3===3&&(Q="rotate(180deg)");var w=P?"calc(96% - "+e+"px)":"96%";g.AE(this.element,{top:0,left:0,right:"",bottom:"",width:E?E+"px":"",height:G?G+"px":"","max-width":w,"max-height":w,margin:"",transform:""});this.xk(H);Q={transform:Q,top:"",left:"",
width:E?E+"px":"",height:G?G+"px":"","max-width":"","max-height":""};var t=this.L.UB*.96+2;w=this.L.Y7;switch(w){case 0:case 3:case 6:(P=this.L.sT.fontSizeIncrement)&&P>0&&this.L.o3!==2&&this.L.o3!==3&&(t=Math.max(t/(1+P*2),2));Q.left=t+"%";break;case 1:case 4:case 7:Q.left=t+"%";t=this.D.offsetWidth;E||t?(E=E||t+1,Q.width=E+"px",Q["margin-left"]=P?E/-2-e/2+"px":E/-2+"px"):Q.transform+=" translateX(-50%)";break;case 2:case 5:case 8:Q.right=100-t+"%"}P=this.L.h2*.96+2;switch(w){case 0:case 1:case 2:Q.top=
P+"%";break;case 3:case 4:case 5:Q.top=P+"%";(G=G||this.element.clientHeight)?(Q.height=G+"px",Q["margin-top"]=G/-2+"px"):Q.transform+=" translateY(-50%)";break;case 6:case 7:case 8:Q.bottom=100-P+"%"}g.AE(this.element,Q);if(this.T){G=this.D.offsetHeight;P=1;for(E=0;E<H.length;E++)Q=H[E],typeof Q.text==="string"&&(P+=Q.text.split("\n").length-1,Q.append||E===0||P++);G/=P;this.T.style.height=G+"px";this.T.style.width=G+"px";this.element.style.paddingLeft=G+5+"px";this.element.style.paddingRight=G+
5+"px";H=Number(this.element.style.marginLeft.replace("px",""))-G-5;G=Number(this.element.style.marginRight.replace("px",""))-G-5;this.element.style.marginLeft=H+"px";this.element.style.marginRight=G+"px"}};
g.M.xk=function(H){var E;for(E=0;E<H.length&&H[E]===this.C[E];E++);if(this.PF||this.C.length>E)E=0,this.PF=!1,this.C=[],this.B=this.T$=this.O7=null,g.NG(this.D);for(;E<H.length;E++)bqH(this,H[E])};
g.M.ZA=function(){return 0};
g.M.BJ=function(){return 0};
g.M.toString=function(){return g.D.prototype.toString.call(this)};VB3.prototype.clear=function(){this.G=this.time=this.mode=0;this.L=[];this.reset()};
VB3.prototype.reset=function(){this.mode=0;this.D.reset(0);this.T.reset(1)};
var jPD=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Wr.prototype.set=function(H){this.type=H};
Wr.prototype.get=function(){return this.type};
Sw.prototype.clear=function(){this.state=0};
Sw.prototype.update=function(){this.state=this.state===2?1:0};
Sw.prototype.zU=function(){return this.state!==0};
Sw.prototype.matches=function(H,E){return this.zU()&&H===this.Xy&&E===this.qP};
HqR.prototype.reset=function(){this.timestamp=this.L=0};
IU.prototype.updateTime=function(H){for(var E=1;E<=15;++E)for(var G=1;G<=32;++G)this.G[E][G].timestamp=H};
IU.prototype.debugString=function(){for(var H="\n",E=1;E<=15;++E){for(var G=1;G<=32;++G){var P=this.G[E][G];H=P.L===0?H+"_":H+String.fromCharCode(P.L)}H+="\n"}return H};
IU.prototype.reset=function(H){for(var E=0;E<=15;E++)for(var G=0;G<=32;G++)this.G[E][G].reset();this.D=H;this.L=0;this.W=this.row=1};
var kou=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],WnC=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],IUC=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],A9d=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Lno.prototype.reset=function(H,E){this.T=E;this.style.set(2);this.W=this.C;this.D=this.B;this.L=this.W;var G=(H<<2)+(E<<1);this.C.reset(G);this.B.reset(G);this.text.reset((H<<2)+(E<<1)+1)};
TWM.prototype.reset=function(H){this.T=H;this.W.clear();this.D=this.G;this.G.reset(H,0);this.C.reset(H,1)};f8D.prototype.D=function(){};g.C(Z3,g.cP);Z3.prototype.toString=function(){return g.cP.prototype.toString.call(this)};g.C(yI,g.J);yI.prototype.reset=function(){};g.C(AV,g.cP);AV.prototype.toString=function(){return g.cP.prototype.toString.call(this)};
var LS=0;g.C(li,yI);li.prototype.reset=function(){this.B={};this.W=this.L=null;this.C=!0};
li.prototype.G=function(H,E){H=H.firstChild;H.getAttribute("format");E=E||0;Number.isFinite(E);H=Array.from(H.childNodes);H=g.R(H);for(var G=H.next();!G.done;G=H.next())if(G=G.value,G.nodeType===1)switch(G.tagName){case "head":var P=G;break;case "body":var Q=G}if(P)for(P=Array.from(P.childNodes),P=g.R(P),H=P.next();!H.done;H=P.next())if(H=H.value,H.nodeType===1)switch(H.tagName){case "pen":G=H.getAttribute("id");var e=this.pens,w={},t=H.getAttribute("p");t&&Object.assign(w,this.pens[t]);t=dX(H,"b");
t!=null&&(w.bold=t);t=dX(H,"i");t!=null&&(w.italic=t);t=dX(H,"u");t!=null&&(w.underline=t);t=ui(H,"et");t!=null&&(w.charEdgeStyle=t);t=ui(H,"of");t!=null&&(w.offset=t);t=vr(H,"bc");t!=null&&(w.background=t);t=vr(H,"ec");t!=null&&(w.dn=t);t=vr(H,"fc");t!=null&&(w.color=t);t=ui(H,"fs");t!=null&&t!==0&&(w.fontFamily=t);t=Mv(H,"sz");t!==void 0&&(w.fontSizeIncrement=t/100-1);t=Mv(H,"bo");t!==void 0&&(w.backgroundOpacity=t/255);t=Mv(H,"fo");t!==void 0&&(w.textOpacity=t/255);t=ui(H,"rb");t!=null&&t!==10&&
t!==0&&(w.Fe=t>10?t-1:t);H=ui(H,"hg");H!=null&&(w.c7=H);e[G]=w;break;case "ws":G=H.getAttribute("id");this.L_[G]=D1W(this,H);break;case "wp":G=H.getAttribute("id"),this.N[G]=EpW(this,H)}if(Q){P=[];Q=Array.from(Q.childNodes);Q=g.R(Q);for(H=Q.next();!H.done;H=Q.next())if(H=H.value,H.nodeType===1)switch(H.tagName){case "w":this.L=Gr$(this,H,E,!1);(H=this.B[this.L.id])&&H.end>this.L.start&&(H.end=this.L.start);this.B[this.L.id]=this.L;P.push(this.L);break;case "p":var k=H;t=E;G=[];e=k.getAttribute("w")||
this.T;w=!!dX(k,"a");t=(Mv(k,"t")||0)+t;var W=Mv(k,"d")||5E3;w||(!this.C&&this.W&&this.W.windowId===e&&this.W.end>t&&(this.W.end=t),this.W&&this.W.text==="\n"&&(this.W.text=""));var I=w?6:5,A=k.getAttribute("p");A=A?this.pens[A]:null;var m=Array.from(k.childNodes);m.length&&(this.C=k.getAttribute("d")!=null);for(k=0;k<m.length;k++){var u=m[k],v=void 0;k>0&&(w=!0);var n=void 0;u.nodeType===1&&(n=u);if(n&&n.tagName==="s"){if((u=(u=n.getAttribute("p"))?this.pens[u]:null)&&u.Fe&&(u.Fe===1?(u=m.slice(k,
k+4),u.length===4&&(v=kro(t,W,e,w,I,u,this.pens),k+=3)):v=kro(t,W,e,w,I,[n],this.pens)),!v){var O=n;v=t;n=W;u=e;var q=w,N=I,r=O.textContent?O.textContent:"",B=O.getAttribute("p");B=B?this.pens[B]:null;O=Mv(O,"t")||0;v=new Z3(v+O,n-O,N,u,r,q,B)}}else v=new Z3(t,W,I,e,u.textContent||"",w,A);G.push(v);this.W=v}if(G.length>0)for(G[0].windowId===this.T&&(this.L=Gr$(this,H,E,!0),P.push(this.L)),H=g.R(G),G=H.next();!G.done;G=H.next())G=G.value,G.windowId=this.L.id,this.L.L.push(G),P.push(G)}E=P}else E=[];
return E};var yL$=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.C(UK,yI);UK.prototype.reset=function(){this.W.clear()};
UK.prototype.G=function(H,E){var G=JSON.parse(H);if(!G)return[];if(G.pens){H=0;for(var P=g.R(G.pens),Q=P.next();!Q.done;Q=P.next()){Q=Q.value;var e={},w=Q.pParentId;w&&Object.assign(e,this.L.get(w));Q.bAttr&&(e.bold=!0);Q.iAttr&&(e.italic=!0);Q.uAttr&&(e.underline=!0);w=Q.ofOffset;w!=null&&(e.offset=w);Q.szPenSize!==void 0&&(e.fontSizeIncrement=Q.szPenSize/100-1);w=Q.etEdgeType;w!=null&&(e.charEdgeStyle=w);Q.ecEdgeColor!==void 0&&(e.dn=Br(Q.ecEdgeColor));w=Q.fsFontStyle;w!=null&&w!==0&&(e.fontFamily=
w);Q.fcForeColor!==void 0&&(e.color=Br(Q.fcForeColor));Q.foForeAlpha!==void 0&&(e.textOpacity=Q.foForeAlpha/255);Q.bcBackColor!==void 0&&(e.background=Br(Q.bcBackColor));Q.boBackAlpha!==void 0&&(e.backgroundOpacity=Q.boBackAlpha/255);(w=Q.rbRuby)&&w!==10&&(e.Fe=w>10?w-1:w,e.textEmphasis=yL$.get(e.Fe));Q.hgHorizGroup&&(e.c7=Q.hgHorizGroup);this.L.set(H++,e)}}if(G.wsWinStyles)for(H=0,P=g.R(G.wsWinStyles),Q=P.next();!Q.done;Q=P.next())Q=Q.value,e={},(w=Q.wsParentId)?Object.assign(e,this.T.get(w)):Object.assign(e,
this.C),Q.mhModeHint!==void 0&&(e.Zn=Q.mhModeHint),Q.juJustifCode!==void 0&&(e.textAlign=Q.juJustifCode),Q.pdPrintDir!==void 0&&(e.o3=Q.pdPrintDir),Q.sdScrollDir!==void 0&&(e.JW=Q.sdScrollDir),Q.wfcWinFillColor!==void 0&&(e.windowColor=Br(Q.wfcWinFillColor)),Q.wfoWinFillAlpha!==void 0&&(e.windowOpacity=Q.wfoWinFillAlpha/255),this.T.set(H++,e);if(G.wpWinPositions)for(H=0,P=g.R(G.wpWinPositions),Q=P.next();!Q.done;Q=P.next())Q=Q.value,e={},(w=Q.wpParentId)&&Object.assign(e,this.D.get(w)),Q.ahHorPos!==
void 0&&(e.UB=Q.ahHorPos),Q.apPoint!==void 0&&(e.Y7=Q.apPoint),Q.avVerPos!==void 0&&(e.h2=Q.avVerPos),Q.ccCols!==void 0&&(e.Ld=Q.ccCols),Q.rcRows!==void 0&&(e.JH=Q.rcRows),this.D.set(H++,e);if(G.events){H=[];G=g.R(G.events);for(P=G.next();!P.done;P=G.next()){var t=P.value;Q=(t.tStartMs||0)+E;e=t.dDurationMs||0;if(t.id)w=String(t.id),P=$1D(this,t,Q,e,w),H.push(P),this.W.set(w,P);else{t.wWinId?w=t.wWinId.toString():(w="_"+LS++,P=$1D(this,t,Q,e,w),H.push(P),this.W.set(w,P));P=H;var k=t;e===0&&(e=5E3);
t=this.W.get(w);var W=!!k.aAppend,I=W?6:5,A=k.segs,m=null;k.pPenId&&(m=this.L.get(k.pPenId));for(k=0;k<A.length;k++){var u=A[k],v=u.utf8;if(v){var n=u.tOffsetMs||0,O=null;u.pPenId&&(O=this.L.get(u.pPenId));if((t.params.Zn!=null?t.params.Zn:t.L.length>1?1:0)===2&&W&&v==="\n")continue;u=null;var q=[],N;if(N=O&&O.Fe===1){N=A;var r=k;if(r+3>=N.length||!N[r+1].pPenId||!N[r+2].pPenId||!N[r+3].pPenId)N=!1;else{var B=N[r+1].pPenId;(B=this.L.get(B))&&B.Fe&&B.Fe===2?(B=N[r+2].pPenId,B=this.L.get(B),!B||!B.Fe||
B.Fe<3?N=!1:(B=N[r+3].pPenId,N=(B=this.L.get(B))&&B.Fe&&B.Fe===2?!0:!1)):N=!1}}if(N)n=A[k+1].utf8,u=A[k+3].utf8,N=A[k+2].utf8,r=this.L.get(A[k+2].pPenId),v=tVW(v,n,N,u,r),u=new Z3(Q,e,I,w,v,W,O),k+=3;else{if(v.indexOf("<")>-1){var l=void 0;q=O;N=m;r=Q;B=e;var S=n,z=I,Pt=W,eu=[],QM=g.T_("<html>"+v+"</html>");if(!QM.getElementsByTagName("parsererror").length&&((l=QM.firstChild)==null?0:l.childNodes.length))for(l=g.R(QM.firstChild.childNodes),QM=l.next();!QM.done;QM=l.next()){QM=QM.value;var $Q=void 0,
En=void 0,Dj=(En=($Q=QM.textContent)==null?void 0:$Q.replace(/\n/g,""))!=null?En:"";if(QM.nodeType!==3||Dj&&Dj.match(/^ *$/)==null){$Q={};Object.assign($Q,q||N);En=void 0;switch((En=QM)==null?void 0:En.tagName){case "b":$Q.bold=!0;break;case "i":$Q.italic=!0;break;case "u":$Q.underline=!0}eu.push(new Z3(r+S,B-S,z,t.id,Dj,Pt,$Q))}}q=eu}q.length||(q=[new Z3(Q+n,e-n,I,t.id,v,W,O||m)])}if(q.length)for(W=g.R(q),O=W.next();!O.done;O=W.next())O=O.value,P.push(O),t.L.push(O);else u&&(P.push(u),t.L.push(u))}W=
!0}}}E=H}else E=[];return E};g.C(JV,g.iv);JV.prototype.Y4=function(H,E,G){FXM(this.videoData.videoId,H.vssId,G.oz)};
JV.prototype.il=function(H){if(this.audioTrack)for(var E=g.R(this.audioTrack.captionTracks),G=E.next();!G.done;G=E.next())g.qM(this.W,G.value);H.zA()};g.C(YP,qv);YP.prototype.xk=function(H){var E=this.W.L;qv.prototype.xk.call(this,H);for(H=H.length;H<E.length;H++){var G=E[H];if(e&&G.L===Q)var P=e;else{P={};Object.assign(P,G.L);Object.assign(P,bCo);var Q=G.L;var e=P}bqH(this,G,P)}};
var bCo={aaJ:!0};g.C(CS,f8D);CS.prototype.D=function(H,E,G,P,Q){if(G<P){var e="_"+LS++;G=G/1E3-this.C;P=P/1E3-this.C;H=new AV(G,P-G,5,e,{textAlign:0,Y7:0,UB:E*2.5,h2:H*5.33});Q=new Z3(G,P-G,5,e,Q);this.W.push(H);this.W.push(Q)}};
g.C(bi,yI);bi.prototype.G=function(H){H=new CS(H,H.byteLength,this.W);if(p4J(H)){for(;H.byteOffset<H.L.byteLength;)for(H.version===0?H.G=VI(H)*(1E3/45):H.version===1&&(H.G=VI(H)*4294967296+VI(H)),H.T=Ta(H);H.T>0;H.T--){var E=Ta(H),G=Ta(H),P=Ta(H);E&4&&(E&3)===this.track&&(this.track===0||this.track===1)&&(E=this.L,E.L.push({time:H.G,type:this.track,l6:G,b6:P,order:E.L.length}))}PFR(this.L,H);return H.W}return[]};
bi.prototype.reset=function(){this.L.clear()};g.C(XF,qv);g.M=XF.prototype;g.M.Zo=function(){g.au(this.G6)};
g.M.wg=function(){this.element.removeEventListener("transitionend",this.wg,!1);g.Tn(this.element,"ytp-rollup-mode");this.cS(this.U2,!0)};
g.M.BJ=function(){return this.G?this.p_:this.N};
g.M.ZA=function(){return this.G?this.N:this.p_};
g.M.cS=function(H,E){this.U2=H;if(this.W.params.JH){for(var G=0,P=0;P<this.C.length&&G<H.length;P++)this.C[P]===H[G]&&G++;G>0&&G<H.length&&(H=this.C.concat(H.slice(G)));this.FI=this.p_;this.N=this.p_=0;qv.prototype.cS.call(this,H);OqK(this,E)}qv.prototype.cS.call(this,H)};VkC.prototype.unload=function(){this.L!=null&&(this.S.removeEventListener("sabrCaptionsDataLoaded",this.L),this.L=null);this.i4=[];this.S.publish("sabrCaptionsBufferedRangesUpdated",this.i4)};
VkC.prototype.oZ=function(H){return{formatId:g.KJ(H.info.uJ.info,this.T6),U7:H.info.U7+(this.T6?0:1),startTimeMs:H.info.D*1E3,durationMs:H.info.B*1E3}};g.C(rX,g.iv);rX.prototype.Y4=function(H,E,G){this.xQ();E=H.getId();E=E!=null&&E in this.L.L?this.L.L[E]:null;E||(E=H.languageCode,E=this.L.isManifestless?pVW(this,E,"386"):pVW(this,E));E&&(this.D=H,this.C=E,NLW(this.B,G),this.S.publish("sabrCaptionsTrackChanged",g.KJ(E.info,this.L.T6)))};
rX.prototype.il=function(H){var E=this.L.isManifestless?DLZ(this,"386"):DLZ(this);E=g.R(E);for(var G=E.next();!G.done;G=E.next())g.qM(this.W,G.value);H.zA()};
rX.prototype.xQ=function(){this.D&&(this.D=this.C=null,this.B.unload(),this.S.publish("sabrCaptionsTrackChanged",null))};
rX.prototype.rp=function(){return""};var sPM="WEBVTT".split("").map(function(H){return H.charCodeAt(0)});
g.C(ALD,yI);
ALD.prototype.G=function(H,E){H instanceof ArrayBuffer&&(H=g.x$(new Uint8Array(H)));var G=[];H=H.split(iCu);for(var P=1;P<H.length;P++){var Q=H[P],e=E;if(Q!==""&&!qVo.test(Q)){var w=RdZ.exec(Q);if(w&&w.length>=4){var t=lUu(w[1]),k=lUu(w[2])-t;t+=e;var W=(w=w[3])?w.split(" "):[];w={};var I=null;var A="";var m=null,u="";W=g.R(W);for(var v=W.next();!v.done;v=W.next())if(v=v.value.split(":"),v.length===2){var n=v[1];switch(v[0]){case "line":v=n.split(",");v[0].endsWith("%")&&(I=v[0],w.h2=Number.parseInt(I,
10),v.length===2&&(A=v[1].trim()));break;case "position":v=n.split(",");m=v[0];w.UB=Number.parseInt(m,10);v.length===2&&(u=v[1].trim());break;case "align":switch(n){case "start":w.textAlign=0;break;case "middle":w.textAlign=2;break;case "end":w.textAlign=1}}}I||A||(A="end");if(!m)switch(w.textAlign){case 0:w.UB=0;break;case 1:w.UB=100;break;case 2:w.UB=50}if(w.textAlign!=null){I=0;switch(A){case "center":I+=3;break;case "end":I+=6;break;default:I+=0}switch(u){case "line-left":I+=0;break;case "center":I+=
1;break;case "line-right":I+=2;break;default:switch(w.textAlign){case 0:I+=0;break;case 2:I+=1;break;case 1:I+=2}}A=I<0||I>8?7:I;w.Y7=A}Q=Q.substring(RdZ.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=w;w=Q;Q={};if(w.indexOf("<")<0&&w.indexOf("&")<0)e=Nid(t,k,5,u),k=new Z3(t,k,5,e.id,w,!1,g.ZR(Q)?void 0:Q),G.push(e),G.push(k),e.L.push(k);else for(A=w.split(JLC),A.length===1?(w=5,u=Nid(t,k,w,u)):(I=w=6,u=Object.assign({Ld:32},u),u=new AV(t,k,I,"_"+LS++,u)),G.push(u),I=t,m=0;m<A.length;m++)W=A[m],
m%2===0?(v=g.T_("<html>"+W+"</html>"),v.getElementsByTagName("parsererror").length?(n=v.createElement("span"),n.appendChild(v.createTextNode(W))):n=v.firstChild,fUZ(this,I,k-(I-t),w,u,m>0,n,Q,G)):I=lUu(W)+e}RdZ.lastIndex=0}}return G};
var qVo=/^NOTE/,iCu=/(?:\r\n|\r|\n){2,}/,RdZ=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),JLC=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.C(xP,g.J);xP.prototype.clear=function(){this.L&&this.L.dispose();this.L=null};
xP.prototype.reset=function(){this.L&&this.L.reset()};
xP.prototype.G$=function(){g.J.prototype.G$.call(this);this.clear()};var RU={windowColor:"#080808",windowOpacity:0,textAlign:2,Y7:7,UB:50,h2:100,isDefault:!0,sT:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.C(dLJ,g.UM);g.M=dLJ.prototype;g.M.G$=function(){if(this.T||this.E7){var H=this.S.xt();H&&!H.Iu()&&H.Wk()}else KKW(this,!1);g.UM.prototype.G$.call(this)};
g.M.Mm=function(){return this.X.U("html5_honor_caption_availabilities_in_audio_track")&&this.D!=="LIVE"&&this.D!=="SABR_LIVE"};
g.M.lB=function(){if(this.BF)return this.T||this.E7;var H=this.getAudioTrack();if(this.Mm()){if(!H.captionTracks.length)return!1;if(!this.L)return!0}H=MkW(H,g.sn(this.X));return H==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:H==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?D3(this):gg$(this)||D3(this)?!0:edd(this)};
g.M.load=function(){g.UM.prototype.load.call(this);this.L_=this.getAudioTrack();if(this.L)this.W&&(this.MZ.clear(),this.T?uaH(this,!0):this.player.getPresentingPlayerType()!==3&&this.L.Y4(this.W,"json3",this.G6),this.T||this.E7||FF(this)||this.player.GU("captionschanged",g.ex(this.W)));else{var H;this.D==="OFFLINE"?H=new JV(this.player,this.videoData,this.getAudioTrack()):this.D==="SABR_LIVE"?H=new rX(this.videoData.L,this.player):this.D==="LIVE"?H=new gX(this.videoData.L,this.player):this.D==="INNERTUBE"?
H=new g.Ts(this.player,this.videoData,this.getAudioTrack()):H=new g.Rn(this.player,this.videoData.G6,this.videoData.videoId,g.gWw(this.videoData),this.videoData.PL,this.videoData.eventId);this.L=H;g.d(this,this.L);this.L.il(this.G6)}};
g.M.unload=function(){this.T&&this.W?uaH(this,!1):(this.z$&&g.Od(this.z$),this.player.dV("captions"),this.O7=[],this.L&&this.L.xQ(),this.MZ.clear(),this.p_&&this.player.MV(this.p_),this.In());g.UM.prototype.unload.call(this);this.player.z3();this.player.GU("captionschanged",{})};
g.M.create=function(){this.lB()&&this.load();var H;a:{var E,G,P;if(this.X.U("web_player_nitrate_promo_tooltip")&&((E=this.videoData.getPlayerResponse())==null?0:(G=E.captions)==null?0:(P=G.playerCaptionsTracklistRenderer)==null?0:P.enableTouchCaptionsNitrate)){var Q,e;if(E=(H=this.videoData.getPlayerResponse())==null?void 0:(Q=H.captions)==null?void 0:(e=Q.playerCaptionsTracklistRenderer)==null?void 0:e.captionTracks)for(H=g.R(E),Q=H.next();!Q.done;Q=H.next())if(Q=Q.value,Q.kind==="asr"&&Q.languageCode===
"en"){H=!0;break a}}H=!1}H&&this.S.publish("showpromotooltip",this.B.element)};
g.M.zA=function(){var H=MkW(this.player.getAudioTrack(),g.sn(this.X));var E=H==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?aU(this,this.N):H==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&D3(this)?mV(this):gg$(this)||this.N||edd(this)?aU(this,this.N):D3(this)?mV(this):null;if(this.T||this.E7){var G=g.CL(this.L.W,!0);H=[];for(var P=0;P<G.length;P++){var Q=G[P],e=g.pu("TRACK");e.setAttribute("kind","subtitles");e.setAttribute("label",g.y9(Q));e.setAttribute("srclang",g.xr(Q));e.setAttribute("id",Q.toString());
this.E7||e.setAttribute("src",this.L.rp(Q,"vtt"));Q===E&&e.setAttribute("default","1");H.push(e)}E=this.S.xt();E.uF(H);H=E.E2();this.s7&&this.PF.Z(H.textTracks,"change",this.lrp)}else!this.W&&E&&fS(this,E),this.player.GU("onCaptionsTrackListChanged"),this.player.tC("onApiChange")};
g.M.lrp=function(){for(var H=this.S.xt().E2().textTracks,E=null,G=0;G<H.length;G++)if(H[G].mode==="showing")a:{E=g.CL(this.L.W,!0);for(var P=0;P<E.length;P++)if(E[P].toString()===H[G].id){E=E[P];break a}E=null}(this.loaded?this.W:null)!==E&&fS(this,E,!0)};
g.M.Na$=function(){!this.W&&this.T||this.unload()};
g.M.oz=function(H,E,G,P){if(H){var Q;QPd(this,(Q=this.W)!=null?Q:void 0);this.L.eW()&&(this.O7=[],this.S.dV("captions"),OK(this.T$),this.MZ.reset());a:{Q=this.MZ;P=P||0;G=WKC(Q,H,G||0);H=[];try{for(var e=g.R(G),w=e.next();!w.done;w=e.next()){var t=w.value,k=t.trackData,W=t.q1,I=Q.X.U("safari_live_drm_captions_fix");if(typeof k!=="string"){G=H;var A=G.concat;if(I&&opH(k))var m=mLM(Q,k,W);else{var u=Q,v=E,n=k,O=W,q=P;if(!HCM(n))throw Error("Invalid binary caption track data");u.L||(u.L=new bi(q,v));
m=u.L.G(n,O)}var N=A.call(G,m)}else{if(k.substring(0,6)==="WEBVTT")var r=H.concat(mLM(Q,k,W));else{G=H;var B=G.concat;b:{v=u=void 0;n=Q;O=E;if(k[0]==="{")try{n.L||(n.L=new UK(ngR(O)));var l=v=n.L.G(k,W);break b}catch(En){g.h3(En);l=[];break b}var S=g.T_(k);if(!S||!S.firstChild){var z=Error("Invalid caption track data");z.params=k;throw z;}if(S.firstChild.tagName==="timedtext"){if(Number(S.firstChild.getAttribute("format"))===3){n.L||(n.L=new li(ngR(O),n.X));l=u=n.L.G(S,W);break b}var Pt=Error("Unsupported subtitles format in web player (Format2)");
Pt.params=k;throw Pt;}if(S.firstChild.tagName==="transcript"){var eu=Error("Unsupported subtitles format in web player (Format1)");eu.params=k;throw eu;}var QM=Error("Invalid caption track data");QM.params=k;throw QM;}r=B.call(G,l)}N=r}H=N}var $Q=H;break a}catch(En){g.d3(Q.logger,187101178,"Captions parsing failed: "+En.message+". ");Q.clear();$Q=[];break a}$Q=void 0}E=$Q;E.length>0&&($Q=this.W,this.cL($Q,!!$Q,FF(this)?"g":this.N?"m":"s"));this.player.MV(E,void 0,this.D==="LIVE"||this.D==="SABR_LIVE");
!this.N||this.E7||FF(this)||g.vV(this.X)||g.Rp(this.X)||g.qt(this.X)||this.X.Jm==="shortspage"||this.player.isInline()||(g.Od(this.z$),E=OCW({Y7:0,UB:5,h2:5,JH:2,textAlign:0,o3:0,lang:"en"}),this.eR=[E],$Q=["Click "," for settings"],this.hm||(e=new g.vN(g.xz()),g.d(this,e),this.hm=e.element),e=E.end-E.start,(w=g.y9(this.W))&&this.eR.push(new Z3(E.start,e,0,E.id,w)),this.eR.push(new Z3(E.start,e,0,E.id,$Q[0]),new Z3(E.start,e,0,E.id,this.hm,!0),new Z3(E.start,e,0,E.id,$Q[1],!0)),this.player.MV(this.eR),
g.J3(this.z$));!this.N||this.E7||FF(this)||(g.sn(this.X)?za(this,!0):pS(this,!0),this.L_&&(this.L_.D=this.W),this.player.z3());this.N=!1}};
g.M.onCueRangeEnter=function(H){this.O7.push(H);OK(this.T$)};
g.M.onCueRangeExit=function(H){g.Ih(this.O7,H);this.L instanceof gX&&this.L.B&&this.player.hR([H]);OK(this.T$)};
g.M.getCaptionWindowContainerId=function(){return this.B.element.id};
g.M.l5R=function(){Rko(this,this.eR);this.eR=null};
g.M.mK=function(){var H=this;if(!this.FI||!this.T){this.T$.stop();g.oM1(this.Yp);this.O7.sort(g.v9);var E=this.O7;if(this.p_){var G=g.W2(E,function(e){return this.p_.indexOf(e)===-1},this);
G.length&&(E=G)}E=g.R(E);for(G=E.next();!G.done;G=E.next())npM(this,G.value);E=g.R(Object.entries(this.Jm));var P=E.next();for(G={};!P.done;G={pK:void 0,Jx:void 0},P=E.next()){var Q=g.R(P.value);P=Q.next().value;Q=Q.next().value;G.pK=P;G.Jx=Q;this.Yp[G.pK]?(G.Jx.element.parentNode||(G.Jx instanceof XF||G.Jx instanceof YP||g.ve(this.Jm,function(e){return function(w,t){t!==e.pK&&w.W.params.Y7===e.Jx.W.params.Y7&&w.W.params.UB===e.Jx.W.params.UB&&w.W.params.h2===e.Jx.W.params.h2&&(w.dispose(),delete H.Jm[t]);
return t===e.pK}}(G),this),this.B.element.appendChild(G.Jx.element)),G.Jx.cS(this.Yp[G.pK])):(G.Jx.dispose(),delete this.Jm[G.pK])}}};
g.M.EHo=function(){S73(this,{},!0);this.player.GU("captionssettingschanged")};
g.M.gp7=function(){var H=RU.sT;H={background:H.background,backgroundOpacity:H.backgroundOpacity,charEdgeStyle:H.charEdgeStyle,color:H.color,fontFamily:H.fontFamily,fontSizeIncrement:H.fontSizeIncrement,fontStyle:H.bold&&H.italic?3:H.bold?1:H.italic?2:0,textOpacity:H.textOpacity,windowColor:RU.windowColor,windowOpacity:RU.windowOpacity};var E=QAH()||{};E.background!=null&&(H.background=E.background);E.backgroundOverride!=null&&(H.backgroundOverride=E.backgroundOverride);E.backgroundOpacity!=null&&
(H.backgroundOpacity=E.backgroundOpacity);E.backgroundOpacityOverride!=null&&(H.backgroundOpacityOverride=E.backgroundOpacityOverride);E.charEdgeStyle!=null&&(H.charEdgeStyle=E.charEdgeStyle);E.charEdgeStyleOverride!=null&&(H.charEdgeStyleOverride=E.charEdgeStyleOverride);E.color!=null&&(H.color=E.color);E.colorOverride!=null&&(H.colorOverride=E.colorOverride);E.fontFamily!=null&&(H.fontFamily=E.fontFamily);E.fontFamilyOverride!=null&&(H.fontFamilyOverride=E.fontFamilyOverride);E.fontSizeIncrement!=
null&&(H.fontSizeIncrement=E.fontSizeIncrement);E.fontSizeIncrementOverride!=null&&(H.fontSizeIncrementOverride=E.fontSizeIncrementOverride);E.fontStyle!=null&&(H.fontStyle=E.fontStyle);E.fontStyleOverride!=null&&(H.fontStyleOverride=E.fontStyleOverride);E.textOpacity!=null&&(H.textOpacity=E.textOpacity);E.textOpacityOverride!=null&&(H.textOpacityOverride=E.textOpacityOverride);E.windowColor!=null&&(H.windowColor=E.windowColor);E.windowColorOverride!=null&&(H.windowColorOverride=E.windowColorOverride);
E.windowOpacity!=null&&(H.windowOpacity=E.windowOpacity);E.windowOpacityOverride!=null&&(H.windowOpacityOverride=E.windowOpacityOverride);return H};
g.M.I_=function(H,E){var G={};Object.assign(G,QAH());Object.assign(G,H);S73(this,G,E);this.player.GU("captionssettingschanged")};
g.M.In=function(){!this.T&&this.loaded&&(g.kn(this.Jm,function(H,E){H.dispose();delete this.Jm[E]},this),this.mK())};
g.M.Mf=function(H,E){switch(H){case "fontSize":if(isNaN(E))break;H=g.Mo(E,-2,4);this.I_({fontSizeIncrement:H});return H;case "reload":E&&!this.T&&fS(this,this.W,!0);break;case "stickyLoading":E!==void 0&&this.X.N&&(g.sn(this.X)?za(this,!!E):pS(this,!!E));break;case "track":return acD(this,E);case "tracklist":return this.L?g.wH(g.CL(this.L.W,!(!E||!E.includeAsr)),function(G){return g.ex(G)}):[];
case "translationLanguages":return this.L?this.L.T.map(function(G){return Object.assign({},G)}):[];
case "sampleSubtitles":this.T||E===void 0||KKW(this,!!E);break;case "sampleSubtitlesCustomized":this.T||KKW(this,!!E,E);break;case "recommendedTranslationLanguages":return g.zi();case "defaultTranslationSourceTrackIndices":return this.L?this.L.N:[]}};
g.M.getOptions=function(){var H="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.X.N&&H.push("stickyLoading");return H};
g.M.EY=function(){var H=this.W;if(this.S.ZG("captions")){if(this.X.U("html5_modify_caption_vss_logging")){var E;return(H=(E=this.videoData.qF)!=null?E:null)?{cc:g.N3s(H)}:{}}if(H)return E=H.vssId,H.translationLanguage&&E&&(E="t"+E+"."+g.xr(H)),{cc:E}}return{}};
g.M.oxo=function(){this.isSubtitlesOn()?(g.sn(this.X)?za(this,!1):pS(this,!1),QPd(this),fS(this,null,!0)):this.Mw()};
g.M.Mw=function(){var H=FF(this)||!this.W?aU(this,!0):this.W;H&&this.rG(H.vssId,"m");this.isSubtitlesOn()||fS(this,FF(this)||!this.W?aU(this,!0):this.W,!0)};
g.M.isSubtitlesOn=function(){return!!this.loaded&&!!this.W&&!FF(this)};
g.M.C47=function(){var H=FF(this);D3(this,H)?fS(this,this.getAudioTrack().L,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Mm()&&(this.N=!1,this.W=null,this.L&&(this.L.dispose(),this.L=null)),this.lB()&&(H?fS(this,aU(this,!1),!1):this.load()))};
g.M.bS=function(H){H&&(this.WF={top:H.top,right:H.right,bottom:H.bottom,left:H.left,width:1-H.left-H.right,height:1-H.top-H.bottom},this.B.element.style.top=this.WF.top*100+"%",this.B.element.style.left=this.WF.left*100+"%",this.B.element.style.width=this.WF.width*100+"%",this.B.element.style.height=this.WF.height*100+"%",this.B.element.style.position="absolute",H=jAd(this))&&(this.B.element.style.width=H.width+"px",this.B.element.style.height=H.height+"px")};
g.M.onVideoDataChange=function(H,E){H==="newdata"&&(this.videoData=E,this.loaded&&this.unload(),this.N=!1,this.W=null,this.L&&(this.L.dispose(),this.L=null,this.player.GU("captionschanged",{})),this.lB()&&this.load())};
g.M.getAudioTrack=function(){return this.player.getAudioTrack()};
g.M.mVx=function(){var H=this.S.xt();H&&!H.Iu()&&H.Wk();this.S.isFullscreen()?(this.T=this.BF=!0,this.loaded&&this.zA()):(this.BF=this.X.controlsType==="3",this.T=PTK(this));fS(this,this.W)};
g.M.Mt=function(){var H,E,G,P=(H=this.videoData.getPlayerResponse())==null?void 0:(E=H.captions)==null?void 0:(G=E.playerCaptionsTracklistRenderer)==null?void 0:G.openTranscriptCommand;P&&this.player.n_("innertubeCommand",P)};
g.M.cL=function(H,E,G){var P=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,Q="";H&&(Q=H.vssId,Q=Q.replace(P,""));var e="";H&&H.getId()&&(e=H.getId()||"");H&&H.getXtags()&&(H=H.getXtags(),H=H.replace(P,""),e=e.concat(";"+H));this.S.cL(E?Q:"",E?e:"",G)};
g.M.rG=function(H,E){H=(H||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");H.length>0&&this.S.rG(H,E)};g.IK("captions",dLJ);})(_yt_player);
