(function(g){var window=this;'use strict';var wJ=function(H){g.D.call(this,{J:"div",QN:["ytp-upnext","ytp-player-content"],j:{"aria-label":"{{aria_label}}"},V:[{J:"div",Y:"ytp-cued-thumbnail-overlay-image",j:{style:"{{background}}"}},{J:"span",Y:"ytp-upnext-top",V:[{J:"span",Y:"ytp-upnext-header",iJ:"Up Next"},{J:"span",Y:"ytp-upnext-title",iJ:"{{title}}"},{J:"span",Y:"ytp-upnext-author",iJ:"{{author}}"}]},{J:"a",Y:"ytp-upnext-autoplay-icon",j:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{J:"svg",j:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},V:[{J:"circle",Y:"ytp-svg-autoplay-circle",j:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{J:"circle",Y:"ytp-svg-autoplay-ring",j:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{J:"path",Y:"ytp-svg-fill",j:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{J:"span",Y:"ytp-upnext-bottom",V:[{J:"span",Y:"ytp-upnext-cancel"},
{J:"span",Y:"ytp-upnext-paused",iJ:"Autoplay is paused"}]}]});this.api=H;this.cancelButton=null;this.T=this.HF("ytp-svg-autoplay-ring");this.G=this.notification=this.L=this.suggestion=null;this.D=new g.Wt(this.Bp,5E3,this);this.W=0;var E=this.HF("ytp-upnext-cancel");this.cancelButton=new g.D({J:"button",QN:["ytp-upnext-cancel-button","ytp-button"],j:{tabindex:"0","aria-label":"Cancel autoplay"},iJ:"Cancel"});g.d(this,this.cancelButton);this.cancelButton.listen("click",this.g$,this);this.cancelButton.mx(E);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.d(this,this.D);this.api.createClientVe(this.element,this,18788);E=this.HF("ytp-upnext-autoplay-icon");this.Z(E,"click",this.Ws);this.api.createClientVe(E,this,115130);this.HC();this.Z(H,"autonavvisibility",this.HC);this.Z(H,"mdxnowautoplaying",this.Eqo);this.Z(H,"mdxautoplaycanceled",this.QMR);g.Bt(this.element,"ytp-upnext-mobile",this.api.K().W)},oaW=function(H){return H.isBackground()&&H.tE()},hM=function(H){return g.F8(H.player)&&
H.V4()&&!H.D},eDZ=function(H){H=H.K();
return H.WO&&!H.g6&&!H.disableOrganicUi},wDo=function(H){$q.call(this,H,"videowall-endscreen");
var E=this;this.S=H;this.stills=[];this.G=this.videoData=null;this.D=this.C=!1;this.B=null;g.aG(this.element,"modern-videowall-endscreen");this.W=new g.Z0(this);g.d(this,this.W);this.T=new g.Wt(function(){g.aG(E.element,"ytp-show-tiles")},0);
g.d(this,this.T);this.table=new g.vN({J:"div",Y:"ytp-modern-endscreen-content"});g.d(this,this.table);this.table.mx(this.element);H.getVideoData().au?this.L=new tM(H,!0):this.L=new wJ(H);g.d(this,this.L);g.as(this.player,this.L.element,4);H.createClientVe(this.element,this,158789);this.hide()},kq=function(H){var E=H.K(),G=g.pC||g.zk?{style:"will-change: opacity"}:void 0,P=E.D,Q=["ytp-videowall-still"];
E.W&&Q.push("ytp-videowall-show-text");g.D.call(this,{J:"a",QN:Q,j:{href:"{{url}}",target:P?E.L_:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{J:"div",Y:"ytp-videowall-still-image",j:{style:"{{background}}"}},{J:"span",Y:"ytp-videowall-still-info",j:{"aria-hidden":"true"},V:[{J:"span",Y:"ytp-videowall-still-info-bg",V:[{J:"span",Y:"ytp-videowall-still-info-content",j:G,V:[{J:"span",Y:"ytp-videowall-still-info-title",iJ:"{{title}}"},
{J:"span",Y:"ytp-videowall-still-info-author",iJ:"{{author_and_views}}"},{J:"span",Y:"ytp-videowall-still-info-live",iJ:"Live"},{J:"span",Y:"ytp-videowall-still-info-duration",iJ:"{{duration}}"}]}]}]},{J:"span",QN:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],j:{"aria-hidden":"true"},V:[{J:"span",Y:"ytp-videowall-still-listlabel-icon"},"Playlist",{J:"span",Y:"ytp-videowall-still-listlabel-length",V:[" (",{J:"span",iJ:"{{playlist_length}}"},")"]}]},{J:"span",QN:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],j:{"aria-hidden":"true"},V:[{J:"span",Y:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{J:"span",Y:"ytp-videowall-still-listlabel-length",iJ:" (50+)"}]}]});this.suggestion=null;this.W=P;this.api=H;this.L=new g.Z0(this);g.d(this,this.L);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.L.Z(H,"videodatachange",this.onVideoDataChange);H.createServerVe(this.element,this);this.onVideoDataChange()},hD$=function(H,E){H.n_("onAutonavCoundownStarted",
E)},W1=function(H){$q.call(this,H,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.D({J:"div",Y:"ytp-suggestion-panel",V:[{J:"div",QN:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],iJ:"More videos"}]});this.B=new g.D({J:"div",Y:"ytp-suggestions-container"});this.videos=[];this.G=null;this.T=this.C=!1;this.W=new tM(this.player);g.d(this,this.W);this.W.mx(this.element);H.getVideoData().au?this.L=this.W:(this.L=new wJ(H),g.as(this.player,this.L.element,4),g.d(this,this.L));this.overlay=new g.D({J:"div",
Y:"ytp-autonav-overlay-cancelled-state"});g.d(this,this.overlay);this.overlay.mx(this.element);this.D=new g.Z0(this);g.d(this,this.D);g.d(this,this.table);this.table.mx(this.element);this.table.show();g.d(this,this.B);this.B.mx(this.table.element);this.hide()},I_=function(H){return g.F8(H.player)&&H.V4()&&!H.G},AM=function(H){var E=H.WY();
E!==H.T&&(H.T=E,$2J(H.player),H.T?(H.W!==H.L&&H.W.hide(),H.table.hide()):(H.W!==H.L&&H.W.show(),H.table.show()))},$q=function(H,E){g.D.call(this,{J:"div",
QN:["html5-endscreen","ytp-player-content",E||"base-endscreen"]});this.created=!1;this.player=H},mc=function(H){var E=H.K(),G=E.D;
g.D.call(this,{J:"a",Y:"ytp-autonav-suggestion-card",j:{href:"{{url}}",target:G?E.L_:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{J:"div",QN:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],j:{style:"{{background}}"},V:[{J:"div",j:{"aria-label":"{{timestamp}}"},QN:["ytp-autonav-timestamp"],iJ:"{{duration}}"},{J:"div",QN:["ytp-autonav-live-stamp"],iJ:"Live"},{J:"div",
QN:["ytp-autonav-upcoming-stamp"],iJ:"Upcoming"},{J:"div",Y:"ytp-autonav-list-overlay",V:[{J:"div",Y:"ytp-autonav-mix-text",iJ:"Mix"},{J:"div",Y:"ytp-autonav-mix-icon"}]}]},{J:"div",QN:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],iJ:"{{title}}"},{J:"div",QN:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],iJ:"{{author}}"},{J:"div",QN:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],iJ:"{{views_and_publish_time}}"}]});this.S=H;this.suggestion=
null;this.L=G;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},u9=function(H){$q.call(this,H,"videowall-endscreen");
var E=this;this.S=H;this.G=0;this.stills=[];this.D=this.videoData=null;this.T=this.B=!1;this.N=null;this.W=new g.Z0(this);g.d(this,this.W);this.C=new g.Wt(function(){g.aG(E.element,"ytp-show-tiles")},0);
g.d(this,this.C);var G=new g.D({J:"button",QN:["ytp-button","ytp-endscreen-previous"],j:{"aria-label":"Previous"},V:[g.Zn()]});g.d(this,G);G.mx(this.element);G.listen("click",this.uj,this);this.table=new g.vN({J:"div",Y:"ytp-endscreen-content"});g.d(this,this.table);this.table.mx(this.element);G=new g.D({J:"button",QN:["ytp-button","ytp-endscreen-next"],j:{"aria-label":"Next"},V:[g.sx()]});g.d(this,G);G.mx(this.element);G.listen("click",this.Hs,this);H.getVideoData().au?this.L=new tM(H,!0):this.L=
new wJ(H);g.d(this,this.L);g.as(this.player,this.L.element,4);H.createClientVe(this.element,this,158789);this.hide()},tXH=function(H,E){if(E)return E;
if(H.api.isFullscreen()){var G;H=(G=H.api.getVideoData())==null?void 0:G.sV;return H===-1||H===void 0?8E3:H}return H.api.tJ()>=0?H.api.tJ():g.hE(H.api.K().experiments,"autoplay_time")||1E4},v1=function(H){var E=H.S.qS(!0,H.S.isFullscreen());
g.Bt(H.container.element,"ytp-autonav-endscreen-small-mode",H.jA(E));g.Bt(H.container.element,"ytp-autonav-endscreen-is-premium",!!H.suggestion&&!!H.suggestion.ssu);g.Bt(H.S.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!H.S.WY());g.Bt(H.S.getRootNode(),"countdown-running",H.tv());g.Bt(H.container.element,"ytp-player-content",H.S.WY());g.AE(H.overlay.element,{width:E.width+"px"});if(!H.tv()){H.S.WY()?kyH(H,Math.round(W0$(H)/1E3)):kyH(H);E=!!H.suggestion&&!!H.suggestion.Rf;var G=H.S.WY()||
!E;g.Bt(H.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!G&&E);g.Bt(H.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",G&&!E);H.W.BT(H.S.WY());g.Bt(H.element,"ytp-enable-w2w-color-transitions",IEW(H))}},Azd=function(H,E){g.D.call(this,{J:"button",
QN:["ytp-watch-on-youtube-button","ytp-button"],iJ:"{{content}}"});this.S=H;this.buttonType=this.buttonType=E;this.pD();this.buttonType===2&&g.aG(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.pD);this.BT(!0)},kyH=function(H,E){E=E===void 0?-1:E;
H=H.L.HF("ytp-autonav-endscreen-upnext-header");g.NG(H);if(E>=0){E=String(E);var G="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],P="Up next in $SECONDS".indexOf(G);if(P>=0){H.appendChild(g.HL("Up next in $SECONDS".slice(0,P)));var Q=g.pu("span");g.Ve(Q,"ytp-autonav-endscreen-upnext-header-countdown-number");g.rA(Q,E);H.appendChild(Q);H.appendChild(g.HL("Up next in $SECONDS".slice(P+G.length)));return}}g.rA(H,"Up next")},m2o=function(H,E){E=tXH(H,E);
var G=Math,P=G.min;var Q=(0,g.ON)()-H.W;G=P.call(G,Q,E);E=E===0?1:Math.min(G/E,1);H.T.setAttribute("stroke-dashoffset",""+-211*(E+1));E>=1&&H.tv()&&H.api.getPresentingPlayerType()!==3?H.select(!0):H.tv()&&H.L.start()},Mw=function(H){$q.call(this,H,"watch-again-on-youtube-endscreen");
this.watchButton=new Azd(H,1);g.d(this,this.watchButton);this.watchButton.mx(this.element);g.QT1(H)&&(this.L=new g.CU(H),g.d(this,this.L),this.W=new g.D({J:"div",QN:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],j:{tabIndex:"-1"},V:[this.L]}),g.d(this,this.W),this.L.mx(this.W.element),this.W.mx(this.element));H.createClientVe(this.element,this,156914);this.hide()},d2R=function(H){g.UM.call(this,H);
var E=this;this.endScreen=null;this.L=this.W=this.G=!1;this.listeners=new g.Z0(this);g.d(this,this.listeners);var G=H.K();H.isEmbedsShortsMode()?this.endScreen=new Mw(H):eDZ(H)?(this.G=!0,uTJ(this),this.L?this.endScreen=new W1(H):G.U("delhi_modern_endscreen")?this.endScreen=new wDo(H):this.endScreen=new u9(H)):G.g6?this.endScreen=new vaM(H):this.endScreen=new $q(H);g.d(this,this.endScreen);g.as(H,this.endScreen.element,4);MXd(this);this.listeners.Z(H,"videodatachange",this.onVideoDataChange,this);
this.listeners.Z(H,g.Ya("endscreen"),function(P){E.onCueRangeEnter(P)});
this.listeners.Z(H,g.XT("endscreen"),function(P){E.onCueRangeExit(P)})},dJ=function(H){var E=H.WY();
E!==H.C&&(H.C=E,$2J(H.player))},$2J=function(H){H.publish("autonavvisibility")},vaM=function(H){$q.call(this,H,"subscribecard-endscreen");
this.L=new g.D({J:"div",Y:"ytp-subscribe-card",V:[{J:"img",Y:"ytp-author-image",j:{src:"{{profilePicture}}"}},{J:"div",Y:"ytp-subscribe-card-right",V:[{J:"div",Y:"ytp-author-name",iJ:"{{author}}"},{J:"div",Y:"html5-subscribe-button-container"}]}]});g.d(this,this.L);this.L.mx(this.element);var E=H.getVideoData();this.subscribeButton=new g.FE("Subscribe",null,"Unsubscribe",null,!0,!1,E.t_,E.subscribed,"trailer-endscreen",null,H,!1);g.d(this,this.subscribeButton);this.subscribeButton.mx(this.L.HF("html5-subscribe-button-container"));
this.Z(H,"videodatachange",this.r5);this.r5();this.hide()},na3=function(H,E){E=E.getWatchNextResponse();
var G,P;E=(G=D2o(E))==null?void 0:(P=G.nextButton)==null?void 0:P.buttonRenderer;H.T=E==null?void 0:E.navigationEndpoint;G=E==null?void 0:E.trackingParams;H.playButton&&G&&H.S.setTrackingParams(H.playButton.element,G)},D2o=function(H){var E,G,P;
return H==null?void 0:(E=H.playerOverlays)==null?void 0:(G=E.playerOverlayRenderer)==null?void 0:(P=G.autoplay)==null?void 0:P.playerOverlayAutoplayRenderer},W0$=function(H){if(H.S.isFullscreen()){var E;
H=(E=H.S.getVideoData())==null?void 0:E.sV;return H===-1||H===void 0?8E3:H}return H.S.tJ()>=0?H.S.tJ():g.hE(H.S.K().experiments,"autoplay_time")||1E4},IEW=function(H){var E;
return!((E=H.S.getVideoData())==null||!E.watchToWatchTransitionRenderer)},MXd=function(H){H.player.dV("endscreen");
var E=H.player.getVideoData();E=new g.cP(Math.max((E.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var G=new g.cP(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});H.player.MV([E,G])},aEC=function(H){var E=W0$(H),G=Math,P=G.min;
var Q=H.G?Date.now()-H.G:0;G=P.call(G,Q,E);kyH(H,Math.ceil((E-G)/1E3));E-G<=500&&H.tv()?H.select(!0):H.tv()&&H.D.start()},tM=function(H,E){E=E===void 0?!1:E;
g.D.call(this,{J:"div",Y:"ytp-autonav-endscreen-countdown-overlay"});var G=this;this.C=E;this.cancelCommand=this.T=void 0;this.G=0;this.container=new g.D({J:"div",Y:"ytp-autonav-endscreen-countdown-container"});g.d(this,this.container);this.container.mx(this.element);E=H.K();var P=E.D;this.S=H;this.suggestion=null;this.onVideoDataChange("newdata",this.S.getVideoData());this.Z(H,"videodatachange",this.onVideoDataChange);this.L=new g.D({J:"div",Y:"ytp-autonav-endscreen-upnext-container",j:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{J:"div",Y:"ytp-autonav-endscreen-upnext-header"},{J:"div",Y:"ytp-autonav-endscreen-upnext-alternative-header",iJ:"{{autoplayAlternativeHeader}}"},{J:"a",Y:"ytp-autonav-endscreen-link-container",j:{href:"{{url}}",target:P?E.L_:""},V:[{J:"div",Y:"ytp-autonav-endscreen-upnext-thumbnail",j:{style:"{{background}}"},V:[{J:"div",j:{"aria-label":"{{timestamp}}"},QN:["ytp-autonav-timestamp"],
iJ:"{{duration}}"},{J:"div",QN:["ytp-autonav-live-stamp"],iJ:"Live"},{J:"div",QN:["ytp-autonav-upcoming-stamp"],iJ:"Upcoming"}]},{J:"div",Y:"ytp-autonav-endscreen-video-info",V:[{J:"div",Y:"ytp-autonav-endscreen-premium-badge"},{J:"div",Y:"ytp-autonav-endscreen-upnext-title",iJ:"{{title}}"},{J:"div",Y:"ytp-autonav-endscreen-upnext-author",iJ:"{{author}}"},{J:"div",Y:"ytp-autonav-view-and-date",iJ:"{{views_and_publish_time}}"},{J:"div",Y:"ytp-autonav-author-and-view",iJ:"{{author_and_views}}"}]}]}]});
g.d(this,this.L);this.L.mx(this.container.element);P||this.Z(this.L.HF("ytp-autonav-endscreen-link-container"),"click",this.Jd);this.S.createClientVe(this.container.element,this,115127);this.S.createClientVe(this.L.HF("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.D({J:"div",Y:"ytp-autonav-overlay"});g.d(this,this.overlay);this.overlay.mx(this.container.element);this.W=new g.D({J:"div",Y:"ytp-autonav-endscreen-button-container"});g.d(this,this.W);this.W.mx(this.container.element);
this.cancelButton=new g.D({J:"button",QN:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",E.U("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],j:{"aria-label":"Cancel autoplay"},iJ:"Cancel"});g.d(this,this.cancelButton);this.cancelButton.mx(this.W.element);this.cancelButton.listen("click",this.Lx,this);this.S.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.D({J:"a",QN:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
E.U("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],j:{href:"{{url}}",role:"button","aria-label":"Play next video"},iJ:"Play Now"});g.d(this,this.playButton);this.playButton.mx(this.W.element);this.playButton.listen("click",this.Jd,this);this.S.createServerVe(this.playButton.element,this.playButton,!0);(E=this.S.getVideoData())&&na3(this,E);this.D=new g.Wt(function(){aEC(G)},500);
g.d(this,this.D);this.Dt();this.Z(H,"autonavvisibility",this.Dt);this.S.U("web_autonav_color_transition")&&(this.Z(H,"autonavchange",this.Fw),this.Z(H,"onAutonavCoundownStarted",this.cGw))},Df=function(H){var E=H.WY();
E!==H.B&&(H.B=E,$2J(H.player))},uTJ=function(H){var E=H.player.getVideoData();
if(!E||H.L===E.n6&&H.W===E.au)return!1;H.L=E.n6;H.W=E.au;return!0};
g.NK.prototype.tJ=g.Mt(6,function(){return this.app.tJ()});
g.Pi.prototype.tJ=g.Mt(5,function(){return this.getVideoData().N6});
g.cB.prototype.Ol=g.Mt(4,function(H){this.d7().Ol(H)});
g.A0.prototype.Ol=g.Mt(3,function(H){this.mT!==H&&(this.mT=H,this.vy())});
g.C(mc,g.D);mc.prototype.select=function(){this.S.OF(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.tI||void 0)&&this.S.logClick(this.element)};
mc.prototype.onClick=function(H){g.k6(H,this.S,this.L,this.suggestion.sessionData||void 0)&&this.select()};
mc.prototype.onKeyPress=function(H){switch(H.keyCode){case 13:case 32:H.defaultPrevented||(this.select(),H.preventDefault())}};g.C(tM,g.D);g.M=tM.prototype;g.M.Q_=function(H){this.suggestion!==H&&(this.suggestion=H,g.So(this.L,H),this.playButton.updateValue("url",this.suggestion.Sd()),v1(this))};
g.M.tv=function(){return this.G>0};
g.M.Fy=function(){this.tv()||(this.G=Date.now(),aEC(this),hD$(this.S,W0$(this)),g.Bt(this.S.getRootNode(),"countdown-running",this.tv()))};
g.M.Jq=function(){this.jf();aEC(this);var H=this.L.HF("ytp-autonav-endscreen-upnext-header");H&&g.rA(H,"Up next")};
g.M.jf=function(){this.tv()&&(this.D.stop(),this.G=0)};
g.M.select=function(H){this.S.nextVideo(!1,H===void 0?!1:H);this.jf()};
g.M.Jd=function(H){g.k6(H,this.S)&&(H.currentTarget===this.playButton.element?this.S.logClick(this.playButton.element):H.currentTarget===this.L.HF("ytp-autonav-endscreen-link-container")&&(H=this.L.HF("ytp-autonav-endscreen-link-container"),this.S.logVisibility(H,!0),this.S.logClick(H)),this.T?(this.S.n_("innertubeCommand",this.T),this.jf()):this.select())};
g.M.Lx=function(){this.S.logClick(this.cancelButton.element);g.hP(this.S,!0);this.cancelCommand&&this.S.n_("innertubeCommand",this.cancelCommand)};
g.M.onVideoDataChange=function(H,E){na3(this,E);H=E.getWatchNextResponse();var G,P;H=(G=D2o(H))==null?void 0:(P=G.cancelButton)==null?void 0:P.buttonRenderer;this.cancelCommand=H==null?void 0:H.command};
g.M.cGw=function(H){if(IEW(this)){var E=this.S.getVideoData().watchToWatchTransitionRenderer,G=E==null?void 0:E.fromColorPaletteDark;E=E==null?void 0:E.toColorPaletteDark;if(G&&E){var P=this.element;P.style.setProperty("--w2w-start-background-color",g.bt(G.surgeColor));P.style.setProperty("--w2w-start-primary-text-color",g.bt(G.primaryTitleColor));P.style.setProperty("--w2w-start-secondary-text-color",g.bt(G.secondaryTitleColor));P.style.setProperty("--w2w-end-background-color",g.bt(E.surgeColor));
P.style.setProperty("--w2w-end-primary-text-color",g.bt(E.primaryTitleColor));P.style.setProperty("--w2w-end-secondary-text-color",g.bt(E.secondaryTitleColor));P.style.setProperty("--w2w-animation-duration",H+"ms")}g.Bt(this.element,"ytp-w2w-animate",!0)}};
g.M.Fw=function(H){this.S.U("web_autonav_color_transition")&&H!==2&&g.Bt(this.element,"ytp-w2w-animate",!1)};
g.M.Dt=function(){var H=this.S.WY();this.C&&this.pP!==H&&this.BT(H);v1(this);this.S.logVisibility(this.container.element,H);this.S.logVisibility(this.cancelButton.element,H);this.S.logVisibility(this.L.HF("ytp-autonav-endscreen-link-container"),H);this.S.logVisibility(this.playButton.element,H)};
g.M.jA=function(H){return H.width<400||H.height<459};g.C($q,g.D);g.M=$q.prototype;g.M.create=function(){this.created=!0};
g.M.destroy=function(){this.created=!1};
g.M.V4=function(){return!1};
g.M.WY=function(){return!1};
g.M.O4=function(){return!1};g.C(wJ,g.D);g.M=wJ.prototype;g.M.Bp=function(){this.notification&&(this.D.stop(),this.Sq(this.G),this.G=null,this.notification.close(),this.notification=null)};
g.M.Q_=function(H){this.suggestion=H;g.So(this,H,"hqdefault.jpg")};
g.M.HC=function(){this.BT(this.api.WY());this.api.logVisibility(this.element,this.api.WY());this.api.logVisibility(this.HF("ytp-upnext-autoplay-icon"),this.api.WY());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.WY())};
g.M.zn_=function(){window.focus();this.Bp()};
g.M.Fy=function(H){var E=this;this.tv()||(g.ky("a11y-announce","Up Next "+this.suggestion.title),this.W=(0,g.ON)(),this.L=new g.Wt(function(){m2o(E,H)},25),m2o(this,H),hD$(this.api,tXH(this,H)));
g.Tn(this.element,"ytp-upnext-autoplay-paused")};
g.M.hide=function(){g.D.prototype.hide.call(this)};
g.M.tv=function(){return!!this.L};
g.M.Jq=function(){this.jf();this.W=(0,g.ON)();m2o(this);g.aG(this.element,"ytp-upnext-autoplay-paused")};
g.M.jf=function(){this.tv()&&(this.L.dispose(),this.L=null)};
g.M.select=function(H){H=H===void 0?!1:H;if(this.api.K().U("autonav_notifications")&&H&&window.Notification&&typeof document.hasFocus==="function"){var E=Notification.permission;E==="default"?Notification.requestPermission():E!=="granted"||document.hasFocus()||(this.Bp(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.QM()}),this.G=this.Z(this.notification,"click",this.zn_),this.D.start())}this.jf();this.api.nextVideo(!1,H)};
g.M.Ws=function(H){!g.wa(this.cancelButton.element,H.target)&&g.k6(H,this.api)&&(this.api.WY()&&this.api.logClick(this.HF("ytp-upnext-autoplay-icon")),this.select())};
g.M.g$=function(){this.api.WY()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.hP(this.api,!0)};
g.M.Eqo=function(H){this.api.getPresentingPlayerType();this.show();this.Fy(H)};
g.M.QMR=function(){this.api.getPresentingPlayerType();this.jf();this.hide()};
g.M.G$=function(){this.jf();this.Bp();g.D.prototype.G$.call(this)};g.C(W1,$q);g.M=W1.prototype;g.M.create=function(){$q.prototype.create.call(this);this.D.Z(this.player,"appresize",this.Ea);this.D.Z(this.player,"onVideoAreaChange",this.Ea);this.D.Z(this.player,"videodatachange",this.onVideoDataChange);this.D.Z(this.player,"autonavchange",this.u9);this.D.Z(this.player,"onAutonavCancelled",this.ij);this.onVideoDataChange()};
g.M.show=function(){$q.prototype.show.call(this);(this.C||this.G&&this.G!==this.videoData.clientPlaybackNonce)&&g.hP(this.player,!1);g.F8(this.player)&&this.V4()&&!this.G?(AM(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||oaW(this.player.Rs())&&this.player.U("web_player_pip_logging_fix")?this.L.select(!0):this.L.Fy():this.videoData.autonavState===3&&this.L.Jq()):(g.hP(this.player,!0),AM(this));this.Ea()};
g.M.hide=function(){$q.prototype.hide.call(this);this.L.Jq();AM(this)};
g.M.Ea=function(){var H=this.player.qS(!0,this.player.isFullscreen());AM(this);v1(this.W);g.Bt(this.element,"ytp-autonav-cancelled-small-mode",this.jA(H));g.Bt(this.element,"ytp-autonav-cancelled-tiny-mode",this.zI(H));g.Bt(this.element,"ytp-autonav-cancelled-mini-mode",H.width<=400||H.height<=360);this.overlay&&g.AE(this.overlay.element,{width:H.width+"px"});if(!this.T)for(H=0;H<this.videos.length;H++)g.Bt(this.videos[H].element,"ytp-suggestion-card-with-margin",H%2===1)};
g.M.onVideoDataChange=function(){var H=this.player.getVideoData();if(this.videoData!==H&&H){this.videoData=H;H=this.videoData.suggestions;var E=g.KR(this.videoData);E&&(this.L.Q_(E),this.L!==this.W&&this.W.Q_(E));if(H&&H.length)for(E=0;E<Ob$.length;++E){var G=Ob$[E];if(H&&H[G]){this.videos[E]=new mc(this.player);var P=this.videos[E];G=H[G];P.suggestion!==G&&(P.suggestion=G,g.So(P,G));g.d(this,this.videos[E]);this.videos[E].mx(this.B.element)}}this.Ea()}};
g.M.u9=function(H){H===1?(this.C=!1,this.G=this.videoData.clientPlaybackNonce,this.L.jf(),this.pP&&this.Ea()):(this.C=!0,this.WY()&&(H===2?this.L.Fy():H===3&&this.L.Jq()))};
g.M.ij=function(H){H?this.u9(1):(this.G=null,this.C=!1)};
g.M.V4=function(){return this.videoData.autonavState!==1};
g.M.jA=function(H){return(H.width<910||H.height<459)&&!this.zI(H)&&!(H.width<=400||H.height<=360)};
g.M.zI=function(H){return H.width<800&&!(H.width<=400||H.height<=360)};
g.M.WY=function(){return this.pP&&g.F8(this.player)&&this.V4()&&!this.G};
var Ob$=[1,3,2,4];g.C(wDo,$q);g.M=wDo.prototype;g.M.create=function(){$q.prototype.create.call(this);var H=this.player.getVideoData();H&&(this.videoData=H);this.BW();this.W.Z(this.player,"appresize",this.BW);this.W.Z(this.player,"onVideoAreaChange",this.BW);this.W.Z(this.player,"videodatachange",this.onVideoDataChange);this.W.Z(this.player,"autonavchange",this.KF);this.W.Z(this.player,"onAutonavCancelled",this.G4);H=this.videoData.autonavState;H!==this.B&&this.KF(H);this.W.Z(this.element,"transitionend",this.Dd)};
g.M.destroy=function(){g.hH(this.W);g.dT(this.stills);this.stills=[];$q.prototype.destroy.call(this);g.Tn(this.element,"ytp-show-tiles");this.T.stop();this.B=this.videoData.autonavState};
g.M.V4=function(){return this.videoData.autonavState!==1};
g.M.show=function(){var H=this.pP;$q.prototype.show.call(this);g.Tn(this.element,"ytp-show-tiles");this.player.K().W?g.au(this.T):this.T.start();(this.D||this.G&&this.G!==this.videoData.clientPlaybackNonce)&&g.hP(this.player,!1);I_(this)?(dJ(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||oaW(this.player.Rs())&&this.player.U("web_player_pip_logging_fix")?this.L.select(!0):this.L.Fy():this.videoData.autonavState===3&&this.L.Jq()):(g.hP(this.player,!0),dJ(this));H!==this.pP&&
this.player.logVisibility(this.element,!0)};
g.M.hide=function(){var H=this.pP;$q.prototype.hide.call(this);this.L.Jq();dJ(this);H!==this.pP&&this.player.logVisibility(this.element,!1)};
g.M.Dd=function(H){H.target===this.element&&this.BW()};
g.M.BW=function(){var H,E,G,P;var Q=((H=this.videoData)==null?0:(E=H.suggestions)==null?0:E.length)?(G=this.videoData)==null?void 0:G.suggestions:[(P=this.videoData)==null?void 0:g.KR(P)];if(Q.length){E=this.S.qS(!0,this.S.isFullscreen());H=Math.floor((E.width-64+16)/(g.Mo(E.width*.27,250,450)+16));E=Math.min(3,Math.floor((E.height-64)/((E.width-64-(H-1)*16)/H*.5625+70)));g.YQ(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.aG(this.element,"ytp-modern-endscreen-limit-rows-"+E);g.Bt(this.element,"ytp-modern-endscreen-single-item",H===1);g.Bt(this.element,"ytp-modern-endscreen-row-0",E===0);H=this.table.element;H.ariaLive="polite";this.L.Q_(g.KR(this.videoData));this.L instanceof tM&&v1(this.L);g.Bt(this.element,"ytp-endscreen-takeover",I_(this));dJ(this);E=0;H.ariaBusy="true";G=Q.length;for(P=0;P<G;P++){var e=P%G,w=this.stills[P];w||(w=new g.xW(this.player),this.stills[P]=w,H.appendChild(w.element));g.$x1(w,Q[e]);E++}this.stills.length=
E}};
g.M.onVideoDataChange=function(){var H=this.player.getVideoData(1);this.videoData!==H&&(H!=null&&g.KR(H)?(this.videoData=H,this.BW()):this.player.g5("missg",{vid:(H==null?void 0:H.videoId)||"",cpn:(H==null?void 0:H.clientPlaybackNonce)||""}))};
g.M.O4=function(){return this.L.tv()};
g.M.KF=function(H){H===1?(this.D=!1,this.G=this.videoData.clientPlaybackNonce,this.L.jf(),this.pP&&this.BW()):(this.D=!0,this.pP&&I_(this)&&(H===2?this.L.Fy():H===3&&this.L.Jq()))};
g.M.G4=function(H){if(H){for(H=0;H<this.stills.length;H++)this.S.logVisibility(this.stills[H].element,!0);this.KF(1)}else this.G=null,this.D=!1;this.BW()};
g.M.WY=function(){return this.pP&&I_(this)};g.C(vaM,$q);vaM.prototype.r5=function(){var H=this.player.getVideoData();this.L.update({profilePicture:H.profilePicture,author:H.author});this.subscribeButton.channelId=H.t_;var E=this.subscribeButton;H.subscribed?E.L():E.W()};g.C(kq,g.D);kq.prototype.select=function(){this.api.OF(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.tI||void 0)&&this.api.logClick(this.element)};
kq.prototype.onClick=function(H){if(g.L3(this.api.K())&&this.api.U("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var E=this.suggestion.Sd(),G={};g.T8(this.api,G);E=g.eB(E,G);g.Xb(E,this.api,H)}else g.k6(H,this.api,this.W,this.suggestion.sessionData||void 0)&&this.select()};
kq.prototype.onKeyPress=function(H){switch(H.keyCode){case 13:case 32:H.defaultPrevented||(this.select(),H.preventDefault())}};
kq.prototype.onVideoDataChange=function(){var H=this.api.getVideoData(),E=this.api.K();this.W=H.Xg?!1:E.D};g.C(u9,$q);g.M=u9.prototype;g.M.create=function(){$q.prototype.create.call(this);var H=this.player.getVideoData();H&&(this.videoData=H);this.nB();this.W.Z(this.player,"appresize",this.nB);this.W.Z(this.player,"onVideoAreaChange",this.nB);this.W.Z(this.player,"videodatachange",this.onVideoDataChange);this.W.Z(this.player,"autonavchange",this.k8);this.W.Z(this.player,"onAutonavCancelled",this.Jf);H=this.videoData.autonavState;H!==this.N&&this.k8(H);this.W.Z(this.element,"transitionend",this.lj)};
g.M.destroy=function(){g.hH(this.W);g.dT(this.stills);this.stills=[];$q.prototype.destroy.call(this);g.Tn(this.element,"ytp-show-tiles");this.C.stop();this.N=this.videoData.autonavState};
g.M.V4=function(){return this.videoData.autonavState!==1};
g.M.show=function(){var H=this.pP;$q.prototype.show.call(this);g.Tn(this.element,"ytp-show-tiles");this.player.K().W?g.au(this.C):this.C.start();(this.T||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.hP(this.player,!1);hM(this)?(Df(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||oaW(this.player.Rs())&&this.player.U("web_player_pip_logging_fix")?this.L.select(!0):this.L.Fy():this.videoData.autonavState===3&&this.L.Jq()):(g.hP(this.player,!0),Df(this));H!==this.pP&&
this.player.logVisibility(this.element,!0)};
g.M.hide=function(){var H=this.pP;$q.prototype.hide.call(this);this.L.Jq();Df(this);H!==this.pP&&this.player.logVisibility(this.element,!1)};
g.M.lj=function(H){H.target===this.element&&this.nB()};
g.M.nB=function(){var H,E,G,P;var Q=((H=this.videoData)==null?0:(E=H.suggestions)==null?0:E.length)?(G=this.videoData)==null?void 0:G.suggestions:[(P=this.videoData)==null?void 0:g.KR(P)];if(Q.length){g.aG(this.element,"ytp-endscreen-paginate");var e=this.S.qS(!0,this.S.isFullscreen());if(H=g.X0(this.S))H=H.FM()?48:32,e.width-=H*2;var w=e.width/e.height;P=96/54;E=H=2;var t=Math.max(e.width/96,2),k=Math.max(e.height/54,2);G=Q.length;var W=G*4;for(W-=4;W>0&&(H<t||E<k);){var I=H/2,A=E/2,m=H<=t-2&&W>=
A*4,u=E<=k-2&&W>=I*4;if((I+1)/A*P/w>w/(I/(A+1)*P)&&u)W-=I*4,E+=2;else if(m)W-=A*4,H+=2;else if(u)W-=I*4,E+=2;else break}P=!1;W>=12&&G*4-W<=6&&(E>=4||H>=4)&&(P=!0);W=H*96;t=E*54;w=W/t<w?e.height/t:e.width/W;w=Math.min(w,2);W=Math.floor(Math.min(e.width,W*w));t=Math.floor(Math.min(e.height,t*w));e=this.table.element;e.ariaLive="polite";g.sR(e,W,t);g.AE(e,{marginLeft:W/-2+"px",marginTop:t/-2+"px"});this.L.Q_(g.KR(this.videoData));this.L instanceof tM&&v1(this.L);g.Bt(this.element,"ytp-endscreen-takeover",
hM(this));Df(this);W+=4;t+=4;w=0;e.ariaBusy="true";for(k=0;k<H;k++)for(I=0;I<E;I++)if(A=w,u=0,P&&k>=H-2&&I>=E-2?u=1:I%2===0&&k%2===0&&(I<2&&k<2?I===0&&k===0&&(u=2):u=2),A=g.NQ(A+this.G,G),u!==0){m=this.stills[w];m||(m=new kq(this.player),this.stills[w]=m,e.appendChild(m.element));var v=Math.floor(t*I/E),n=Math.floor(W*k/H),O=Math.floor(t*(I+u)/E)-v-4,q=Math.floor(W*(k+u)/H)-n-4;g.lN(m.element,n,v);g.sR(m.element,q,O);g.AE(m.element,"transitionDelay",(I+k)/20+"s");g.Bt(m.element,"ytp-videowall-still-mini",
u===1);g.Bt(m.element,"ytp-videowall-still-large",u>2);u=Math.max(q,O);g.Bt(m.element,"ytp-videowall-still-round-large",u>=256);g.Bt(m.element,"ytp-videowall-still-round-medium",u>96&&u<256);g.Bt(m.element,"ytp-videowall-still-round-small",u<=96);A=Q[A];m.suggestion!==A&&(m.suggestion=A,u=m.api.K(),v=g.T2(m.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.So(m,A,v),g.L3(u)&&!m.api.U("web_player_log_click_before_generating_ve_conversion_params")&&(u=A.Sd(),v={},g.oT(m.api,"addEmbedsConversionTrackingParams",
[v]),u=g.eB(u,v),m.updateValue("url",u)),(A=(A=A.sessionData)&&A.itct)&&m.api.setTrackingParams(m.element,A));w++}e.ariaBusy="false";g.Bt(this.element,"ytp-endscreen-paginate",w<G);for(Q=this.stills.length-1;Q>=w;Q--)H=this.stills[Q],g.LQ(H.element),g.Vq(H);this.stills.length=w}};
g.M.onVideoDataChange=function(){var H=this.player.getVideoData(1);this.videoData!==H&&(H!=null&&g.KR(H)?(this.G=0,this.videoData=H,this.nB()):this.player.g5("missg",{vid:(H==null?void 0:H.videoId)||"",cpn:(H==null?void 0:H.clientPlaybackNonce)||""}))};
g.M.Hs=function(){this.G+=this.stills.length;this.nB()};
g.M.uj=function(){this.G-=this.stills.length;this.nB()};
g.M.O4=function(){return this.L.tv()};
g.M.k8=function(H){H===1?(this.T=!1,this.D=this.videoData.clientPlaybackNonce,this.L.jf(),this.pP&&this.nB()):(this.T=!0,this.pP&&hM(this)&&(H===2?this.L.Fy():H===3&&this.L.Jq()))};
g.M.Jf=function(H){if(H){for(H=0;H<this.stills.length;H++)this.S.logVisibility(this.stills[H].element,!0);this.k8(1)}else this.D=null,this.T=!1;this.nB()};
g.M.WY=function(){return this.pP&&hM(this)};g.C(Azd,g.D);g.M=Azd.prototype;g.M.pD=function(){switch(this.buttonType){case 1:var H="Watch again on YouTube";var E=156915;break;case 2:H="Continue watching on YouTube";E=156942;break;default:H="Continue watching on YouTube",E=156942}this.update({content:H});this.S.hasVe(this.element)&&this.S.destroyVe(this.element);this.S.createClientVe(this.element,this,E)};
g.M.onClick=function(H){this.S.U("web_player_log_click_before_generating_ve_conversion_params")&&this.S.logClick(this.element);g.Xb(this.getVideoUrl(),this.S,H);this.S.U("web_player_log_click_before_generating_ve_conversion_params")||this.S.logClick(this.element)};
g.M.getVideoUrl=function(){var H=!0;switch(this.buttonType){case 1:H=!0;break;case 2:H=!1}H=this.S.getVideoUrl(H,!1,!1,!0);var E=this.S.K();if(g.L3(E)){var G={};g.L3(E)&&g.oT(this.S,"addEmbedsConversionTrackingParams",[G]);H=g.eB(H,G)}return H};
g.M.logVisibility=function(){this.S.logVisibility(this.element,this.pP&&this.L_)};
g.M.show=function(){g.D.prototype.show.call(this);this.logVisibility()};
g.M.hide=function(){g.D.prototype.hide.call(this);this.logVisibility()};
g.M.qL=function(H){g.D.prototype.qL.call(this,H);this.logVisibility()};g.C(Mw,$q);Mw.prototype.hasSuggestions=function(){var H;return(H=this.L)==null?void 0:H.hasSuggestions()};
Mw.prototype.show=function(){if(this.player.getPlayerState()!==3){$q.prototype.show.call(this);var H=this.W;if(H){var E=this.L.hasSuggestions();g.Bt(this.element,"ytp-shorts-branded-ui",E);E?H.show():H.hide()}var G;(G=g.X0(this.player))==null||G.Ol(!0);this.player.logVisibility(this.element,!0);this.watchButton.qL(!0)}};
Mw.prototype.hide=function(){$q.prototype.hide.call(this);var H;(H=g.X0(this.player))==null||H.Ol(!1);this.player.logVisibility(this.element,!1);this.watchButton.qL(!1)};g.C(d2R,g.UM);g.M=d2R.prototype;g.M.lB=function(){var H=this.player.getVideoData(),E=H.mutedAutoplay&&(H.limitedPlaybackDurationInSeconds>0||H.endSeconds>0||H.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!E)return!0;var G;var P=!!((H==null?0:g.KR(H))||(H==null?0:(G=H.suggestions)==null?0:G.length));P=!eDZ(this.player)||P;H=H.U_;G=this.player.Pl();return P&&!H&&!G&&!E};
g.M.WY=function(){return this.endScreen.WY()};
g.M.iPx=function(){return this.WY()?this.endScreen.O4():!1};
g.M.G$=function(){this.player.dV("endscreen");g.UM.prototype.G$.call(this)};
g.M.load=function(){var H=this.player.getVideoData();var E=H.transitionEndpointAtEndOfStream;if(E&&E.videoId){var G=this.player.lm().GH.get("heartbeat"),P=g.KR(H);!P||E.videoId!==P.videoId||H.gT?(this.player.OF(E.videoId,void 0,void 0,!0,!0,E),G&&G.B0("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),H=!0):H=!1}else H=!1;H||(g.UM.prototype.load.call(this),this.endScreen.show())};
g.M.unload=function(){g.UM.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.M.onCueRangeEnter=function(H){this.lB()&&(this.endScreen.created||this.endScreen.create(),H.getId()==="load"&&this.load())};
g.M.onCueRangeExit=function(H){H.getId()==="load"&&this.loaded&&this.unload()};
g.M.onVideoDataChange=function(){MXd(this);this.G&&uTJ(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.L?this.endScreen=new W1(this.player):this.endScreen=new u9(this.player),g.d(this,this.endScreen),g.as(this.player,this.endScreen.element,4))};g.IK("endscreen",d2R);})(_yt_player);
