(function(){var l=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function aa(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof n&&n];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ba=aa(this);
function p(a,b){if(b)a:{var c=ba;a=a.split(".");for(var e=0;e<a.length-1;e++){var d=a[e];if(!(d in c))break a;c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&b!=null&&l(c,a,{configurable:!0,writable:!0,value:b})}}function ca(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
p("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(e+(f||"")+"_"+d++,f)}function c(f,h){this.h=f;l(this,"description",{configurable:!0,writable:!0,value:h})}if(a)return a;c.prototype.toString=function(){return this.h};var e="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0;return b});
p("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");l(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return da(ca(this))}});return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}function ea(a,b){a instanceof String&&(a+="");var c=0,e=!1,d={next:function(){if(!e&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}e=!0;return{done:!0,value:void 0}}};d[Symbol.iterator]=function(){return d};return d}
p("Array.prototype.keys",function(a){return a?a:function(){return ea(this,function(b){return b})}});/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var r={};function u(a){if(r!==r)throw Error("Bad secret");this.h=a}u.prototype.toString=function(){return this.h};new u("about:blank");new u("about:invalid#zClosurez");var v=[];function w(a){console.warn("A URL with content '"+a+"' was sanitized away.")}v.indexOf(w)===-1&&v.push(w);function x(a,b,c){var e=Array.prototype.slice.call(arguments,2);return function(){var d=e.slice();d.push.apply(d,arguments);return a.apply(b,d)}}function fa(a,b){if(a){var c=Array.prototype.slice.call(arguments,1);try{return a.apply(null,c)}catch(e){return e}}}var y=window.performance&&window.performance.timing&&window.performance.now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};function z(a,b){if(a.forEach)a.forEach(b,void 0);else for(var c=0,e=a.length;c<e;c++)c in a&&b.call(void 0,a[c],c,a)}function A(a,b){if(a.some)return a.some(b,void 0);for(var c=0,e=a.length;c<e;c++)if(c in a&&b.call(void 0,a[c],c,a))return!0;return!1}function C(a){return Object.prototype.toString.call(a)=="[object Array]"?a:[a]};function D(a,b){return E[a]=b}var E=window._spf_state||{};window._spf_state=E;var F={};"config"in E||D("config",F);F=E.config;function G(a){var b=H();a in b&&delete b[a]}function ha(){var a=H();for(b in a)I(a[b])||delete a[b];a=H();var b=parseInt(F["cache-max"],10);b=isNaN(b)?Infinity:b;b=Object.keys(a).length-b;if(!(b<=0))for(var c=0;c<b;c++){var e=Infinity,d;for(d in a)if(a[d].count<e){var f=d;e=a[d].count}delete a[f]}}function I(a){if(!(a&&"data"in a))return!1;var b=a.life;b=isNaN(b)?Infinity:b;a=a.time;return y()-a<b}function J(a){var b=parseInt(E["cache-counter"],10)||0;b++;D("cache-counter",b);a.count=b}
function H(){return"cache-storage"in E?E["cache-storage"]:D("cache-storage",{})};function K(a,b){var c=a.length-b.length;return c>=0&&a.indexOf(b,c)==c}var L=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")};function M(a,b){a=a.split(b);var c=a.length==1;return[a[0],c?"":b,c?"":a.slice(1).join(b)]};function N(a){a.data&&Object.prototype.toString.call(a.data)=="[object String]"&&a.data.lastIndexOf("spf:",0)==0&&O(a.data.substring(4))}function O(a){var b=P[a];b&&(delete P[a],b())}function Q(a){window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent&&window.attachEvent("onmessage",a)}function R(a){window.removeEventListener?window.removeEventListener("message",a,!1):window.detachEvent&&window.detachEvent("onmessage",a)}
var S=function(){function a(){b=!1}if(!window.postMessage)return!1;var b=!0;Q(a);window.postMessage("","*");R(a);return b}(),P={};"async-defers"in E||D("async-defers",P);P=E["async-defers"];S&&("async-listener"in E&&R(E["async-listener"]),Q(N),D("async-listener",N));var T={};"ps-s"in E||D("ps-s",T);T=E["ps-s"];function U(a){var b=document.createElement("a");b.href=a;b.href=b.href;a={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:b.port,pathname:b.pathname,search:b.search,hash:b.hash,username:b.username,password:b.password};a.origin=a.protocol+"//"+a.host;a.pathname&&a.pathname[0]=="/"||(a.pathname="/"+a.pathname);return a}function ia(a){a=U(a);return M(a.href,"#")[0]};/*

 SPF
 (c) 2012-2017 Google Inc.
 https://ajax.googleapis.com/ajax/libs/spf/2.4.0/LICENSE
*/
var ja={},ka={},la={};"rsrc-s"in E||D("rsrc-s",ja);ja=E["rsrc-s"];"rsrc-n"in E||D("rsrc-n",ka);ka=E["rsrc-n"];"rsrc-u"in E||D("rsrc-u",la);la=E["rsrc-u"];var ma={};"js-d"in E||D("js-d",ma);ma=E["js-d"];var na={};"js-u"in E||D("js-u",na);na=E["js-u"];/*

 Copyright 2012-2017 Google Inc. All Rights Reserved.
 Use of this source code is governed by The MIT License.
 SPDX-License-Identifier: MIT
*/
function oa(a,b,c){if(b){b=[];var e=0;c&&(a+="\r\n");var d=a.indexOf("[\r\n",e);for(d>-1&&(e=d+3);(d=a.indexOf(",\r\n",e))>-1;){var f=L(a.substring(e,d));e=d+3;f&&b.push(JSON.parse(f))}d=a.indexOf("]\r\n",e);d>-1&&(f=L(a.substring(e,d)),e=d+3,f&&b.push(JSON.parse(f)));f="";a.length>e&&(f=a.substring(e),c&&K(f,"\r\n")&&(f=f.substring(0,f.length-2)));b=V(b);return{m:b,g:f}}a=JSON.parse(a);b=V(C(a));return{m:b,g:""}}
function V(a){var b=C(a);z(b,function(c){if(c){c.head&&(c.head=W(c.head));if(c.body)for(var e in c.body)c.body[e]=W(c.body[e]);c.foot&&(c.foot=W(c.foot))}});return a}
function W(a){var b=new pa;if(!a)return b;if(Object.prototype.toString.call(a)!="[object String]")return a.scripts&&z(a.scripts,function(c){b.scripts.push({url:c.url||"",text:c.text||"",name:c.name||"",async:c.async||!1})}),a.styles&&z(a.styles,function(c){b.styles.push({url:c.url||"",text:c.text||"",name:c.name||""})}),a.links&&z(a.links,function(c){c.rel=="spf-preconnect"&&b.links.push({url:c.url||"",rel:c.rel||""})}),b.html=a.html||"",b;a=a.replace(qa,function(c,e,d,f){if(e=="script"){e=(e=d.match(X))?
e[1]:"";var h=d.match(ra);h=h?h[1]:"";var k=sa.test(d);d=ta.exec(d);return(d=!d||d[1].indexOf("/javascript")!=-1||d[1].indexOf("/x-javascript")!=-1||d[1].indexOf("/ecmascript")!=-1)?(b.scripts.push({url:h,text:f,name:e,async:k}),""):c}return e=="style"&&(e=(e=d.match(X))?e[1]:"",d=ta.exec(d),d=!d||d[1].indexOf("text/css")!=-1)?(b.styles.push({url:"",text:f,name:e}),""):c});a=a.replace(ua,function(c,e){var d=e.match(va);d=d?d[1]:"";return d=="stylesheet"?(d=(d=e.match(X))?d[1]:"",e=(e=e.match(wa))?
e[1]:"",b.styles.push({url:e,text:"",name:d}),""):d=="spf-preconnect"?(e=(e=e.match(wa))?e[1]:"",b.links.push({url:e,rel:d}),""):c});b.html=a;return b}function pa(){this.html="";this.scripts=[];this.styles=[];this.links=[]}(function(){var a=document.createElement("div");return"transition"in a.style?!0:A(["webkit","Moz","Ms","O","Khtml"],function(b){return b+"Transition"in a.style})})();
var ua=/\x3clink([\s\S]*?)\x3e/ig,qa=/\x3c(script|style)([\s\S]*?)\x3e([\s\S]*?)\x3c\/\1\x3e/ig,sa=/(?:\s|^)async(?:\s|=|$)/i,wa=/(?:\s|^)href\s*=\s*["']?([^\s"']+)/i,X=/(?:\s|^)name\s*=\s*["']?([^\s"']+)/i,va=/(?:\s|^)rel\s*=\s*["']?([^\s"']+)/i,ra=/(?:\s|^)src\s*=\s*["']?([^\s"']+)/i,ta=/(?:\s|^)type\s*=\s*["']([^"']+)["']/i;function xa(a,b,c,e){var d=e||{},f=!1,h=0,k,g=new XMLHttpRequest;g.open(a,b,!0);g.timing={};var m=g.abort;g.abort=function(){clearTimeout(k);g.onreadystatechange=null;m.call(g)};g.onreadystatechange=function(){var q=g.timing;if(g.readyState==2){q.responseStart=q.responseStart||y();if(g.responseType=="json")f=!1;else if(F["assume-all-json-requests-chunked"]||(g.getResponseHeader("Transfer-Encoding")||"").toLowerCase().indexOf("chunked")>-1)f=!0;else{q=g.getResponseHeader("X-Firefox-Spdy");var B=window.chrome&&
chrome.loadTimes&&chrome.loadTimes();B=B&&B.wasFetchedViaSpdy;f=!(!q&&!B)}d.u&&d.u(g)}else g.readyState==3?f&&d.l&&(q=g.responseText.substring(h),h=g.responseText.length,d.l(g,q)):g.readyState==4&&(q.responseEnd=q.responseEnd||y(),window.performance&&window.performance.getEntriesByName&&(g.resourceTiming=window.performance.getEntriesByName(b).pop()),f&&d.l&&g.responseText.length>h&&(q=g.responseText.substring(h),h=g.responseText.length,d.l(g,q)),clearTimeout(k),d.o&&d.o(g))};"responseType"in g&&d.responseType==
"json"&&(g.responseType="json");d.withCredentials&&(g.withCredentials=d.withCredentials);e="FormData"in window&&c instanceof FormData;a=a=="POST"&&!e;if(d.headers)for(var t in d.headers)g.setRequestHeader(t,d.headers[t]),"content-type"==t.toLowerCase()&&(a=!1);a&&g.setRequestHeader("Content-Type","application/x-www-form-urlencoded");d.C>0&&(k=setTimeout(function(){g.abort();d.A&&d.A(g)},d.C));g.timing.fetchStart=y();g.send(c);return g};function ya(a,b,c,e,d){var f=!1;c.responseStart=c.responseEnd=y();b.type&&b.type.lastIndexOf("navigate",0)==0&&(c.navigationStart=c.startTime,F["cache-unified"]||(G(e),f=!0));b.j&&d.type=="multipart"&&z(d.parts,function(h){h.timing||(h.timing={});h.timing.spfCached=!!c.spfCached;h.timing.spfPrefetched=!!c.spfPrefetched;b.j(a,h)});za(a,b,c,d,f)}function Aa(a,b,c){a=c.getResponseHeader("X-SPF-Response-Type")||"";b.h=a.toLowerCase().indexOf("multipart")!=-1}
function Ba(a,b,c,e,d,f,h){if(e.h){f=e.g+f;try{var k=oa(f,!0,h)}catch(g){d.abort();b.i&&b.i(a,g,d);return}b.j&&z(k.m,function(g){g.timing||(g.timing={});g.timing.spfCached=!!c.spfCached;g.timing.spfPrefetched=!!c.spfPrefetched;b.j(a,g)});e.complete=e.complete.concat(k.m);e.g=k.g}}
function Ca(a,b,c,e,d){if(d.timing)for(var f in d.timing)c[f]=d.timing[f];if(d.resourceTiming)if(b.type=="load")for(var h in d.resourceTiming)c[h]=d.resourceTiming[h];else if(window.performance&&window.performance.timing&&(f=window.performance.timing.navigationStart,f+d.resourceTiming.startTime>=c.startTime))for(var k in d.resourceTiming)h=d.resourceTiming[k],h!==void 0&&(K(k,"Start")||K(k,"End")||k=="startTime")&&(c[k]=f+Math.round(h));b.type!="load"&&(c.navigationStart=c.startTime);e.complete.length&&
(e.g=L(e.g),e.g&&Ba(a,b,c,e,d,"",!0));if(d.responseType=="json"){if(!d.response){b.i&&b.i(a,Error("JSON response parsing failed"),d);return}var g=V(C(d.response))}else try{g=oa(d.responseText).m}catch(t){b.i&&b.i(a,t,d);return}if(b.j&&g.length>1)for(e=e.complete.length;e<g.length;e++)d=g[e],d.timing||(d.timing={}),d.timing.spfCached=!!c.spfCached,d.timing.spfPrefetched=!!c.spfPrefetched,b.j(a,d);if(g.length>1){var m;z(g,function(t){t.cacheType&&(m=t.cacheType)});g={parts:g,type:"multipart"};m&&(g.cacheType=
m)}else g=g.length==1?g[0]:{};za(a,b,c,g,!0)}function za(a,b,c,e,d){if(d&&b.method!="POST"&&(d=Da(a,b.current,e.cacheType,b.type,!0))){e.cacheKey=d;var f={response:e,type:b.type||""},h=parseInt(F["cache-lifetime"],10),k=parseInt(F["cache-max"],10);h<=0||k<=0||(k=H(),f={data:f,life:h,time:y(),count:0},J(f),k[d]=f,setTimeout(ha,1E3))}e.timing=c;b.v&&b.v(a,e)}
function Da(a,b,c,e,d){a=ia(a);var f;F["cache-unified"]?f=a:e=="navigate-back"||e=="navigate-forward"?f="history "+a:e=="navigate"?f=(d?"history ":"prefetch ")+a:e=="prefetch"&&(f=d?"prefetch "+a:"");b&&c=="url"?f+=" previous "+b:b&&c=="path"&&(f+=" previous "+U(b).pathname);return f||""}
function Ea(a,b){var c=[];b&&(c.push(a+" previous "+b),c.push(a+" previous "+U(b).pathname));c.push(a);var e=null;A(c,function(d){a:{var f=H();if(d in f){f=f[d];if(I(f)){J(f);f=f.data;break a}G(d)}f=void 0}f&&(e={key:d,response:f.response,type:f.type});return!!f});return e}function Fa(){this.h=!1;this.g="";this.complete=[]};function Y(a,b){if(a){var c=Array.prototype.slice.call(arguments);c[0]=a;c=fa.apply(null,c)}return c!==!1};function Ga(a,b,c,e){Y((a||{}).onError,{url:b,err:c,xhr:e})}function Ha(a,b,c){Y((a||{}).onPartProcess,{url:b,part:c})&&Y((a||{}).onPartDone,{url:b,part:c})}function Ia(a,b,c){var e;(e=c.type=="multipart")||(e=Y((a||{}).onProcess,{url:b,response:c}));e&&Y((a||{}).onDone,{url:b,response:c})}
var Ja={request:function(a,b){b=b||{};b={method:b.method,headers:b.experimental_headers,j:x(Ha,null,b),i:x(Ga,null,b),v:x(Ia,null,b),D:b.postData,type:"",current:window.location.href,B:window.location.href};b.method=((b.method||"GET")+"").toUpperCase();b.type=b.type||"request";var c=a,e=F["url-identifier"]||"";if(e){e=e.replace("__type__",b.type||"");var d=M(c,"#"),f=M(d[0],"?");c=f[0];var h=f[1];f=f[2];var k=d[1];d=d[2];if(e.lastIndexOf("?",0)==0)h&&(e=e.replace("?","&")),f+=e;else{if(e.lastIndexOf(".",
0)==0)if(K(c,"/"))e="index"+e;else{var g=c.lastIndexOf(".");g>-1&&(c=c.substring(0,g))}else K(c,"/")&&e.lastIndexOf("/",0)==0&&(e=e.substring(1));c+=e}c=c+h+f+k+d}e=ia(c);c={};c.spfUrl=e;c.startTime=y();c.fetchStart=c.startTime;h=Da(a,b.current,null,b.type,!1);h=Ea(h,b.current);c.spfPrefetched=!!h&&h.type=="prefetch";c.spfCached=!!h;if(h){a=x(ya,null,a,b,c,h.key,h.response);b=window._spf_state=window._spf_state||{};var m=parseInt(b.uid,10)||0;m++;b=b.uid=m;P[b]=a;S?window.postMessage("spf:"+b,"*"):
window.setTimeout(x(O,null,b),0);a=null}else{h={};if(f=F["request-headers"])for(m in f)k=f[m],h[m]=k==null?"":String(k);if(b.headers)for(m in b.headers)k=b.headers[m],h[m]=k==null?"":String(k);b.B!=null&&(h["X-SPF-Referer"]=b.B);b.current!=null&&(h["X-SPF-Previous"]=b.current);if(m=F["advanced-header-identifier"])h["X-SPF-Request"]=m.replace("__type__",b.type),h.Accept="application/json";m=new Fa;f=x(Ca,null,a,b,c,m);a={headers:h,C:F["request-timeout"],u:x(Aa,null,a,m),l:x(Ba,null,a,b,c,m),o:f,A:f};
b.withCredentials&&(a.withCredentials=b.withCredentials);F["advanced-response-type-json"]&&(a.responseType="json");a=b.method=="POST"?xa("POST",e,b.D,a):xa("GET",e,null,a)}return a}},n=this;n.spf=n.spf||{};var Ka=n.spf,Z;for(Z in Ja)Ka[Z]=Ja[Z];}).call(this);
